### ISSUE TITLE
Right Click is broken.

### ISSUE THREAD

**Issue by smartfrigde** [smartfrigde/armcord#10]
For some reason right click by default in Electron is disabled. Most of the solutions I can find as of now online make you make your own Context Menu but it would be nice to use this context menu built-in to Discord.
![image](https://user-images.githubusercontent.com/37928912/117135381-26fa1780-ada7-11eb-9291-59e1060d04dc.png)

**Comment by smartfrigde** [comment]
Added minimal context menu in latest canary commit which should be enough.

**Comment by he3als** [comment]
Hello, I try to right click on a message and nothing happens. Is this a bug?
