### ISSUE TITLE
not working on Jetpack 5.0 ubuntu 20.04

### ISSUE THREAD

**Issue by leonpano2006** [smartfrigde/armcord#112]
armcord: /lib/aarch64-linux-gnu/libxkbcommon.so.0: version `V_1.0.0' not found (required by armcord)

**Comment by smartfrigde** [comment]
It seems to be fixed by this [pull request made to Electron](https://github.com/electron/electron/pull/34155). This means it's not ArmCord issue but Electron bug. A fix will be available when new Electron release is available.

**Comment by smartfrigde** [comment]
@leonpano2006 [Here's a pre-release build with newer Electron version](https://github.com/ArmCord/ArmCord/releases/tag/devbuild) to make it probably work

**Comment by leonpano2006** [comment]
Wow so fast response
I wonder what is difference between webcord and armcord
And webcord and vscode on my jetson can only be started with --no-sandbox or it will not start
