### ISSUE TITLE
upgrade to minimum of electron 18.2.4 (unable to launch on buster/bionic)

### ISSUE THREAD

**Issue by theofficialgman** [smartfrigde/armcord#117]
see https://github.com/electron/electron/pull/34155

please re-build the current release 3.0.5 as well as your buildscript should target 18.2.4 automatically

**Comment by ryanfortner** [comment]
@smartfrigde

**Comment by lexisother** [comment]
Bumping after less than 24 hours isn't going to help.

**Comment by smartfrigde** [comment]
I'll finish this tommorow, I actually updated the Electron but also had to redo the build script and it's just taking a while.

**Comment by theofficialgman** [comment]
I can see you have been trying... your commit messages are fun. good luck, may bill gates smile upon you

**Comment by ryanfortner** [comment]
It looks like electron has been updated with commit [1489e21](https://github.com/ArmCord/ArmCord/commit/1489e213e5ae468c78a7c4d4be1cc5e8703aa82b)

**Comment by theofficialgman** [comment]
The source has been updated for a week, yes, but they have been struggling with making a release https://github.com/ArmCord/ArmCord/actions

**Comment by smartfrigde** [comment]
Done in version 3.0.6
