### ISSUE TITLE
Feature request: Flatpak version

### ISSUE THREAD

**Issue by Apacelus** [smartfrigde/armcord#122]
Not every Linux distro offers snapd, so it would be nice to have flatpak too.

**Comment by MasicoreLord** [comment]
To add to this not everyone wants to be using snaps

**Comment by smartfrigde** [comment]
Flatpaks require a bit more work than snapd for us. Snap is one command meanwhile Flatpak requires us to do much more work. This will be done eventually, just isn't a priority currently

**Comment by anoraktrend** [comment]
webcord flatpaks are almost a go. maybe after that's completed someone could help package the flatpak

**Comment by smartfrigde** [comment]
Webcord uses Electron Forge, which has [Flatpak support built-in](https://www.electronforge.io/config/makers/flatpak). We're using electron-builder

**Comment by rickdtc** [comment]
I heard that app image is good sooo, gotta test that on my manjaro.

**Comment by Apacelus** [comment]
Is there an ETA you could give us @smartfrigde?

**Comment by smartfrigde** [comment]
This is not a priority however after 3.0.8 releases which should be in a week then I'll try do make one. For the time being you can try appimages as a replacement

**Comment by anoraktrend** [comment]
Appimages aren't suitable for use with Musl + other Libcs, the libc independence of flatpaks are the major benefit of them

**Comment by nickname76** [comment]
I also need a flatpak package

**Comment by tazz4843** [comment]
+1 for flatpak, ArmCord is unusable on Steam Deck without it.

**Comment by smartfrigde** [comment]
Electron-builder has recently added a flatpak builder script, so far I couldn't get it to work but I'll be trying, this is more possible than it ever was

**Comment by orowith2os** [comment]
I'd like to help with making a flatpak and maintaining it on Flathub, is there a manifest in the works yet? If not, I can try n knock out most of the work.

**Comment by smartfrigde** [comment]
@orowith2os sorry for late response, however there have been no working attempts at packaging ArmCord onto Flatpak so if you want to, you can try

**Comment by peepo5** [comment]
> Flatpaks require a bit more work than snapd for us. Snap is one command meanwhile Flatpak requires us to do much more work. This will be done eventually, just isn't a priority currently

cringe

**Comment by orowith2os** [comment]
Should be fairly easy, as ArmCord already provides all the binaries (aarch64 and x86_64) to package it. I'll get on it shortly!

**Comment by orowith2os** [comment]
MR is up to Flathub now! See the above.

**Comment by amsyarzero** [comment]
Sorry if I'm necro-ing an old issue thread, but is Flatpak support still in the works? I wanna learn more about Linux stuff, so if possible, I want to help.

**Comment by smartfrigde** [comment]
> Sorry if I'm necro-ing an old issue thread, but is Flatpak support still in the works? I wanna learn more about Linux stuff, so if possible, I want to help.

@amsyarzero There's already an open PR to Flathub

**Comment by orowith2os** [comment]
@amsyarzero see the above, a MR is linked just before my comment. I'll be submitting some patches to ArmCord and hopefully it'll be added when those land in a release.

**Comment by tazz4843** [comment]
Any updates? Hasn't been much activity on the PR above, and the PR that was pending to ArmCord has since been reverted.

**Comment by orowith2os** [comment]
I'm going to redo that upstream PR when I can, that's pretty much all that needs to be done. I also have plans to use SVGs for the icon rather than PNGs, for the sake of efficiency and scalability.

**Comment by 418teapot2** [comment]
> 

Couldn't they just provide binaries for you to install using your package manager?

**Comment by orowith2os** [comment]
@418teapot2 the issue with that is native package managers tend to not be very suited for complex applications, and especially electron applications where they need to be constantly updated. 

Most native packages will be behind for a week or more, and even then not every distro wants to package electron applications (I know Void Linux has a particular stance against them).

Additionally, if a distro *does* package ArmCord, there could be dependency hell where dependencies aren't what ArmCord expects. This is more common than not, see the EAC issues with glibc and Arch.

Assuming all the previous issues are fixed, native packaging for Electron apps is still really inefficient. Updates for ArmCord can be very large with a package manager that doesn't do delta updates, and distros like to put Electron binaries in their own directory in the root. This means that they can't deduplicate, leading to hundreds of MBs of storage being used unnecessarily.

**Comment by tazz4843** [comment]
My personal need for this is that due to SteamOS limitations, native packages are wiped after a system update. Along that, AppImage Electron apps fail to launch consistently, while flatpaks have reliably worked for me.

**Comment by Apacelus** [comment]
@orowith2os the PR was just accepted and after installing the Flatpak version, it starts in Xwayland.
After forcing native Wayland by editing the flatpak desktop file, there is no Tray Icon anymore

**Comment by Apacelus** [comment]
Oh an I just noticed that screen sharing crashes the app, both in legacy screenshare mode and normal

**Comment by orowith2os** [comment]
Screen sharing and crashing is a known issue I believe, not sure why there's no tray icon and it's starting in Xwayland.... I'll have to do some more testing.

**Comment by orowith2os** [comment]
On the upside, at least there *is* a flatpak now, so this issue can somewhat be considered closed.

**Comment by orowith2os** [comment]
Turns out not starting in Wayland was due to me not setting USE_WAYLAND=1 by default; the console bugs you about this. If anybody finds a solution to the tray icon, I'll gladly merge it.

**Comment by Apacelus** [comment]
~~@orowith2os the app has mobile support, perhaps you could set that flag in the flatpak description
Also, seems like every time the app exits itself, i.e. clicking restart in the settings, I get a crash notif from the system.~~

Nvm, I just found the [flatpak repo](https://github.com/flathub/xyz.armcord.ArmCord), lemme make a bunch of issues there

**Comment by orowith2os** [comment]
Or, better yet, make a merge request yourself. It would very much be appreciated.
