### ISSUE TITLE
Deb icon created in 0x0 directory and is not picked up by system

### ISSUE THREAD

**Issue by theofficialgman** [smartfrigde/armcord#128]
![image](https://user-images.githubusercontent.com/28281419/171282801-416bcae8-0a65-4b4e-9fca-d140e60a96a9.png)

I've only seen this in one other app. not sure exactly how the debs are formed but this is likely a bug with that process. Above is a screenshot of the deb from releases.

**Comment by smartfrigde** [comment]
Related to this [electron-builder issue](https://github.com/electron-userland/electron-builder/issues/5294). Will try to fix tommorow

**Comment by smartfrigde** [comment]
![image](https://user-images.githubusercontent.com/37928912/171491234-ab637740-ae34-4161-90c7-c4bed36116b2.png)
Fixed in latest commit, after the release is ready, I'll close this issue

**Comment by smartfrigde** [comment]
Fixed with latest release

**Comment by theofficialgman** [comment]
verified fixed, thanks
