### ISSUE TITLE
Feature Request: Powercord support

### ISSUE THREAD

**Issue by tazz4843** [smartfrigde/armcord#136]
Hey there! This seems like a really nice project, and it seems to perform a lot better than vanilla Discord. However, it's missing one key feature that I'd kinda need to be willing to switch, which is Powercord support. https://github.com/powercord-org/powercord/

I've already tried modifying Powercord's injectors to point to ArmCord's install directory, but that didn't work, nothing changed. It'd be really nice if support was added, even just for injection, not automatic install.

**Comment by lexisother** [comment]
Impossible. Discord's app is structurally different from ArmCord.
