### ISSUE TITLE
Quitting on macOS doesn't actually quit the app

### ISSUE THREAD

**Issue by colin273** [smartfrigde/armcord#137]
When I attempt to quit ArmCord on macOS using any of the standard methods for quitting a macOS app (listed below), it simply gets rid of the existing ArmCord window without actually quitting the app. I have to force quit the app from either the context menu on ArmCord's dock icon (while holding Option) or macOS's Force Quit menu.

Methods that should quit the app immediately but only get rid of the ArmCord window:

- Cmd Q
- Quit from the menu bar
- Right click on the dock icon and choose Quit
- Ctrl C or Ctrl D in Terminal (when running ArmCord from there)

Clicking the X in the upper right corner of the ArmCord window does the same thing as well.

When I run ArmCord from Terminal and attempt to quit the app, `minimizeToTray: true` is logged to the console and the Discord window disappears if it wasn't already closed, but the app continues running without a window, and without any way to create a new window, until I force quit it.

I'm using ArmCord 3.0.6 on macOS 12.4.

**Comment by smartfrigde** [comment]
Please try latest [latest dev build](https://github.com/ArmCord/ArmCord/releases/tag/devbuild) if possible. It should fix the issue

**Comment by smartfrigde** [comment]
Partially fixed
