### ISSUE TITLE
ArmCord not remembering its size after being closed and reopened

### ISSUE THREAD

**Issue by duckyondiscord** [smartfrigde/armcord#140]
When I start up ArmCord on KDE Plasma, it always starts up in a specific window size.
Even after resizing it, it always uses its default size after starting up.

**Comment by smartfrigde** [comment]
Saving window state (size, etc) will be added in next release.

**Comment by smartfrigde** [comment]
Done in this [commit](https://github.com/ArmCord/ArmCord/commit/86f885c41fafe111494cc2ee93b9a7263c9322b5). Please wait for new release for this to be present in your client. Alternatively use latest dev build in releases tab.
