### ISSUE TITLE
ArmCord conflicts with Electron Mail

### ISSUE THREAD

**Issue by Bens0** [smartfrigde/armcord#146]
sudo rpm -i ~/Downloads/Programs/ArmCord-3.0.7.x86_64.rpm 
        file /usr/lib/.build-id/a2/562c52725bb7caa27cd0de814ec368b8c45e7f from install of ArmCord-3.0.7-1.x86_64 conflicts with file from package electron-mail-5.0.1-1.x86_64

**Comment by smartfrigde** [comment]
Really hard for me to say if it isn't electron-mail issue or even electron-builder issue. Those apps share 0 code other than usage of [electron-builder](https://www.electron.build)

**Comment by smartfrigde** [comment]
[Not ArmCord issue see this.](https://github.com/jgraph/drawio-desktop/issues/259)
