### ISSUE TITLE
Cannot grant ArmCord permission to use my microphone

### ISSUE THREAD

**Issue by skykanin** [smartfrigde/armcord#151]
I'm unable to grant ArmCord permission to use my microphone. I get this red text about having no input devices enabled, but clicking on "access your microphone" does nothing. From looking at the console it seems that the network request is blocked by the client.
![image](https://user-images.githubusercontent.com/3789764/178144819-8c6f620f-9d5e-4c04-b666-7e0de076d9b1.png)
![image](https://user-images.githubusercontent.com/3789764/178144903-8378abd9-0143-4554-87b5-cf35ef596b1b.png)

**Comment by smartfrigde** [comment]
The blocked science requests are blocked Discord trackers. Did you install using Snap/Ubuntu store?

**Comment by skykanin** [comment]
I wrapped the AppImage in a nix package since I'm on NixOS.

To be clear it's detecting my input devices correctly. I just don't have permission to use them for some reason.
![image](https://user-images.githubusercontent.com/3789764/178148039-8415de9a-cde4-4626-99d5-d8d03d86763b.png)

**Comment by smartfrigde** [comment]
Does the microphone work in your browser?

**Comment by skykanin** [comment]
Yes, my microphone works in the browser I just have to give discord permission to use it first:
![image](https://user-images.githubusercontent.com/3789764/178750710-4ff90c0b-f2d5-4a6b-b032-2638fedcbfcd.png)

**Comment by smartfrigde** [comment]
I can't reproduce this issue on my end, can you run ArmCord from terminal and send me the output?

**Comment by skykanin** [comment]
Not sure if there is much to glean, but here is the output:
```
➜  ~ ./result/bin/ArmCord-3.0.7
doneSetup: true
performanceMode: performance
ArmCord has been run before. Skipping setup.
Performance mode enabled
armcordCSP: false
windowStyle: default
windowStyle: default
ArmCord CSP is disabled. The CSP should be managed by third-party plugin.
trayIcon: undefined
ignoreProtocolWarning: undefined
0: undefined
/nix/store/lk3d6cf0mn2qp3y0yw14xj67512hx7w9-ArmCord-3.0.7-extracted/resources/app.asar/ts-out/content/splash.html
inviteWebsocket: true
[WebSocket]ArmCord is listening at 6464
channel: stable
automaticPatches: false
width: 2643
height: 1419
isMaximized: false
Not maximized.
channel: stable
automaticPatches: false
mods: none
minimizeToTray: false
```

**Comment by smartfrigde** [comment]
Can you check what sound system are you running? (pulseaudio, pipewire, alsa etc.)

**Comment by skykanin** [comment]
I'm using pulseaudio

**Comment by smartfrigde** [comment]
Please recheck in the newest version, it could've been an Electron bug.

**Comment by smartfrigde** [comment]
Can't reproduce
