### ISSUE TITLE
VCs fail to work

### ISSUE THREAD

**Issue by ghost** [smartfrigde/armcord#154]
The app is getting my mic input fine but just spams the console not actualy transmitting voice
I can still receive voice
highly doubt this is any help but I dont get any other errors
<img width="612" alt="image" src="https://user-images.githubusercontent.com/89495053/178784598-a8a2ade9-a262-4e3f-93f9-a96aee43e271.png">

**Comment by smartfrigde** [comment]
Platform?

**Comment by ghost** [comment]
Windows 11 x64

**Comment by smartfrigde** [comment]
Please recheck if this issue is still present on the newest version, if so provide app logs from running it in a terminal/cmd in a new issue. You can also reopen this one
