### ISSUE TITLE
streaming doesn't have sounds

### ISSUE THREAD

**Issue by ogmicco** [smartfrigde/armcord#161]
sounds not working on stream

**Comment by westlyroots** [comment]
What OS are you on? If you're on linux, how did you install the package? Are you using the dev build or the main release?

**Comment by ogmicco** [comment]
I'm on Windows 10 1809 and I've tried the dev build and also the main release, both won't work

**Comment by smartfrigde** [comment]
Streaming audio is unsupported currently

**Comment by ogmicco** [comment]
ok. Is there plans to add it in the future?

**Comment by smartfrigde** [comment]
Only for Wayland and PipeWire on Linux

**Comment by zoeleu** [comment]
> Only for Wayland and PipeWire on Linux

Is it implemented?

**Comment by smartfrigde** [comment]
Not yet

**Comment by Kyr4l** [comment]
> Only for Wayland and PipeWire on Linux

many distros still use X11, Wayland isn't well supported by KDE Plasma.
but i guess it won't be implemented for X11 ?

**Comment by zoeleu** [comment]
The only problems with Wayland are Nvidia GPUs. Literally. I am yet to find a problem with Wayland under my AMD GPU.
