### ISSUE TITLE
Option to use system menu bar

### ISSUE THREAD

**Issue by AroPix** [smartfrigde/armcord#164]
**Is your feature request related to a problem? Please describe.**
Im a KDE user and id like to use armcord as it seems a lot snappier and faster, tho it is very bad that the app has its own menu bar as it takes away functionality.

**Describe the solution you'd like**
A option to disable the menu bar drawn by the program, and instead letting the window manager draw it.

**Describe alternatives you've considered**
None.

**Comment by smartfrigde** [comment]
Right click on the tray icon, open settings and change ArmCord style to native.

**Comment by AroPix** [comment]
omg im so dumb thanks for the info! would be nice to make this more clear as i was already searching in the settings.

**Comment by smartfrigde** [comment]
Yeah, next release has redesigned settings with actual descriptions.
