### ISSUE TITLE
Proper wayland support to fix nvidia + wayland issues

### ISSUE THREAD

**Issue by Apacelus** [smartfrigde/armcord#166]
**Is your feature request related to a problem? Please describe.**
NVidia + wayland -> "hickups" when typing in chat. Text has latency over 1 second before appering on screen while typing.

**Describe the solution you'd like**
A proper wayland implementation instead of xwayland.

**Additional context**
Dont blame the nvidia driver, armcord is the only app I am having such issues with.

**Comment by smartfrigde** [comment]
Desktop environment?

**Comment by Apacelus** [comment]
Gnome 42.2

**Comment by smartfrigde** [comment]
If you run armcord through terminal do you see `Wayland specific patches applied.` message somewhere in logs?

**Comment by Apacelus** [comment]
No, here is the terminal output:  
```
doneSetup: true
performanceMode: performance
ArmCord has been run before. Skipping setup.
Performance mode enabled
armcordCSP: true
windowStyle: native
windowStyle: native
Setting up CSP unstricter...
trayIcon: undefined
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
ignoreProtocolWarning: undefined
0: undefined
/tmp/.mount_armcorDcqam5/resources/app.asar/ts-out/content/splash.html
inviteWebsocket: false
MESA-LOADER: failed to retrieve device information
MESA-LOADER: failed to open nvidia-drm: /usr/lib/dri/nvidia-drm_dri.so: cannot open shared object file: Permission denied (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
failed to load driver: nvidia-drm
MESA-LOADER: failed to open kms_swrast: /usr/lib/dri/kms_swrast_dri.so: cannot open shared object file: Permission denied (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
failed to load driver: kms_swrast
MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: Permission denied (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
failed to load swrast driver
channel: stable
automaticPatches: true
width: 2560
height: 1303
isMaximized: true
channel: stable
automaticPatches: true
mods: cumcord
```

**Comment by smartfrigde** [comment]
ArmCord should be doing this automatically however you can try to forcing Wayland support with `--enable-features=UseOzonePlatform --ozone-platform=wayland`

**Comment by Apacelus** [comment]
I added that to the desktop file. Armcord now indeed runs via wayland, but there are a few issues:
- When native theme is set, armcord doesnt have a title bar at all
- Armcord doesnt use its logo and instead has no logo in the dock
- Cant pin it to the dock

**Comment by smartfrigde** [comment]
If you want to have the native titlebar back try running ArmCord with `--enable-features=UseOzonePlatform,WaylandWindowDecorations`

**Comment by Apacelus** [comment]
> If you want to have the native titlebar back try running ArmCord with `--enable-features=UseOzonePlatform,WaylandWindowDecorations`

``--enable-features=UseOzonePlatform,WaylandWindowDecorations --ozone-platform=wayland``, doesnt work.
``--enable-features=UseOzonePlatform,WaylandWindowDecorations`` starts in xwayland

**Comment by Apacelus** [comment]
@smartfrigde still having issues. Native titlbar doesnt work and the app is opened as this(and no option to pin to dock):

![image](https://user-images.githubusercontent.com/46828271/189233207-f742d630-c6d3-4e1f-8663-3f671d5cf065.png)

**Comment by smartfrigde** [comment]
**Describe the bug**
A tap is interpreted as right click instead of left click

**To Reproduce**
Steps to reproduce the behavior:
1. Force wayland by starting with: ``armcord --enable-features=UseOzonePlatform --ozone-platform=wayland``
2. Tap on anything

**Expected behavior**
A tap is a left mouse click

**Desktop (please complete the following information):**
 - OS: PopOS, 22.04
 - Method of installation: appimage
 - Version: 3.8.0
**Describe the bug**
A tap is interpreted as right click instead of left click

**To Reproduce**
Steps to reproduce the behavior:
1. Force wayland by starting with: ``armcord --enable-features=UseOzonePlatform --ozone-platform=wayland``
2. Tap on anything

**Expected behavior**
A tap is a left mouse click

**Desktop (please complete the following information):**
 - OS: PopOS, 22.04
 - Method of installation: appimage
 - Version: 3.8.0

**Additional context**
Quickly tapping the same element multiple times results in a left click.
Doesnt happen on 3.7.0 with wayland
**Additional context**
Quickly tapping the same element multiple times results in a left click.
Doesnt happen on 3.7.0 with wayland

**Comment by smartfrigde** [comment]
Can you recheck with the newest version? We updated Electron which includes some fixes for Wayland

**Comment by Apacelus** [comment]
Updated to newest version, results:
* App icon works now properly
* Running in Xwayland mode still has the typing bug
* Armcord wont start in wayland mode automatically
* Native theme now kinda works, but it uses the wrong theme(see screenshots below:)
![Untitled](https://user-images.githubusercontent.com/46828271/204388062-87af3a2b-2e15-4736-a5ad-71bc640f4608.png)
Expected theme:
![Untitled](https://user-images.githubusercontent.com/46828271/204388389-36c900bc-8ada-4099-b494-c7afffc0cccb.png)

**Comment by smartfrigde** [comment]
Are you using snap to install ArmCord? There's a chance snap doesn't properly get the theme you're using and sets it to light (electron-builder bug?).

**Comment by smartfrigde** [comment]
As seen [here](https://gitlab.com/inkscape/inkscape/-/issues/862), it can also affect appimages. Try a package for your package manager or tar.gz build

**Comment by kode54** [comment]
#304 fixes the Wayland patch to actually activate. However, I can't get it to display window sharing for anything but XWayland apps, and the Screen sharing shows black screens. AMDGPU on RX 480, Arch Linux, Gnome Wayland. Using xdg-desktop-portal-gnome.

**Comment by smartfrigde** [comment]
Screensharing on wayland is broken on newest Electron which dev branch is on

**Comment by smartfrigde** [comment]
Moving to #305 as Wayland works fine on ArmCord apart from screenshare
