### ISSUE TITLE
Make a Discord server

### ISSUE THREAD

**Issue by VenomousSteam81** [smartfrigde/armcord#172]
**Is your feature request related to a problem? Please describe.**
Every Discord client has a Discord server

**Describe the solution you'd like**
Make a Discord server

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by smartfrigde** [comment]
If you check the tray icon you can see the support discord button, which redirects to [this](https://discord.gg/TgJxfpbs). It'll be added to readme and website later
