### ISSUE TITLE
Remove "Download Apps" button

### ISSUE THREAD

**Issue by Apacelus** [smartfrigde/armcord#178]
**Is your feature request related to a problem? Please describe.**
On the left of the main screen there is a "Download Apps" button which links to the vanilla discord apps.

**Describe the solution you'd like**
Remove it

**Describe alternatives you've considered**
N/A

**Additional context**
Here is an image(the download button is the one on the bottom):
![image](https://user-images.githubusercontent.com/46828271/184673612-d1addcac-72f0-4e3d-a69f-637bd0a32fed.png)

**Comment by smartfrigde** [comment]
[Fixed](https://github.com/ArmCord/ArmCord/commit/3bc47753e6eb25bdc819d7a3ae36bbb5fb23f199)
