### ISSUE TITLE
Logout when app restarted

### ISSUE THREAD

**Issue by NotDemonix** [smartfrigde/armcord#181]
hello, when i close and open app again i need to login again
2. when will you update to new discord design
3. could you pls make some rich presence plugin? I cant connect with discord-rpc npm package..

**Comment by smartfrigde** [comment]
1. Close using the tray icon or toggle minimize to tray option in settings. Don't close from terminal using CTRL+C as then E
2. We use our own design with icons and such, unless you mean something else, we won't change it
3. RPC is not yet possible and is not planned unless the WS module gets updated to support it.
