### ISSUE TITLE
I want to change the "Zoom level".

### ISSUE THREAD

**Issue by kreis117** [smartfrigde/armcord#183]
**Is your feature request related to a problem? Please describe.**
The "Zoom level" can be changed in the settings of the official Discord client, and I usually set it to "90%" when I use it.
I would like to do the same in ArmCord, but "Zoom level" does not exist in the ArmCord settings.

**Describe the solution you'd like**
I would like to be able to change the "Zoom level" in the ArmCord settings.

**Describe alternatives you've considered**
None.

**Additional context**
![image](https://user-images.githubusercontent.com/74777259/186138925-da4d49d0-81dd-42cc-a5e8-d1952335d1e3.png)

**Comment by smartfrigde** [comment]
You should be able to do that manually using keyboard shortcuts like CTRL+ and CTRL Shift -

**Comment by kreis117** [comment]
Thank you very much.
I could not change the Zoom level in ArmCord v3.1.0, but I confirmed that it is possible in v3.0.7.

**Comment by smartfrigde** [comment]
v3.1.0 now has zoom level back in with keyboard shortcuts and if you have native titlebar enabled you can change zoom level from Alt menu
