### ISSUE TITLE
Mobile Device Support (Smartphones)

### ISSUE THREAD

**Issue by tdadvocate** [smartfrigde/armcord#186]
**Is your feature request related to a problem? Please describe.**
Mobile Device Support (ie PinePhone (base/Pro), Librem, etc)

**Describe the solution you'd like**
Not sure if this is even possible but just some variant of the application that can be run on the weird aspect ratios of mobile smartphones. So hiding the users online and the server channels after opening a channel to message in.

**Describe alternatives you've considered**
It works perfectly fine when using an external display but obviously this is suboptimal for on the go usage of the devices.

**Additional context**
I figure this likely isn't possible due to the way things are being done but figured it was worth a shot to ask regardless. Thank you very much for taking the time out of your busy schedule to look at this request!

**Comment by smartfrigde** [comment]
See dev builds in releases tab, in settings you can find mobile mode which is not perfect but definetely helps
