### ISSUE TITLE
Single instance support

### ISSUE THREAD

**Issue by rollingmoai** [smartfrigde/armcord#190]
**Is your feature request related to a problem? Please describe.**
Ability to only allow ArmCord to run a single instance. When opening the app for the second time, it should open the instance from the tray instead of opening another instance. This behavior is similar to Discord's native client.

**Describe the solution you'd like**
Only allow a single instance.

**Describe alternatives you've considered**
None.

**Additional context**

**Comment by smartfrigde** [comment]
Done

**Comment by rollingmoai** [comment]
Okay, now how do I toggle it back on? A setting would be great

**Comment by smartfrigde** [comment]
What do you mean? All you need to do is update to the latest version

**Comment by rollingmoai** [comment]
I would like to toggle between single instance and multi-instance however I want
