### ISSUE TITLE
Start ArmCord minimized

### ISSUE THREAD

**Issue by rollingmoai** [smartfrigde/armcord#191]
**Is your feature request related to a problem? Please describe.**
Ability to open ArmCord minimized to tray. This is useful when adding ArmCord to the startup.

**Describe the solution you'd like**
Add a launch parameter to open ArmCord minimized to tray.

**Describe alternatives you've considered**
Or maybe toggle in the ArmCord settings.

**Additional context**
Equivalent to "Start minimized" in the settings in the native desktop client:
![image](https://user-images.githubusercontent.com/75471378/189076366-28c917b8-eaca-4fea-b4cf-cff3c163c98c.png)

**Comment by smartfrigde** [comment]
Done in latest dev build
