### ISSUE TITLE
Left-clicking the tray should open and focus the app

### ISSUE THREAD

**Issue by rollingmoai** [smartfrigde/armcord#192]
**Is your feature request related to a problem? Please describe.**
Left-clicking the tray should open and focus the app. This is the behavior of the desktop client. Currently, left-clicking the tray does not do anything to ArmCord.

**Describe the solution you'd like**
Implement left-clicking for the tray.

**Describe alternatives you've considered**
None.

**Additional context**

**Comment by smartfrigde** [comment]
Are you on ArmCord stable?

**Comment by rollingmoai** [comment]
Yes. Is this already implemented?

**Comment by smartfrigde** [comment]
Yes, on dev builds it has been implemented

**Comment by rollingmoai** [comment]
Just tested it, works as intended. Thanks for the information!
