### ISSUE TITLE
Windows installer installs amd64 version of app on arm64 devices

### ISSUE THREAD

**Issue by halomakes** [smartfrigde/armcord#195]
Hello,
I am wanting to use this on my Surface Pro X which is a Windows arm64 device.  It appears that the installer is giving me the amd64 version of everything which is resulting in very degraded performance.
![image](https://user-images.githubusercontent.com/5904472/189371462-d5e84752-ea19-4ef3-a14e-b155472d3745.png)

Thanks for any help

**Comment by smartfrigde** [comment]
Yeah we don't have any precompiled binaries for Windows on ARM

**Comment by smartfrigde** [comment]
But we'll add them eventually and notify you

**Comment by halomakes** [comment]
Ok cool thank you for the fast response

I was able to just build and install locally in the meantime

**Comment by smartfrigde** [comment]
[Check latest dev build for experimental ARM64 build](https://github.com/ArmCord/ArmCord/releases/tag/devbuild)
