### ISSUE TITLE
All settings, data, themes, and plugins are reset, and I am logged out every time I restart

### ISSUE THREAD

**Issue by candroid-man** [smartfrigde/armcord#197]
**Describe the bug**

Whenever I restart the app, all of my configurations are wiped, and I have to sign in again.

**Desktop (please complete the following information):**
 - OS: EndeavourOS
 - Method of installation: AUR
 - Version: 3.0.7

**Comment by smartfrigde** [comment]
Are you using CTRL+C to exit?

**Comment by candroid-man** [comment]
No, just exiting it out normally.

**Comment by candroid-man** [comment]
Update: It seems that every time I open ArmCord from my KDE task bar, it creates a new instance of it and keeps the one I closed in the background rather than actually closing it. Whenever you open a new ArmCord it doesn't save your data I guess

**Comment by PhoenixOrigin** [comment]
Same, except I am using ubuntu plasma. I don't know about not closing but not saving credentials is really annoying

**Comment by smartfrigde** [comment]
> Update: It seems that every time I open ArmCord from my KDE task bar, it creates a new instance of it and keeps the one I closed in the background rather than actually closing it. Whenever you open a new ArmCord it doesn't save your data I guess

Fixed
