### ISSUE TITLE
No cumcord plugins option

### ISSUE THREAD

**Issue by Apacelus** [smartfrigde/armcord#207]
**Describe the bug**
The cumcord option disappeared from my Armcord settings  

**To Reproduce**
1. Download fresh x86_64 appimage 3.0.7 or 3.0.8
2. Delete ~/.config/ArmCord
3. Start armcord appimage, select cumcord and login to an account
4. No armcord option in settings

**Expected behavior**
I expected to see a cumcord plugins option

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux, PopOs 22.04
 - Method of installation: appimage
 - Version 3.0.8 or 3.0.7

**Additional context**
I tested v3.0.7 too, with the same results

**Comment by lexisother** [comment]
Cumcord and all supported client mods are dead.
