### ISSUE TITLE
3.0.8 Update on Arch Broken

### ISSUE THREAD

**Issue by PyroPM** [smartfrigde/armcord#216]
**Describe the bug**
Installation from .tar.gz or from AUR errors out:
```
error: missing package metadata in ArmCord-3.0.8.tar.gz
error: 'ArmCord-3.0.8.tar.gz': invalid or corrupted package
```

**To Reproduce**
Attempt to update the entire system with:
```
yay -Syyu
```
or install from the .tar.gz:
```
sudo pacman -U ArmCord-3.0.8.tar.gz
```

**Expected behavior**
Upgrade from 3.0.7 to 3.0.8

**Screenshots**
from .tar.gz:
![image](https://user-images.githubusercontent.com/48967461/193885977-b5ddd27e-180a-4688-b386-eb734d342507.png)
from AUR:
![image](https://user-images.githubusercontent.com/48967461/193886384-4fae9de8-c610-4685-b4d1-c61bca252db7.png)

**Additional context**
Arch Linux
ArmCord 3.0.7
AUR / .tar.gz

**Comment by lexisother** [comment]
JFC, this is the second time.

Can you please generate a sha256sum from this file?
https://github.com/ArmCord/ArmCord/releases/download/v3.0.8/ArmCord-3.0.8.tar.gz

**Comment by PyroPM** [comment]
5cc399b6a9c8e064112a2d6cba25cc662278c540d6cdc7ef88dc77b9fb433233  ArmCord-3.0.8.tar.gz

**Comment by lexisother** [comment]
See the PKGBUILD. It's literally the same hash. I have absolutely no idea what to do to fix this.

**Comment by PyroPM** [comment]
I figured it was the "missing package metadata" error, not necessarily an invalid package. I don't know much about this as I'm more of a novice than anything

**Comment by Ast3risk-ops** [comment]
try `yay -S armcord-bin --skip-integ --skip-checksums` or similar

**Comment by PyroPM** [comment]
I should have closed this before, it seems to work now. I did a fresh install of Arch and it worked fine.
