### ISSUE TITLE
Implement notifications

### ISSUE THREAD

**Issue by ivan123-tty** [smartfrigde/armcord#220]
**Is your feature request related to a problem? Please describe.**
It feels kinda unusual for a Discord client to not have notifications.

**Describe the solution you'd like**
Implement notifications.

**Describe alternatives you've considered**
Switching back to official Discord client.

**Additional context**
Well, in this context, I mean the desktop notifications.

**Comment by smartfrigde** [comment]
![image](https://user-images.githubusercontent.com/37928912/194712646-07bdb0ad-0563-41f0-b9ac-dc67c889f81e.png)
Make sure you have enabled desktop notifications from settings.

**Comment by ivan123-tty** [comment]
OH, i'm sorry.

**Comment by aaronliu0130** [comment]
Could this be enabled by default somehow? It feels kinda usual :).

**Comment by hashcube-dev** [comment]
> Could this be enabled by default somehow? It feels kinda usual :).

THIS 1000% like why is this DISABLED by DEFAULT??
