### ISSUE TITLE
Touch support broken under wayland

### ISSUE THREAD

**Issue by Apacelus** [smartfrigde/armcord#221]
**Describe the bug**
A tap is interpreted as right click instead of left click

**To Reproduce**
1. Force wayland by starting with: ``armcord --enable-features=UseOzonePlatform --ozone-platform=wayland``
2. Tap on anything

**Expected behavior**
A tap is a left mouse click

**Desktop (please complete the following information):**
 - OS: PopOS, 22.04
 - Method of installation: appimage
 - Version: 3.8.0

**Additional context**
Quickly tapping the same element multiple times results in a left click.
Doesnt happen on 3.7.0 with wayland

**Comment by smartfrigde** [comment]
#166 Let's move it here
