### ISSUE TITLE
Support Vencord

### ISSUE THREAD

**Issue by rollingmoai** [smartfrigde/armcord#222]
**Is your feature request related to a problem? Please describe.**
GooseMod and Cumcord is dead

**Describe the solution you'd like**
Support Vencord

**Describe alternatives you've considered**

**Additional context**

**Comment by Vendicated** [comment]
Fyi, you can already do this now:
- Download the Vencord Browser extension from GitHub releases
- Open the Armcord plugins folder and extract it there. Make sure it's in its own folder (files like manifest.json should be in ArmCord/plugins/Vencord/)
- Enable ArmCord CSP if you want to use QuickCss, petpet or FakeNitro sticker bypass

Please note that you will not get automatic Updates this way, so you have to manually reinstall the extension every so often (you will keep your settings)

![image](https://user-images.githubusercontent.com/45497981/202282895-bf72bd66-51f4-4ff3-b924-fe808edd10f0.png)

**Comment by rollingmoai** [comment]
> Please note that you will not get automatic updates this way, so you have to manually reinstall the extension every so often (you will keep your settings)

@Vendicated Yeah, this is inconvenient. It would be a solution for me if the browser extension were pushed in a separate branch so I can set up a task scheduler to regularly `git pull`.

**Comment by Vendicated** [comment]
you can actually do that in the following way:
- Extract the extension into your armcord plugins folder like mentioned above
- Clone the Vencord repo
- build the web build and create a symlink from dist/browser.js to Armcord/plugins/Vencord/dist/Vencord.js
- now just periodically pull and rebuild the repo

**Comment by MattTheTekie** [comment]
Add it and remove the older two dead client mods.

**Comment by MattTheTekie** [comment]
My friend cant install a theme because of this, the other people that arent too linux savvy and stuck on arm devices cant keep up

**Comment by smartfrigde** [comment]
Done, check latest dev builds

**Comment by MattTheTekie** [comment]
Thank you. This improves the quality of the project 10 fold!
