### ISSUE TITLE
Disable Automatic Gain Control, but actually

### ISSUE THREAD

**Issue by dfault-user** [smartfrigde/armcord#231]
**Is your feature request related to a problem? Please describe.**
It is very frustrating to use my microphone, as the client is constantly adjusting my microphone when it seems 'fit' to do so. **The official Discord client does not do this, and as such should, at least in my opinion be the intended behavior of ArmCord.**

**Describe the solution you'd like**
Automatic Gain Control in WebRTC is very trivial to disable, and in fact has a Chrome extension to easily disable it.

**Describe alternatives you've considered**
Just using web Discord and https://github.com/joeywatts/disable-autogain-control-extension to disable AGC-but-actually.

**Comment by smartfrigde** [comment]
Try the latest dev build and enable disable autogain feature in settings

**Comment by ranomier** [comment]
I toggled the autogain multiple times, it stays on.

ArchLinux 64, through flatpak from flathub.

**Comment by Switch123456789** [comment]
How come this issue is closed? I still have this problem. Can it get reopened or should I create a new issue?
`CachyOS 6.14.4` `pipewire 1.4.2` `legcord-bin 1.1.1`

**Comment by Switch123456789** [comment]
I just noticed I can't disable echo cancellation as well, I mean I can use the switches but they don't do anything.
