### ISSUE TITLE
Add support for OpenAsar

### ISSUE THREAD

**Issue by DodoLeDev** [smartfrigde/armcord#233]
**Is your feature request related to a problem? Please describe.**
The GooseMod and CumCord mods are officially no longer maintained!

**Describe the solution you'd like**
Could you please add the successor of GooseMod, [OpenAsar](https://openasar.dev/)

**Describe alternatives you've considered**
I lived without any configuration capabilities on my currently-modded Armcord app.

**Additional context**
I use Arch BTW

**Comment by smartfrigde** [comment]
OpenAsar is not a classic Discord mod which means it can't be added into ArmCord, we're slowly adding back features from OpenAsar into ArmCord.
