### ISSUE TITLE
Custom CSS support?

### ISSUE THREAD

**Issue by greed-d** [smartfrigde/armcord#236]
**Is your feature request related to a problem? Please describe.**
Since both mod have reached EOL can I put custom CSS `~/.config/ArmCord/themes` because when I tried it didn't work....

**Describe the solution you'd like**
Custom CSS support

**Describe alternatives you've considered**
Tried important CSS in a file in `../themes` folder and writing a `../themes/customFile.css` in themes folder

**Comment by AlfredOhNO** [comment]
Modified post from the Armcord support channel:

"1. Create a new folder for your theme within the themes folder

2. Create a [theme].css (substituting the text in [] for whatever you wish and removing the brackets) and manifest.json file in the new folder

3. Fill the manifest.json file
```
{
    "name": "[new_folder_name]",
    "author": "[author]",
    "theme": "[theme].css"
}
```
4. Paste your custom CSS into the [theme].css file and save it

5. Restart Armcord"

Additionally ensure that in your Armcord settings, it's set to 'Default' instead of 'Native'

**Comment by greed-d** [comment]
@AlfredOhNO 
>Additionally ensure that in your Armcord settings, it's set to 'Default' instead of 'Native'

Where can I find this setting?
and this is my file tree 
`../ArmCord/themes/themes/customCss.css`
`../ArmCord/themes/manifest/manifest.json`

And what I've written in my `manifest.json`
```json
{
  "name": "themes",
  "author": "winston#0001",
  "theme": "mocha.theme.css"
}
```

**Comment by greed-d** [comment]
Also didn't find any armcord discord server :(
Isn't there one?

**Comment by GRR3ED** [comment]
Also didn't find any armcord discord server :(
Isn't there one?

**Comment by AlfredOhNO** [comment]
There is a Discord! You can find it here - https://discord.gg/F25bc4RYDt

It's also in the Armcord tray icon's context menu, which is also where the setting I mentioned is located

I'm actually using the same theme, (Catppuccin Mocha for BetterDiscord right?) So you should be able to simply mirror my files:

`~/.config/armcord/themes/Catppuccin/manifest.json`
`~/.config/armcord/themes/Catppuccin/mocha.theme.css`

Contents of manifest.json:

```
{
    "name": "Catppuccin_Mocha",
    "author": "Winston",
    "theme": "mocha.theme.css"
}
```

**Comment by greed-d** [comment]
Thanks it works :)
