### ISSUE TITLE
Keybinds Not working

### ISSUE THREAD

**Issue by Commandcracker** [smartfrigde/armcord#243]
**Describe the bug**
The Keybinds are Not working

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Keybinds'
3. See the message saying Keybinds are not supported

**Expected behavior**
Working Keybinds

**Screenshots**
![Screenshot_20221027_192321](https://user-images.githubusercontent.com/49335821/198357371-85259048-22da-4fa3-a73c-769e4e51fe6d.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Method of installation sourceforge
 - Version 3.0.8

**Comment by smartfrigde** [comment]
#88
