### ISSUE TITLE
Feature Request: Integrate linux screenshare audio workaround

### ISSUE THREAD

**Issue by Pnut2K** [smartfrigde/armcord#247]
**Is your feature request related to a problem? Please describe.**
Screenshare audio has been a longstanding issue on linux platforms.

**Describe the solution you'd like**
I think it would be interesting if the workaround from https://github.com/edisionnano/Screenshare-with-audio-on-Discord-with-Linux could be integrated into armcord.

**Describe alternatives you've considered**
It is possible that discord may update their webrtc implementation in the relatively near future to enable pipewire hooks, but I am not holding my breath.

**Comment by lexisother** [comment]
It will be added if it doesn't turn out to be hard to mantain.

**Comment by smartfrigde** [comment]
We will just add PipeWire/Wayland eventually, hacks like these may be added in the worst case
