### ISSUE TITLE
[Bug?] Everything works fine, but no text whatsoever

### ISSUE THREAD

**Issue by cyclone018** [smartfrigde/armcord#250]
**Describe the bug**
No text. Except logos, pictures, and shows up during transitions and loads.

**To Reproduce**
1. Installed ArmCord with yay
2. launched the launcher (no text only logos and buttons)
3. signed into discord (still no text)
4. discord homepage (still no text, however during transitions text shows up then once everything loads... gone)

**Expected behavior**
Text so I can see what I select/read (then everything is perfect)

**Screenshots**
![PXL_20221115_004436271 MP](https://user-images.githubusercontent.com/71578464/201800013-d1ee7bc3-a96b-4967-b7a9-272288908795.jpg)

**Desktop (please complete the following information):**
 - OS: Arch ARM / Pine64 Pinephone (1.2) (ARM64, 6.0.2-3-danctnix)
 - Method of installation: yay (from AUR)
 - Version: Newest (3.0.8) (or whatever is newest from AUR)

**Additional context**
Nothing, everything works except text. I just wanna say thank you for your hard work to bring discord to arm in a way thats useable on linux tablets / phones. Ive been looking to go off the grid for a long time now and now might be it.
![PXL_20221115_004436271 MP](https://user-images.githubusercontent.com/71578464/201800013-d1ee7bc3-a96b-4967-b7a9-272288908795.jpg)

**Comment by smartfrigde** [comment]
1. Can you provide terminal output?
2. If you can access the tray icon somehow, or if you get your text back scroll down to place where versions are placed in settings and click on ArmCord Version. A settings window will pop out, you can enable mobile mode there for easier usage.
3. If you could, can you please join the [support Discord](https://discord.gg/Awp6YgXdS6) so we more easily debug this issue?

**Comment by smartfrigde** [comment]
This seems to be a mesa issue, please disable hw acceleration using `--disable-gpu` to get this working
