### ISSUE TITLE
On macOS, Option+Left/Right to move cursor by word, also navigates browser history

### ISSUE THREAD

**Issue by nyanpasu64** [smartfrigde/armcord#251]
**Describe the bug**
In macOS apps, Option+Left/Right is intended to move cursor by word, and never move through history. But in ArmCord, it instead jumps through history, making text editing painful.

**To Reproduce**
1. Click on the message typing field, or a message edit field.
2. Type some words separated by spaces.
3. Press Option+Left/Right.
4. Watch page navigate through browser history.

**Expected behavior**
The text cursor moves by words.

In web browsers, Command+Left/Right normally moves through history unless a text field is active, and Command+[/] always moves through history. I don't know if this shortcut is important in an Electron/web app.

**Desktop (please complete the following information):**
 - OS: macOS
 - Method of installation: .app
 - Version: 3.0.8

**Additional context**

**Comment by LewsTherinTelescope** [comment]
Not sure about OP but tried the latest version (3.2.6) and this bug seems to no longer be present, at least on my device (Intel Mac on Sonoma). Not sure what version fixed it, as it's been a little while since I first tried the app so there have been multiple releases since then.
