### ISSUE TITLE
Flatpak

### ISSUE THREAD

**Issue by ghost** [smartfrigde/armcord#265]
hi there,

is flatpak planned or considered?

**Comment by AlfredOhNO** [comment]
There's an AppImage and a tarballed binary... Do you need specifically a Flatpak for some reason?

**Comment by smartfrigde** [comment]
Duplicate of #122

**Comment by orowith2os** [comment]
> There's an AppImage and a tarballed binary... Do you need specifically a Flatpak for some reason?

I'd like to mention that a flatpak is useful for nontraditional systems, such as NixOS, Silverblue, and an AppImage and tarball can be a bit weird in terms of desktop integration.
