### ISSUE TITLE
Error installing mods on startup

### ISSUE THREAD

**Issue by Rak1ta** [smartfrigde/armcord#268]
**Describe the bug**
Error on startup after upgrading to v3.1.0 from v3.0.8

**To Reproduce**
1. Go to 'armcord'
2. Click on 'N/A'
3. Scroll down to 'N/A'

**Expected behavior**
Run without errors.

**Screenshots**
![Безымянный](https://user-images.githubusercontent.com/88277343/203580028-f4bb7892-a685-4d03-b2e3-a23bb6b45c2d.png)

**Desktop:**
 - OS: [Raspbian GNU/Linux 10 (buster), architecture: 32-bit]
 - Method of installation [deb from ArmCord/ArmCord/releases]
 - Version [3.0.8 >> 3.1.0]

**Additional context**
v3.1.0 [log.txt](https://github.com/ArmCord/ArmCord/files/10076730/log.txt)
v3.0.8 [old_log.txt](https://github.com/ArmCord/ArmCord/files/10076765/old_log.txt)

**Comment by Vendicated** [comment]
```
[Mod loader] Failed to install mods
TypeError: Only absolute URLs are supported
    at getNodeRequestOptions (/opt/ArmCord/resources/app.asar/node_modules/node-fetch/lib/index.js:1327:9)
    at /opt/ArmCord/resources/app.asar/node_modules/node-fetch/lib/index.js:1440:19
    at new Promise (<anonymous>)
    at fetch (/opt/ArmCord/resources/app.asar/node_modules/node-fetch/lib/index.js:1437:9)
    at fetch (/opt/ArmCord/resources/app.asar/node_modules/cross-fetch/dist/node-ponyfill.js:10:20)
    at updateModBundle (/opt/ArmCord/resources/app.asar/ts-out/utils.js:312:65)
```

**Comment by smartfrigde** [comment]
Either delete your `settings.json` which you can find by scrolling down in ArmCord settings and clicking "Open storage folder". Or go to settings and set everything to however you like, when there are empty choice fields, fill them out. Your config seems really old, and you still have Cumcord set as a mod. That's the main reason it's failing to update
