### ISSUE TITLE
[Windows 11] [UI] Title bar/button missing from ArmCord

### ISSUE THREAD

**Issue by BraINstinct0** [smartfrigde/armcord#269]
Issue: ArmCord Window is missing title bar and its buttons, so it cannot be opened, closed, maximized or minimized, or dragged to a different location.

_Behavior_
Expected Behavior: the title bar shows, or at least the buttons do as before.
Observed Behavior: the elements mentioned above are not shown.

Findings: the Win+(Arrow) keys does work as normal.
Possibility: the UI element for title bar is missing/not displayed.

_Environment_
Platform: Windows 11 Home 22H2, Build 22623.891
Installation method: Regardless of method. Tried on PC with previous version installed.
ArmCord version: 3.1.0
ArmCord Theme: Default
Additional Programs: StartAllBack(disabled), ExplorerPatcher. These two do affect certain Windows UI elements, but this behavior hasn't appeared on any othe programs - so I assume these are not related.

**Comment by BraINstinct0** [comment]
Edit: did not happen on previous 'stable' version.
Edit 2: Setting the ArmCord Theme in Settings, to Native, will show the Title bar - however the buttons should still show up in the Default Theme, as is stated in the option's details.

**Comment by Nikodemsky** [comment]
Same thing happens on W10, also 22H2.

**Comment by smartfrigde** [comment]
I've been investigating for 2 days and I honestly don't know what's going on. No errors, no logs, nothing. It just randomly stopped working

**Comment by smartfrigde** [comment]
Enable `Automatic patches` in settings. It'll inject a quick fix for it, while you're waiting for next release. Also due to a typo, when you load up settings the setting will always show that's it's disabled.
Source code of the fix: https://github.com/ArmCord/Patches/blob/main/3.1.0/patch.js

If you have any more issues ask me on our Discord https://discord.gg/TnhxcqynZ2

**Comment by smartfrigde** [comment]
Fixed in 3.1.1
