### ISSUE TITLE
Opening links in Linux Appimage, goes to Firefox instead of default browser

### ISSUE THREAD

**Issue by Rust1667** [smartfrigde/armcord#270]
**Describe the bug**
When clicking links, they open on Firefox, instead of my default web browser which is Brave

**To Reproduce**
Using ArmCord-3.1.0.AppImage on Linux Mint 20.3
Click any link

**Expected behavior**
Links opening with the system default web browser

**Desktop (please complete the following information):**
 - OS: Linux Mint 20.3
 - Method of installation: Appimage
 - Version 3.1.0

**Comment by smartfrigde** [comment]
Please run `xdg-open https://armcord.xyz` in your terminal and share what browser opens. There's a high chance your default browser is configured incorrectly.

**Comment by Rust1667** [comment]
Ouch you are right.
I reinstalled the distro yesterday and I forgot to change the default browser.
Sorry for the inconvenience =/
Your project is fucking great
Thanks!
