### ISSUE TITLE
Token login

### ISSUE THREAD

**Issue by UltraBlackLinux** [smartfrigde/armcord#273]
**Is your feature request related to a problem? Please describe.**
Discord won't allow me to change my email-address from one that I lost access to, so now I'm often unable to log in because of a "new location" - The only thing I have left is a token that I took from the app, which never expired for 3 years now.

**Describe the solution you'd like**
Add a button to log in via a discord token. It should be [reasonably straight-forward](https://gist.github.com/m-Phoenix852/b47fffb0fd579bc210420cedbda30b61)

**Describe alternatives you've considered**
The android app does not work on linux, if you don't use an emulator like waydroid, but that's overkill for one app

**Comment by smartfrigde** [comment]
I don't really like this idea as I don't see many useful cases for this feature and it's often associated with bad things like token stealing and stuff. Generally if somebody wants to log with token, they probably already know how to do it manually. If you want then you just paste that snippet of code into dev-tools which are accessible using CTRL+SHIFT+I.
