### ISSUE TITLE
Zooming in/out

### ISSUE THREAD

**Issue by NyakoFox** [smartfrigde/armcord#276]
**Is your feature request related to a problem? Please describe.**
The official client lets you zoom in/out with `ctrl`+`+`/`-`, like most web browsers, but ArmCord doesn't seem to allow you to do that.

**Describe the solution you'd like**
A reimplementation of this behavior.

**Describe alternatives you've considered**
I've tried adjusting chat font scaling, but the rest of the UI is still too small.

**Additional context**

**Comment by smartfrigde** [comment]
Works on my end? What platform are you on?

**Comment by Vendicated** [comment]
This used to be an issue on keyboards with dedicated + key like QWERTZ but was fixed in https://github.com/ArmCord/ArmCord/commit/842b6e8c5da3452b29653635b5ef446c84673e83

Make sure you are on the latest release 3.1.0
