### ISSUE TITLE
Save last known window position

### ISSUE THREAD

**Issue by hazre** [smartfrigde/armcord#277]
Currently Armcord doesn't keep track of the last known window postion.

Most likely needs to be a extension of this #140 

There are many ways to go about it but there is few suggestions [here](https://github.com/electron/electron/issues/526).

Muli monitor users should also be kept in mind.

**Comment by smartfrigde** [comment]
This is implemented. It just doesn't keep track of which monitor you're using

**Comment by smartfrigde** [comment]
Unless you mean the exact coordinates (x, y) of where window is placed on the system.

**Comment by hazre** [comment]
Yes I mean the exact X and Y. Not just width and height.

**Comment by smartfrigde** [comment]
Done in 3.1.1
