### ISSUE TITLE
Remove cloudflare telemetry

### ISSUE THREAD

**Issue by pbmqmwy881** [smartfrigde/armcord#278]
Every few minutes or so Armcord sends a request to a.nel.cloudflare.com which is a network error/telemetry logging. I'm pretty sure this comes from the armcord.xyz domain because first it's CDN is cloudflare and second because I have been using webcord for a year and there was no request to such domain.
Source: https://support.cloudflare.com/hc/en-us/articles/360050691831-Understanding-Network-Error-Logging

It's not a huge issue but it's better if armcord aims for privacy and the solution is pretty easy and not time consuming.

Solution 1: as stated on their website about this logging feature:
"Customers can opt out of having their end users consume the NEL headers by emailing Cloudflare support"

Solution 2: Have an option to never contact armcord.xyz and put as a disclaimer that updates wont be provided and need to be installed manually. I tried using the skip splash screen experimental setting which contacts armcord.xyz for the splash screen. But it doesn't work when vencord is insatlled for some reason (I get a white screen).
Would be nice to have a standalone armcord without external domains.

**Comment by smartfrigde** [comment]
So 3 components of ArmCord rely on armcord.xyz domain:
- Mod loader download (armcord.xyz/loader.zip)
- Update checks (armcord.xyz/latest.json)
- Automatic patches (patch.armcord.xyz)
I'm gonna be emailing cloudflare for them to disable this error logging. I'll update you when response comes in

**Comment by smartfrigde** [comment]
Done
