### ISSUE TITLE
Krisp

### ISSUE THREAD

**Issue by Degl1** [smartfrigde/armcord#279]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when my friends tell me that they can hear my parents talking or whatever
**Describe the solution you'd like**
Add some sort of noise suppression, preferrably Krisp, but main goal is that it'd work
**Describe alternatives you've considered**
Just using normal Discord
**Additional context**

**Comment by lexisother** [comment]
Krisp is proprietary technology.
