### ISSUE TITLE
Popout video chat doesn't work

### ISSUE THREAD

**Issue by kode54** [smartfrigde/armcord#281]
**Describe the bug**
The popout button from video chat doesn't work.

**To Reproduce**
1. Connect to a video chat
2. Click on the Popout button

**Expected behavior**
The video chat opens in a new window which may be moved, for instance, to another monitor.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Method of installation: AUR armcord-bin package, using paru
 - Version 3.1.0-3

**Additional context**
The error result is that clicking the Popout button causes `https://discord.com/popout` to open in the system default browser.

**Comment by Vap0r1ze** [comment]
This has also happened to me on Windows 10

**Comment by kode54** [comment]
Adding an extra to the bug report. It also does the popout link in browser thing if I attempt to open the link for the video chat debug information window.

**Comment by smartfrigde** [comment]
Last time I tried to make it work, it required proprietary Discord modules to function. But maybe they changed it so it works on web. Will check soon

**Comment by smartfrigde** [comment]
They changed it, pushing to dev soon

**Comment by smartfrigde** [comment]
Done in latest commit
