### ISSUE TITLE
No copy link option when right clicking images or video download icon

### ISSUE THREAD

**Issue by the-r3dacted** [smartfrigde/armcord#283]
**Describe the bug**
With the normal Discord client, I could right click an image and copy link. I can also do this for a video by right clicking the download icon and clicking copy link.

**To Reproduce**
1. Use ArmCord
2. Right click any image or video download icon
3. See no copy link option

**Expected behavior**
There is a copy link button that I can click and copy the link with

**Screenshots**
![ScreenShot_20221206095338](https://user-images.githubusercontent.com/77039240/205959872-9009f287-d0a1-48f8-ae39-2cf4b163b589.png)

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Method of installation: setup exe
 - Version 3.1.0

**Comment by Vendicated** [comment]
this is a discord limitation and kind of out of the scope of ArmCord. There is a Vencord plugin (WebContextMenus) that fixes this issue

**Comment by the-r3dacted** [comment]
Why is it out of the scope but able to be fixed with Vencord?

**Comment by Vendicated** [comment]
because ArmCord is not a client mod. To re-enable these entries, you need to patch Discord's code and ArmCord has no patcher or similar and tries to interface with Discord as little as possible for better future proofing and compatibility
