### ISSUE TITLE
Armcord doesn't work

### ISSUE THREAD

**Issue by ivan123-tty** [smartfrigde/armcord#290]
**Describe the bug**
It doesn't load at all.

**To Reproduce**
1. Open Armcord
2. It doesn't load

**Expected behavior**
It should load.

**Screenshots**
![image](https://user-images.githubusercontent.com/70339505/206859451-49637b35-5a1e-4fbc-98f0-f02b6b83769e.png)

**More info**
Windows 10 22H2 (x64)
Armcord installed from the installer.

**Comment by octopushugger** [comment]
This issue happens on 3.1.0 when you can't access armcord.xyz. You should really probably fix your lack of access to the site but if you can't or don't want to then you can use the dev build and it will start even if you can't access it. https://github.com/ArmCord/ArmCord/releases

**Comment by ivan123-tty** [comment]
> This issue happens on 3.1.0 when you can't access armcord.xyz. You should really probably fix your lack of access to the site but if you can't or don't want to then you can use the dev build and it will start even if you can't access it. https://github.com/ArmCord/ArmCord/releases

I can access it though.

**Comment by octopushugger** [comment]
Not sure what's causing your redirect loop then when your client tries to access it. Flush dns and reboot maybe? I don't really expect that to fix it buy hey only other thing I could think of atm.

**Comment by ivan123-tty** [comment]
> Not sure what's causing your redirect loop then when your client tries to access it. Flush dns and reboot maybe? I don't really expect that to fix it buy hey only other thing I could think of atm.

Tried that, and it didn't help. Thanks anyway though.

**Comment by octopushugger** [comment]
What about the dev version though? Did you try that

**Comment by ivan123-tty** [comment]
> What about the dev version though? Did you try that

Tried it now, and it works just fine. Thank you.

**Comment by smartfrigde** [comment]
Can reproduce and it's a bug on Cloudflare/Vercel side. I'll see what I can do

**Comment by ivan123-tty** [comment]
Now that I cleaned all of the ArmCord caches, it works now on the normal build too.

**Comment by smartfrigde** [comment]
![image](https://user-images.githubusercontent.com/37928912/206864669-920f0bf3-3adf-418a-8d65-33864ca8d9b7.png)
As seen here it's redirecting to itself, which is weird

**Comment by smartfrigde** [comment]
> Now that I cleaned all of the ArmCord caches, it works now on the normal build too.

Yup, that solves the issue. I've messed around with Cloudflare settings a bit recently to disable the error reporting and I guess clients cached those infinite redirects
