### ISSUE TITLE
Consider fully removing CSP instead of just loosening it

### ISSUE THREAD

**Issue by yellowsink** [smartfrigde/armcord#292]
**Describe the bug**
As far as I can tell, ArmCord CSP just provides a fetch() without CSP restrictions
and loosens the policy to allow CSS imports to work.

Please consider just entirely removing CSP as most mod injectors do.
It will improve compatibility with some mods / plugins.

**To Reproduce**
1. Attempt to use a plugin that imports remote code
2. CSP intercepts it

**Expected behavior**
CSP is bypassed

**Screenshots**
![image](https://user-images.githubusercontent.com/19270622/206879564-e78d1328-6326-4b8d-96e0-7e088e010515.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Method of installation: aur
 - Version: 3.1.0

**Additional context**

**Comment by Vendicated** [comment]
jsdelivr is already supposed to be allowed, try on 3.1.1

**Comment by Vendicated** [comment]
oh it's because the csp bypass is only enabled on Vencord because at the time of writing it, shelter didn't require it and I didn't think you'd use external dependencies. That would just need to be fixed

https://github.com/ArmCord/ArmCord/blob/b449fdeb942ce264f7290c12bf355b040224d6ad/src/extensions/mods.ts#L41-L45

**Comment by yellowsink** [comment]
Having one domain unblocked is not what I'm asking, what I'm saying is that there are any number of CDNs that could be used by plugins, and I don't see the point in having that restriction in the first place when mods have widely unblocked it entirely for a long time now without any real negative consequences

**Comment by Vendicated** [comment]
yeah thats fair it's just that way cause Vencord only uses those domains and I wanted to keep csp as strict as possible to maybe offer a bit better security (as i said at that time shelter didn't use any external stuffs so I didn't include it)

probably just pr full removal (maybe limit to shelter or just do blanket) and it will probably be merged

**Comment by yellowsink** [comment]
mmye
