### ISSUE TITLE
Minimizing app to tray doesn't work (missing icon)

### ISSUE THREAD

**Issue by Rak1ta** [smartfrigde/armcord#302]
**Describe the bug**

**To Reproduce**
1. Go to 'ArmCord'
2. Click on 'N/A'
3. Scroll down to 'N/A'

**Expected behavior**
Icon works correctly

**Screenshots**
See similar issue

**Desktop (please complete the following information):**
- OS: [Raspbian GNU/Linux 10 (buster), architecture: 32-bit]
- Method of installation [deb from ArmCord/ArmCord/releases]
- version [3.1.0 >> 3.1.1]

**Additional context**
I had a similar problem but with WebCord. I assume you have the same.
https://github.com/SpacingBat3/WebCord/issues/330 
https://github.com/SpacingBat3/WebCord/releases/tag/v3.10.2

**Comment by smartfrigde** [comment]
Electron bug, we're waiting for a fix

**Comment by smartfrigde** [comment]
3.1.2 reverted to older electron version that doesn't have this bug

**Comment by Rak1ta** [comment]
@smartfrigde Just now updated and noticed that my problem is back on version 3.1.5-3.1.6. On version 3.1.4 everything works.
