### ISSUE TITLE
Screenshare on Wayland

### ISSUE THREAD

**Issue by smartfrigde** [smartfrigde/armcord#305]
**Is your feature request related to a problem? Please describe.**
ArmCord is unable to screenshare native Wayland apps.
**Describe the solution you'd like**
Use Wayland's native screenshare with possible audio from PipeWire
**Describe alternatives you've considered**
[This project](https://github.com/edisionnano/Screenshare-with-audio-on-Discord-with-Linux) allows for audio screenshare however it's really hacky and bad implementation imo.
**Additional context**
None

**Comment by orowith2os** [comment]
Technically ArmCord already supports screenshare on Wayland, you just need to launch it with some specific arguments.

However, it could be done better, as the current method of screensharing follows how Discord does it, and is very hacky. It should instead leave screensharing options to the portals.

And the discord-screenaudio project might not be the best, yea, however (WebCord)[https://github.com/spacingBat3/webcord] has a MR open that ArmCord might be able to take from: https://github.com/SpacingBat3/WebCord/pull/346

**Comment by smartfrigde** [comment]
>Technically ArmCord already supports screenshare on Wayland, you just need to launch it with some specific arguments. However, it could be done better, as the current method of screensharing follows how Discord does it, and is very hacky. It should instead leave screensharing options to the portals.       

That's what this issue is all about, to make it out-of-the-box experience while following all Wayland principles 
> WebCord has a MR open that ArmCord might be able to take from: https://github.com/SpacingBat3/WebCord/pull/346

We're trying to avoid taking code from WebCord as the project code style and structure is a different which proved to make "ports" unmaintainable in the past.

**Comment by SpacingBat3** [comment]
> > Technically ArmCord already supports screenshare on Wayland, you just need to launch it with some specific arguments. However, it could be done better, as the current method of screensharing follows how Discord does it, and is very hacky. It should instead leave screensharing options to the portals.
> 
> That's what this issue is all about, to make it out-of-the-box experience while following all Wayland principles
> 
> > WebCord has a MR open that ArmCord might be able to take from: [SpacingBat3/WebCord#346](https://github.com/SpacingBat3/WebCord/pull/346)
> 
> We're trying to avoid taking code from WebCord as the project code style and structure is a different which proved to make "ports" unmaintainable in the past.

You still might take a look [at this module](https://www.npmjs.com/package/node-pipewire "NodeJS native module written in Rust and Typescript to interact with Pipewire."), the mentioned PR uses it under-the-hood so I guess you could as well. I haven't audited the code within it yet, so I can't say much about it through.

**Comment by Melechtna** [comment]
> Technically ArmCord already supports screenshare on Wayland, you just need to launch it with some specific arguments.
> 
> However, it could be done better, as the current method of screensharing follows how Discord does it, and is very hacky. It should instead leave screensharing options to the portals.
> 
> And the discord-screenaudio project might not be the best, yea, however (WebCord)[https://github.com/spacingBat3/webcord] has a MR open that ArmCord might be able to take from: [SpacingBat3/WebCord#346](https://github.com/SpacingBat3/WebCord/pull/346)

Those arguments being?

Edit: For anyone wanting to know, it's 
`--enable-features=UseOzonePlatform --ozone-platform=wayland --enable-features=WebRTCPipeWireCapturer`

**Comment by NextWork123** [comment]
For me isn't working the screen share with that flags. When i press the button of screen sharing it crash.

**Comment by Melechtna** [comment]
> For me isn't working the screen share with that flags. When i press the button of screen sharing it crash.

Discord broke it recently, I've finally given up on Discord after well over a decade of using it and moved to matrix, I'm fucking done with it. Good luck man, but I doubt it's going to get better anymore.

**Comment by dev-null-undefined** [comment]
> For me isn't working the screen share with that flags. When i press the button of screen sharing it crash.

@NextWork123 this sounds very similar to webcord issue https://github.com/SpacingBat3/WebCord/issues/328
maybe check that thread?

**Comment by Cxsmo-ai** [comment]
how do you add this on arch when using the snapstore version where is the place located to add this --enable-features=UseOzonePlatform --ozone-platform=wayland --enable-features=WebRTCPipeWireCapturer

**Comment by ghost** [comment]
> how do you add this on arch when using the snapstore version where is the place located to add this --enable-features=UseOzonePlatform --ozone-platform=wayland --enable-features=WebRTCPipeWireCapturer

Why would you be using the snap version? just curious. Aur package for both tagged release and dev builds work just fine.

**Comment by D3vil0p3r** [comment]
> --enable-features=UseOzonePlatform --ozone-platform=wayland --enable-features=WebRTCPipeWireCapturer

It happens also to me with that flag ArmCord crashes:
```
[Config manager] doneSetup: undefined
[Config manager] performanceMode: none
ArmCord has been run before. Skipping setup.
No performance modes set
[Config manager] windowStyle: default
[Config manager] armcordCSP: true
[Config manager] doneSetup: undefined
[Config manager] customIcon: undefined
Setting up CSP unstricter...
[Config manager] trayIcon: default
[Config manager] windowStyle: default
[Config manager] clientName: undefined
[Config manager] spellcheck: true
[Config manager] windowStyle: default
[319139:0611/004053.250955:ERROR:gl_display.cc(508)] EGL Driver message (Error) eglQueryDeviceStringEXT: EGL_BAD_PARAMETER error: In internal function: Additional INFO may be available

[Config manager] startMinimized: false
[Config manager] mods: vencord
[Config manager] ignoreProtocolWarning: undefined
[Config manager] noBundleUpdates: undefined
[Config manager] 0: undefined
Downloading mod bundle
[Config manager] mods: vencord
[Mod loader] Loaded ArmCord Mod Loader made by Vendicated
[Config manager] mobileMode: false
[Config manager] useLegacyCapturer: false
Starting screenshare module...
[Config manager] trayIcon: default
[Config manager] alternativePaste: false
undefined
[Config manager] inviteWebsocket: true
[arRPC] arRPC v3.1.0 ArmCord
[319139:0611/004053.304822:ERROR:gpu_init.cc(523)] Passthrough is not supported, GL is egl, ANGLE is 
[arRPC > ipc] checking /run/user/1000/discord-ipc-0
[Config manager] skipSplash: undefined
[arRPC > ipc] checked if socket is available: true 
[arRPC > ipc] listening at /run/user/1000/discord-ipc-0
[arRPC > websocket] trying port 6463
[arRPC > websocket] listening on 6463
[arRPC > process] started
[Config manager] channel: stable
[Config manager] mods: vencord
[Config manager] automaticPatches: false
[Config manager] useLegacyCapturer: false
[Config manager] startMinimized: false
[Config manager] trayIcon: default
[Window state manager] No window state file found. Falling back to default values.
[Config manager] startMinimized: false
[Config manager] channel: stable
[Config manager] mods: vencord
[Config manager] automaticPatches: false
[Config manager] useLegacyCapturer: false
[Config manager] mobileMode: false
[Config manager] trayIcon: default
[319073:0611/004059.808136:ERROR:browser_main_loop.cc(271)] Gtk: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
[Config manager] trayIcon: default
[319073:0611/004101.153782:ERROR:browser_main_loop.cc(271)] Gtk: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
[Config manager] trayIcon: default
[319073:0611/004101.303455:ERROR:browser_main_loop.cc(271)] Gtk: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
[Config manager] disableAutogain: false
[Config manager] trayIcon: default
[319073:0611/004106.082791:ERROR:browser_main_loop.cc(271)] Gtk: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
{
  frame: EventEmitter {
    executeJavaScript: [Function: executeJavaScript],
    reload: [Function: reload],
    _send: [Function: _send],
    _postMessage: [Function: _postMessage],
    frameTreeNodeId: [Getter],
    name: [Getter],
    osProcessId: [Getter],
    processId: [Getter],
    routingId: [Getter],
    url: [Getter],
    origin: [Getter],
    visibilityState: [Getter],
    top: [Getter],
    parent: [Getter],
    frames: [Getter],
    framesInSubtree: [Getter]
  },
  securityOrigin: 'https://discord.com/',
  userGesture: true,
  videoRequested: true,
  audioRequested: true
}
/usr/bin/armcord: line 14: 319073 Segmentation fault      (core dumped) "$electron" /usr/share/armcord/app.asar $USER_FLAGS "$@"
```

**Comment by D3vil0p3r** [comment]
By the way, there is an interesting GitHub repository that allows with 0 efforts to fix Discord Wayland Screenshare issue: https://github.com/itsfolf/Discord-Screenshare-Linux

It could be a good idea if ArmCord could implement it directly. Meanwhile I opened a ticket there: https://github.com/itsfolf/Discord-Screenshare-Linux/issues/12

**Comment by smartfrigde** [comment]
Screensharing on Wayland is currently broken upstream (Electron) and there's nothing we can do about it apart from using outdated Electron (Flatpak does and you can find e21 builds [on our build server](https://build.armcord.xyz). On the first look, the project you linked can't technically be merged or even adapted to work with ArmCord in any practical way cause it's modifying the original clients voice modules? Which ArmCord doesn't use (it's not a fork, we're rebuilding the client from the ground up). However I'll look into it with a much greater detail later

**Comment by D3vil0p3r** [comment]
Thank you @smartfrigde If it could be helpful, here there is the Discord server of the devs built that repo I linked above. Maybe it could be useful in case of coordination: https://discord.gg/UKzXq7xkNU

**Comment by smartfrigde** [comment]
I would say screensharing on Wayland is finally ""stable"" and uses Pipewire selector. Fixed with this commit https://github.com/ArmCord/ArmCord/commit/8e43e5abcc04560ce6b11b824691cbfd396536ca. For those wanting audio, let's move the discussion to  https://github.com/ArmCord/ArmCord/issues/435

**Comment by D3vil0p3r** [comment]
Thank you very much! I tried to test it by getting the latest commit, but when I enter in a Vocal channel in a server an I try to click the Screenshare button, nothing happens, no screen or windows to choose are shown:
![image](https://github.com/ArmCord/ArmCord/assets/83867734/7c15c2c5-2b0a-494b-8f80-affe6acddb1a)

**Comment by smartfrigde** [comment]
@D3vil0p3r click ctrl+shift+I and open console, and send any errors (red) here, alternatively join the [support Discord](https://discord.gg/6Ryc2FFD)

**Comment by D3vil0p3r** [comment]
> @D3vil0p3r click ctrl+shift+I and open console, and send any errors (red) here, alternatively join the [support Discord](https://discord.gg/6Ryc2FFD)

When I click that button, I don't get any output on console. It just continues to produce:
```
[RTCControlSocket] Sending heartbeat
[RTCControlSocket] Heartbeat ACK received
```

**Comment by smartfrigde** [comment]
Try running ArmCord from terminal, and share the output

**Comment by D3vil0p3r** [comment]
I killed armcord process and when I run it by the terminal, clicking on that screenshare button popups a small window where I can choose only the windows opened in my system, and it does not show the selection for my entire screen. By the way, when I try to select one opened window to share (i.e., my terminal), the screenshare crashes. On terminal I have this output:
```
Wayland detected, using PipeWire for video capture.
[Config manager] doneSetup: true
[Config manager] performanceMode: none
ArmCord has been run before. Skipping setup.
No performance modes set
[Config manager] windowStyle: default

(electron:64515): Gtk-WARNING **: 16:35:50.633: Theme parsing error: gtk.css:6703:68: Invalid name of pseudo-class
[Config manager] armcordCSP: true
[Config manager] doneSetup: true
[Config manager] customIcon: undefined
Setting up CSP unstricter...
[Config manager] trayIcon: default
[Config manager] skipSplash: false
[Config manager] tray: false
[Config manager] windowStyle: default
[Config manager] tray: false
[Window state manager] [object Object]
[Window state manager] [object Object]
[Config manager] mods: vencord
[Window state manager] [object Object]
[Config manager] noBundleUpdates: undefined
[Window state manager] [object Object]
Downloading mod bundle
[Config manager] mods: vencord
[Config manager] spellcheck: true
[Config manager] customJsBundle: undefined
[Mod loader] Loaded ArmCord Mod Loader made by Vendicated
[Window state manager] [object Object]
[Config manager] customCssBundle: undefined
[Config manager] ignoreProtocolWarning: undefined
[Config manager] 0: undefined
[Config manager] mobileMode: false
[Config manager] useLegacyCapturer: false
Starting screenshare module...
[Config manager] trayIcon: default
[Config manager] keybinds: undefined
[Config manager] alternativePaste: false
undefined
[Config manager] inviteWebsocket: true
[arRPC] arRPC v3.1.0 ArmCord
[arRPC > ipc] checking /run/user/1000/discord-ipc-0
[Config manager] skipSplash: false
(node:64515) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'forEach')
    at registerGlobalKeybinds (/usr/share/armcord/app.asar/ts-out/utils.js:404:14)
(Use `electron --trace-warnings ...` to show where the warning was created)
(node:64515) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
[arRPC > ipc] checked if socket is available: true 
[arRPC > ipc] listening at /run/user/1000/discord-ipc-0
[arRPC > websocket] trying port 6463
[arRPC > websocket] listening on 6463
[arRPC > process] started
[Config manager] channel: stable
[Config manager] mods: vencord
[Config manager] automaticPatches: false
[Config manager] channel: stable
[Config manager] mods: vencord
[Config manager] automaticPatches: false
[Config manager] useLegacyCapturer: false
[Config manager] mobileMode: false
[Config manager] startMinimized: false
[Config manager] tray: false
[Config manager] dynamicIcon: false
[Config manager] tray: false
[Config manager] dynamicIcon: false
[Config manager] tray: false
[Config manager] dynamicIcon: false
[Config manager] disableAutogain: false
[Config manager] tray: false
[Config manager] dynamicIcon: false
[Config manager] tray: false
[Config manager] dynamicIcon: false
[64515:0805/163616.259261:ERROR:CONSOLE(1)] "Request Network.enable failed. {"code":-32601,"message":"'Network.enable' wasn't found"}", source: devtools://devtools/bundled/core/protocol_client/protocol_client.js (1)
[64515:0805/163616.273886:ERROR:CONSOLE(1)] "Request Network.setAttachDebugStack failed. {"code":-32601,"message":"'Network.setAttachDebugStack' wasn't found"}", source: devtools://devtools/bundled/core/protocol_client/protocol_client.js (1)
[64515:0805/163616.277558:ERROR:CONSOLE(1)] "Request Emulation.setEmulatedMedia failed. {"code":-32601,"message":"'Emulation.setEmulatedMedia' wasn't found"}", source: devtools://devtools/bundled/core/protocol_client/protocol_client.js (1)
[64515:0805/163616.277621:ERROR:CONSOLE(1)] "Request Emulation.setEmulatedVisionDeficiency failed. {"code":-32601,"message":"'Emulation.setEmulatedVisionDeficiency' wasn't found"}", source: devtools://devtools/bundled/core/protocol_client/protocol_client.js (1)
[64515:0805/163616.277710:ERROR:CONSOLE(1)] "Request Network.clearAcceptedEncodingsOverride failed. {"code":-32601,"message":"'Network.clearAcceptedEncodingsOverride' wasn't found"}", source: devtools://devtools/bundled/core/protocol_client/protocol_client.js (1)
[Config manager] tray: false
[Config manager] dynamicIcon: false
[Config manager] tray: false
[Config manager] dynamicIcon: false
{
  frame: WebFrameMain {},
  securityOrigin: 'https://discord.com/',
  userGesture: true,
  videoRequested: true,
  audioRequested: true
}
[
  {
    name: '',
    id: 'window:1:0',
    thumbnail: NativeImage {
      toPNG: [Function: toPNG],
      toJPEG: [Function: toJPEG],
      toBitmap: [Function: toBitmap],
      getBitmap: [Function: getBitmap],
      getScaleFactors: [Function: getScaleFactors],
      getNativeHandle: [Function: getNativeHandle],
      toDataURL: [Function: toDataURL],
      isEmpty: [Function: isEmpty],
      getSize: [Function: getSize],
      setTemplateImage: [Function: setTemplateImage],
      isTemplateImage: [Function: isTemplateImage],
      isMacTemplateImage: [Getter/Setter],
      resize: [Function: resize],
      crop: [Function: crop],
      getAspectRatio: [Function: getAspectRatio],
      addRepresentation: [Function: addRepresentation]
    },
    display_id: '',
    appIcon: null
  },
  {
    name: 'Entire screen',
    id: 'screen:2:0',
    thumbnail: NativeImage {
      toPNG: [Function: toPNG],
      toJPEG: [Function: toJPEG],
      toBitmap: [Function: toBitmap],
      getBitmap: [Function: getBitmap],
      getScaleFactors: [Function: getScaleFactors],
      getNativeHandle: [Function: getNativeHandle],
      toDataURL: [Function: toDataURL],
      isEmpty: [Function: isEmpty],
      getSize: [Function: getSize],
      setTemplateImage: [Function: setTemplateImage],
      isTemplateImage: [Function: isTemplateImage],
      isMacTemplateImage: [Getter/Setter],
      resize: [Function: resize],
      crop: [Function: crop],
      getAspectRatio: [Function: getAspectRatio],
      addRepresentation: [Function: addRepresentation]
    },
    display_id: '',
    appIcon: null
  }
]
WebRTC Capturer detected, skipping window creation.
{ video: { id: 'window:1:0', name: '' } }
'loop->recurse > 0' failed at ../pipewire/src/pipewire/thread-loop.c:426 pw_thread_loop_wait()
'loop->recurse > 0' failed at ../pipewire/src/pipewire/thread-loop.c:426 pw_thread_loop_wait()
[64515:0805/163648.525598:ERROR:screencast_portal.cc(365)] Failed to start the screen cast session.
[64515:0805/163648.526315:ERROR:base_capturer_pipewire.cc(81)] ScreenCastPortal failed: 2
```

**Comment by smartfrigde** [comment]
Make sure you have the latest up-to-date system with latest packages. Also if you built ArmCord before make sure you did `pnpm install` to update dependencies (in this case Electron) for this build.

**Comment by D3vil0p3r** [comment]
Im using Arch Linux, what I shared above are the logs with already full updated system by `sudo pacman -Syyu` command.

**Comment by smartfrigde** [comment]
Did you update ArmCord deps when building from source? (pnpm install)

**Comment by D3vil0p3r** [comment]
> Did you update ArmCord deps when building from source? (pnpm install)

I installed it by Chaotic AUR repository by `sudo pacman -S armcord-git`.

**Comment by smartfrigde** [comment]
@D3vil0p3r that's most likely pre-built (?), if you want to test build from source directly or use the dev builds in releases tab.

**Comment by D3vil0p3r** [comment]
> @D3vil0p3r that's most likely pre-built (?), if you want to test build from source directly or use the dev builds in releases tab.

I tried to compile from source. The screenshare works, even if my screen is labeled as Unknown Display:
![image](https://github.com/ArmCord/ArmCord/assets/83867734/9ea95c5d-8818-4bd5-80bb-d7e946e76a73)

What I noted, both for this compiled from source version and from the -git package from AUR is that the Authentication by QR code is broken because it continuously asks for the Captcha and even if I enter them correctly, it always proposes a new Captcha (after 3-4 attempts it stops to ask for captcha but does not authenticate).

**Comment by smartfrigde** [comment]
> What I noted, both for this compiled from source version and from the -git package from AUR is that the Authentication by QR code is broken because it continuously asks for the Captcha and even if I enter them correctly, it always proposes a new Captcha (after 3-4 attempts it stops to ask for captcha but does not authenticate).       

That's actually a Discord bug (happens on normal client too, unfixable), not ArmCord

**Comment by D3vil0p3r** [comment]
Ok. Meanwhile I opened an issue ticket to Chaotic for rebuilding the package and making the screenshare working.

**Comment by D3vil0p3r** [comment]
@smartfrigde I noted a weird behavior on ArmCord. As you suggested, I compiled the package from source, and I get a `.AppImage` file to run. When I run it, ArmCord runs, and when I go in a Voice Channel and I click on Screenshare icon, I get the popup window that asks me what to share. In case I decide to close this popup window (instead to choose what to share), and I click again on Screenshare icon, the popup window does not appear anymore, so I think that the "Cancel" button of the popup window could be bugged.

So, the user is forced to close ArmCord and run again the `.AppImage` file.

Can you produce this bug?

**Comment by smartfrigde** [comment]
@D3vil0p3r can you send a screenshot of that popup window?

**Comment by D3vil0p3r** [comment]
> @D3vil0p3r can you send a screenshot of that popup window?

![image](https://github.com/ArmCord/ArmCord/assets/83867734/23abe91a-844e-46c0-8184-3c8c125a4954)

**Comment by D3vil0p3r** [comment]
@smartfrigde I want to report another weird behavior about the produced binary files by the build process. If I compile the project by:
```
pnpm install
npm run packageQuick
```
it produces several files and the binary ones are `dist/linux-unpacked/armcord` and `dist/linux-unpacked/resources/app.asar`. These two binary files behave in different manner.

When I run `armcord` binary file, and I click on ShareScreen button, I get correctly a single popup window:
![image](https://github.com/ArmCord/ArmCord/assets/83867734/2e29c381-3d38-4e2e-8e5e-b0c70ec1fddb)

Instead, when I use `electron dist/linux-unpacked/resources/app.asar` and I click on ShareScreen button in a voice channel, I get wrongly to popup windows instead of one: one for applications screenshare, and another one for monitor screenshare:
![image](https://github.com/ArmCord/ArmCord/assets/83867734/0e763390-d30e-4237-8b0d-1ae157067e54)

Furthermore, unlike the .AppImage file, these two binary files `armcord` and `app.asar`, when I try to start to run a screenshare, the screenshare does not start, nothing happens, and of course I still have the issue described above in https://github.com/ArmCord/ArmCord/issues/305#issuecomment-1676549302

**Comment by strawbberrys** [comment]
> 'loop->recurse > 0' failed at ../pipewire/src/pipewire/thread-loop.c:426 pw_thread_loop_wait()

This isn't ArmCord but I get the same issue on WebCord so it's probably either an electron or discord issue again? It only started happening about a month ago maybe, before then it worked fine. I also pretty much have the same setup as you, Hyprland on Artix.
