### ISSUE TITLE
Add undiscord script to mass delete DM 

### ISSUE THREAD

**Issue by fdaorra789** [smartfrigde/armcord#309]
There is a cool script that was made for discord web https://github.com/victornpb/undiscord
This tool is implemented with a trash can icon on the top right of your UI and when clicked it gives you options to choose a personal conversation or server and then gives you option to filter what you want deleted or deletes everything in this specific convo with a specific delay.

This would advance armcord's privacy tools and would be a really nice addition that could bring more people to use it.
If it were to be implemented I suggest to have it in the settings and to have a warning that this could lead to your account suspension if you do not know how to use it. Personally I never got a suspension using but I heard it could happen if the delay to the api is too low but this tool adjusts it anyways.

**Comment by Vendicated** [comment]
no

**Comment by smartfrigde** [comment]
No.
