### ISSUE TITLE
Make clicking the desktop icon maximize the already running instance

### ISSUE THREAD

**Issue by duckyondiscord** [smartfrigde/armcord#313]
**Is your feature request related to a problem? Please describe.**
I'm kinda sick of having to right click the systray icon and select "Open ArmCord" to return to my existing ArmCord instance.

**Describe the solution you'd like**
I'd like to be able to return to my existing ArmCord instance when clicking the desktop icon while it's already running.

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by smartfrigde** [comment]
Already a thing
