### ISSUE TITLE
arRPC causing massive amounts of log-spam for every status update

### ISSUE THREAD

**Issue by duckyondiscord** [smartfrigde/armcord#314]
**Describe the bug**
arRPC being enabled logs to syslogd for every single status update

**To Reproduce**
1. Enable arRPC
2. Do some activity that often updates your status.
3. Run `journalctl -xef`
4. Look at the massive amount of log-spam

**Expected behavior**
Syslogd is only used for helpful logs.

**Screenshots**
![Screenshot from 2022-12-23 09-52-50](https://user-images.githubusercontent.com/94759537/209295762-88ae1e18-f948-42b9-a4d2-ca803c820e85.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Method of installation [e.g. snap, setup exe, aur] AUR
 - Version [e.g. 3.0.7] 3.1.2

**Additional context**

**Comment by amsyarzero** [comment]
I assume that's Cider. Correct me if I'm wrong, but I think that is normal because Cider has the song timer, which means it needs to constantly update Discord's RPC on its state.

**Comment by smartfrigde** [comment]
Yes, however it's ArmCord fault for logging every update of the status. We're planning to make it optional

**Comment by duckyondiscord** [comment]
> I assume that's Cider. Correct me if I'm wrong, but I think that is normal because Cider has the song timer, which means it needs to constantly update Discord's RPC on its state.

It's PreMiD, but that's not important.
