### ISSUE TITLE
commit 3bc4775 ineffective

### ISSUE THREAD

**Issue by ghost** [smartfrigde/armcord#315]
**Describe the bug**
The download apps button is still present

**To Reproduce**
Open armcord-git. Bottom of server list has the download apps button

**Expected behavior**
No download apps section, like webcord and official discord clients.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: EndeavourOS Linux
 - Method of installation: AUR
 - Version: dev

**Comment by smartfrigde** [comment]
Outdated system electron
