### ISSUE TITLE
Disconecting from calls on windows

### ISSUE THREAD

**Issue by SzymenL0K0** [smartfrigde/armcord#318]
**Describe the bug**

**To Reproduce**
1. Have a call in some discord server
2. Minimize armcord
3. Wait circa 30 sec
4. Realese that you nobody say anything
5. Click on minimize armcord and see for 3 sec that other ppl light up but you don't hear it and get disconnected from discord

**Expected behavior**
I think i descript it on how to reproduce

**Desktop (please complete the following information):**
 - OS: Windows 10 22H2
 - Method of installation setup exe
 - Version 3.1.2.0

**Additional context**

**Comment by smartfrigde** [comment]
Can reproduce after ~20-30 minutes if being in a call

**Comment by smartfrigde** [comment]
Fixed with 3.2.1?
![obraz](https://github.com/ArmCord/ArmCord/assets/37928912/ff90751a-64b1-4475-a6e4-819dc12c158b)
