### ISSUE TITLE
Doesn't start with the proper size on tiling window managers

### ISSUE THREAD

**Issue by PaddiM8** [smartfrigde/armcord#319]
I'm using ArmCord with Sway, and when I start it, the inner window is too small. I have to manually refresh the window in order to get it to get the correct size. 

![It looks like this](https://user-images.githubusercontent.com/19822996/209665555-6862ec47-3b11-4225-8c0e-e34b36644611.png)

Would also be nice to have an option to disable the menu bar that pops up when you press `alt`, since some people use `alt` as a modifier key, but that's another issue!

**Comment by HelmicNewciv** [comment]
Makes me wish we had a plugin akin to CollapsibleUI in BetterDiscord as well, as that will automatically collapse UI elements based on window size.  Makes it so Discord's actually usable even if it's tucked into a tiny corner of your screen.

**Comment by smartfrigde** [comment]
Duplicate of https://github.com/ArmCord/ArmCord/issues/349?

**Comment by orowith2os** [comment]
Yes, it appears to be.
