### ISSUE TITLE
Error on Launch : ArmCord couldn't install internal mod loader

### ISSUE THREAD

**Issue by DanteMarshal** [smartfrigde/armcord#323]
**Describe the bug**
I'm behind a Socks5 proxy, and whether I use command line parameter (`-a --proxy-server=127.0.0.1:1080`) or use [Proxifier](https://www.proxifier.com/), I keep getting this dialog :
![image](https://user-images.githubusercontent.com/17954172/210735195-04df32dc-c5c0-4dfb-84f1-b8e6e29c161a.png)

**To Reproduce**
1. Clean install ArmCord in an environment that only has access to internet from behind a proxy
2. You'll get the dialog once the ArmCord automatically starts after install
3. You'll get the dialog every other time you start ArmCord manually

**Expected behavior**
Not get the dialog and the modloader  being installed successfully

**Desktop (please complete the following information):**
 - OS : Windows 10
 - Method of installation : Setup .exe
 - Version : 3.1.4 (Latest stable at time of writing)

**Additional context**
I live in Iran and can't access internet without a proxy, so couldn't have tested it with direct internet access.

**Comment by smartfrigde** [comment]
Can you run ArmCord from cmd and send the output?

**Comment by Vendicated** [comment]
can you view https://armcord.xyz/loader.zip in your browser?

**Comment by DanteMarshal** [comment]
@smartfrigde Here's the log for running command `$ ./ArmCord.exe -a --proxy-server=127.0.0.1:1080` while also running "Proxifier"

> ```
> [Config manager] doneSetup: undefined
> [Config manager] performanceMode: none
> ArmCord has been run before. Skipping setup.
> No performance modes set
> [Config manager] windowStyle: default
> [Config manager] armcordCSP: true
> [Config manager] doneSetup: undefined
> [Config manager] customIcon: undefined
> Setting up CSP unstricter...
> [Config manager] trayIcon: default
> [Config manager] windowStyle: default
> [Config manager] windowStyle: default
> [Config manager] startMinimized: false
> [Config manager] clientName: undefined
> [Config manager] ignoreProtocolWarning: undefined
> [Config manager] mods: vencord
> [Config manager] 0: undefined
> [Config manager] mobileMode: false
> [Config manager] trayIcon: default
> [Config manager] alternativePaste: false
> undefined
> [Config manager] inviteWebsocket: true
> [←[38;2;88;101;242marRPC←[0m] arRPC v3.0.0 [ArmCord]
> [←[38;2;88;101;242marRPC←[0m > ←[38;2;254;231;92mipc←[0m] checking \\?\pipe\discord-ipc-0
> [Config manager] skipSplash: undefined
> [←[38;2;88;101;242marRPC←[0m > ←[38;2;254;231;92mipc←[0m] checked if socket is available: true
> [←[38;2;88;101;242marRPC←[0m > ←[38;2;254;231;92mipc←[0m] listening at \\?\pipe\discord-ipc-0
> [←[38;2;88;101;242marRPC←[0m > ←[38;2;235;69;158mwebsocket←[0m] trying port 6463
> [←[38;2;88;101;242marRPC←[0m > ←[38;2;235;69;158mwebsocket←[0m] listening on 6463
> [←[38;2;88;101;242marRPC←[0m > ←[38;2;237;66;69mprocess←[0m] started
> [Config manager] channel: stable
> [Config manager] mods: vencord
> [Config manager] automaticPatches: false
> [Config manager] channel: stable
> [Mod loader] Failed to install modloader
> FetchError: request to https://www.armcord.xyz/loader.zip failed, reason: connect ETIMEDOUT 127.8.0.1:443
>     at ClientRequest.<anonymous> (C:\Users\Dante\AppData\Local\ArmCord\resources\app.asar\node_modules\node-fetch\lib\index.js:1491:11)
>     at ClientRequest.emit (node:events:527:28)
>     at TLSSocket.socketErrorListener (node:_http_client:454:9)
>     at TLSSocket.emit (node:events:527:28)
>     at emitErrorNT (node:internal/streams/destroy:157:8)
>     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
>     at process.processTicksAndRejections (node:internal/process/task_queues:83:21) {
>   type: 'system',
>   errno: 'ETIMEDOUT',
>   code: 'ETIMEDOUT'
> }
> [Config manager] startMinimized: false
> (node:11572) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
> (Use `ArmCord --trace-deprecation ...` to show where the warning was created)
> { width: 1936, height: 1066, isMaximized: true, x: -8, y: -8 }
> [Window state manager] [object Object]
> { width: 1936, height: 1066, isMaximized: true, x: -8, y: -8 }
> [Window state manager] [object Object]
> { width: 1936, height: 1066, isMaximized: true, x: -8, y: -8 }
> [Window state manager] [object Object]
> { width: 1936, height: 1066, isMaximized: true, x: -8, y: -8 }
> [Window state manager] [object Object]
> { width: 1936, height: 1066, isMaximized: true, x: -8, y: -8 }
> [Window state manager] [object Object]
> [Config manager] channel: stable
> [Config manager] mods: vencord
> [Config manager] automaticPatches: false
> [Config manager] channel: stable
> [Config manager] mobileMode: false
> ```

I think the `127.8.0.1` address is Proxifier's fault. So I tried without it and after running the command without Proxifier, it worked and now I have the mod loader installed.
But to mention every change, I'm using a relative's WiFi right now, so maybe my own WiFi was the cause ?

@Vendicated Yep I could download the file with browser.

Another friend of mine has the same issue but he wasn't using Proxifier. I'll ask him to run the command and send the log soon.

**Comment by DanteMarshal** [comment]
I checked friend's log. Here's where the error happens :
```
[Mod loader] Failed to install modloader
FetchError: request to https://armcord.xyz/loader.zip failed, reason: socket hang up
    at ClientRequest.<anonymous> (C:\Users\Dante\AppData\Local\ArmCord\resources\app.asar\node_modules\node-fetch\lib\index.js:1491:11)
    at ClientRequest.emit (node:events:527:28)
    at TLSSocket.socketOnEnd (node:_http_client:478:9)
    at TLSSocket.emit (node:events:539:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21) {
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET'
}
```

**Comment by ahmedmoselhi** [comment]
I got similar issue but with different error message:

```
FetchError: request to https://armcord.app/loader.zip failed, reason: self signed certificate in certificate chain
    at ClientRequest.<anonymous> (C:\Users\Dell\AppData\Local\ArmCord\resources\app.asar\node_modules\node-fetch\lib\index.js:1501:11)
    at ClientRequest.emit (node:events:514:28)
    at TLSSocket.socketErrorListener (node:_http_client:501:9)
    at TLSSocket.emit (node:events:514:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'SELF_SIGNED_CERT_IN_CHAIN',
  code: 'SELF_SIGNED_CERT_IN_CHAIN'
}
```

**Comment by smartfrigde** [comment]
Can you re-test on latest release?

**Comment by smartfrigde** [comment]
stale
