### ISSUE TITLE
Option to remove ping count from title bar and dynamic tray icon

### ISSUE THREAD

**Issue by the-r3dacted** [smartfrigde/armcord#325]
**Is your feature request related to a problem? Please describe.**
I never read all my pings, and even if I do it looks odd seeing a blank. I would like to just remove any indicators of ping count outside of the Discord webapp itself.

**Additional context**
Here is it looking weird with the blanks
![ScreenShot_20230105215721](https://user-images.githubusercontent.com/77039240/210927235-7849e88d-a1bd-44f3-b61e-76a24bdfd2cd.png)
![ScreenShot_20230105212421](https://user-images.githubusercontent.com/77039240/210927249-0ef83b97-dba8-4908-b755-af8d162b0a8f.png)

**Comment by smartfrigde** [comment]
You can jusf disable dynamic tray and icon in settings

**Comment by the-r3dacted** [comment]
What about the title bar, or what if I want the blue icon without the ping?
