### ISSUE TITLE
No way to turn off spell checking

### ISSUE THREAD

**Issue by ssg** [smartfrigde/armcord#330]
**Describe the bug**
Spell checking cannot be turned off causing squiggly lines all the time creating extreme annoyance. Right clicking on squiggly lines doesn't show any option to turn off spell-checking either.

**To Reproduce**
1. Type text
2. See squiggly lines
3. Anger
4. Hate
5. Suffering

**Expected behavior**
Abide OS settings for automatic spell checking.

**Desktop (please complete the following information):**
 - OS: Windows 11 ARM64
 - Method of installation: Winget
 - Version: 3.1.4

**Comment by Impeta** [comment]
While we're at it, I would also like if ArmCord could depend on OS settings (for Linux, to depend on `hunspell`) for setting our preferred languages and whatnot to check grammars and spellings over.

**Comment by smartfrigde** [comment]
You can now disable spellchecking in AC settings
