### ISSUE TITLE
Ubuntu/Kubuntu once closed, can't reopen armcord

### ISSUE THREAD

**Issue by NoelJasik** [smartfrigde/armcord#331]
**Describe the bug**
After closing armcord, i cannot open it through the armcord icon, unless i kill the armcord process

**To Reproduce**
1. Open armcord
2. Click on the x to close it
3. Try to open armcord through the icon
4. Doesn't open

**Expected behavior**
Once cliked the x symbol, i should be able to reopen it through clicking the desktop icon

**Desktop:**
 - OS: Linux, Ubuntu with plasma KDE installed as the UI
 - Method of installation: Snap, DEB, Appimage all had this problem
 - Version 3.1.3

**Comment by InverterHub** [comment]
happens to me too but im on windows 11

**Comment by NoelJasik** [comment]
@InverterHub 
There's a way to fix it, if you switch the armcord to use the native theme, instead of the default one, it does work, it's still a bug with their default theme, but atleast we can make it work for ourselfs

Here's a simple guide
1. go to settings and press:
![ksnip_20230112-140548](https://user-images.githubusercontent.com/51520102/212074468-ee56bb5e-42e6-45aa-93eb-c4892e2272ee.png)
2. change the theme (top option,it's translated to polish for me) to native
![ksnip_20230112-140648](https://user-images.githubusercontent.com/51520102/212074601-65c6cc77-b9d9-4e55-996b-ff6886c986b3.png)

**Comment by InverterHub** [comment]
thanks a bunch 🙂

**Comment by smartfrigde** [comment]
[Screencast from 2023-01-26 15-57-31.webm](https://user-images.githubusercontent.com/37928912/214869135-b270bafa-3ecb-4fb6-b348-2ad11524b68a.webm)
Unable to reproduce on ArmCord (dev build) installed through snap
