### ISSUE TITLE
OpenAsar Support

### ISSUE THREAD

**Issue by lemon07r** [smartfrigde/armcord#333]
**Is your feature request related to a problem? Please describe.**
ArmCord does not work with the OpenAsar app.asar (Windows 11 x86_x64)

**Describe the solution you'd like**
Support for OpenAsar's app.asar, or built-in version specifically made for Armcord.

**Describe alternatives you've considered**
Using Discord Stable with OpenAsar.

**Additional context**
Discord Stable with OpenAsar doesn't support mods out of the box like Vencord, etc. and it is also pretty buggy when used with newer versions of electron, like screensharing making the client crash. Would like to see ArmCord get OpenAsar support, or at least an improved app.asar based off of it that has some of the same benefits as OpenAsar.

**Comment by Vendicated** [comment]
> Discord Stable with OpenAsar doesn't support mods out of the box like Vencord

false

In any case, this makes no sense because OpenAsar is meant to replace Discord's bootstrap code but ArmCord has entirely different code so they're inherently incompatible and there would be no benefit even if OpenAsar were to be ported

**Comment by Vendicated** [comment]
Anyway, you just gave me the idea to integrate OpenAsar into the Vencord Installer, might or might not work on this soon https://github.com/Vencord/Installer/issues/11

**Comment by lemon07r** [comment]
> > Discord Stable with OpenAsar doesn't support mods out of the box like Vencord
> 
> false

Maybe I worded it badly, but I meant the Discord Stable installer doesn't install mods for out of the box support.

> Anyway, you just gave me the idea to integrate OpenAsar into the Vencord Installer, might or might not work on this soon [Vencord/Installer#11](https://github.com/Vencord/Installer/issues/11)

This would be great
