### ISSUE TITLE
Zoom level

### ISSUE THREAD

**Issue by Tidrake** [smartfrigde/armcord#334]
Could It be possible to add zoom level to the client so that the whole UI becomes smaller or bigger.

**Comment by Vendicated** [comment]
that's already a thing, just use the normal zoom keybinds

**Comment by Tidrake** [comment]
I've looked trough the keybinds and even the settings where apearance is but even there is nothing to be found it.
Normaly the keybind should be "ctrl" + "+" or "ctrl" + "-" but that doesnt even work.

![Screenshot 2023-01-21 002045](https://user-images.githubusercontent.com/57433873/213822462-1e2d8176-07e0-43c9-85e2-995c4961d8f8.png)
![Screenshot 2023-01-21 002235](https://user-images.githubusercontent.com/57433873/213822465-be23a46e-95e0-4b5e-8dac-229a53bb2e15.png)
![Screenshot 2023-01-21 002232](https://user-images.githubusercontent.com/57433873/213822464-6362d154-bcb3-4e6a-bcab-51afe27667e7.png)

**Comment by Vendicated** [comment]
it does work. What keyboard layout do you use?

**Comment by Tidrake** [comment]
QWERTY

**Comment by Tidrake** [comment]
I found the problem I was using the + of my numpad wich does not work apperently.

**Comment by Kyr4l** [comment]
doesn't work with AZERTY, there is no dedicated "-" key like QWERTY, i can only zoom in

**Comment by Anokino** [comment]
> doesn't work with AZERTY, there is no dedicated "-" key like QWERTY, i can only zoom in

For Azerty, it's : `ctrl `and `=` to zoom (next to backspace)
And : `ctrl` and `à` (the `0` in caps, close to backspace) to unzoom

**Comment by awsms** [comment]
> > doesn't work with AZERTY, there is no dedicated "-" key like QWERTY, i can only zoom in
> 
> For Azerty, it's : `ctrl `and `=` to zoom (next to backspace) And : `ctrl` and `à` (the `0` in caps, close to backspace) to unzoom

unzooming doesn't work.
