### ISSUE TITLE
GUI Issue - Wayland

### ISSUE THREAD

**Issue by NextWork123** [smartfrigde/armcord#336]
**Describe the bug**
I compiled Armcord with the patches of #327 and now I am experiencing a solid color screen and am unable to do anything. I tried to start Armcord with USE_WAYLAND=0 but it seems fine, but when I click the screen sharing button, it crashes.

**Screenshots**
![Screenshot_13](https://user-images.githubusercontent.com/46625863/213933615-81ed4825-9a14-4efd-9c8c-bab271f69b8c.png)

**Desktop (please complete the following information):**
 - OS: CachyOS (Arch Linux Distro Based)
 - Method of installation: AUR
 - Version:3.2.0

**Comment by ptr1337** [comment]
@orowith2os @Vendicated 

Please revert commit https://github.com/ArmCord/ArmCord/commit/a66f477af6f527d3aef3a153aa394ba56e20bce4

It is completly breaking armcord. I faced the same issue as above.

**Comment by ghost** [comment]
this is exclusive to #327 because of the change to appendSwitches I guess (I did some testing)
otherwise the PR seems to be ok
but since it is merged it can't be reopened I'm pretty sure, so a new one should be made with that fixed then
(@orowith2os ?)

**Comment by orowith2os** [comment]
If its the appendSwitches doing it, I suppose it could be reverted to the old way of doing it. It could also be the WindowDecorations flag messing it up, but I doubt that.

**Comment by orowith2os** [comment]
I'm also fairly busy personally, but I will try to fix this up when I can (possibly will be a few weeks, sorry)

**Comment by ghost** [comment]
> If its the appendSwitches doing it, I suppose it could be reverted to the old way of doing it. It could also be the WindowDecorations flag messing it up, but I doubt that.

hi, please take a look at https://github.com/ArmCord/ArmCord/pull/339#issuecomment-1406878837

**Comment by fxzzi** [comment]
When I run in wayland it defaults to XWayland. Adding the parameter `--ozone-platform=wayland` now makes it launch in Wayland mode, but it crashes instantly with these errors in the terminal: ![](https://cdn.upload.systems/uploads/unW1lGFW.png)

**Comment by Vendicated** [comment]
those permission denieds are super weird, that seems like an issue with ur system. Make sure you're in the audio and video groups 🤔 
```sh
sudo usermod -aG audio,video $USER
```

**Comment by fxzzi** [comment]
@Vendicated just added myself to those groups, restarted, and tried again. However the issue is still present. This happens on all electron apps when running in a native wayland mode. I think it's just nvidia shenanigans again.

**Comment by smartfrigde** [comment]
Fixed in E21 builds
