### ISSUE TITLE
Question/Feature Request: Window Transparency Support

### ISSUE THREAD

**Issue by RomanKode** [smartfrigde/armcord#337]
Does ARMcord have Window transparency support for themes that need/use transparency?

If not Will it ever have such support?

**Comment by Henry-Hiles** [comment]
It does, but it is currently very experimental. You have to enable it by manually editing the config file, and it only works in centain scenarios. However I use it on Linux with Wayland, and it works perfectly.

**Comment by RomanKode** [comment]
> It does, but it is currently very experimental. You have to enable it by manually editing the config file, and it only works in centain scenarios. However I use it on Linux with Wayland, and it works perfectly.

What or where is the config file and what parameter do I use?

**Comment by Henry-Hiles** [comment]
`~/.config/ArmCord/settings.json` iirc. Or it could be `~/.config/ArmCord/config.json`, nor sure. You need to set the window style to `transparent`.

**Comment by Henry-Hiles** [comment]
That is on Linux ofc.

**Comment by Vendicated** [comment]
%APPDATA/Armcord/storage/settings.json
~/.config/ArmCord/storage/settings.json

**Comment by RomanKode** [comment]
yup very experimental, I get transparency under wayland as a wayland app(KDE does not have any way to apply blur to transparent wayland apps), but when I launch it as an xwayland application it just shows black background.

Anyways, I'll wait for proper support in the future.

BTW under Linux it's `.config/ArmCord/storage/settings.json` and the setting to change is `"windowStyle":"transparent"`

Closing this as the feature exists just experimental/WIP, thanks for your replies!

**Comment by basicallyar** [comment]
What about macOS
