### ISSUE TITLE
.Zip version

### ISSUE THREAD

**Issue by diorite6767** [smartfrigde/armcord#340]
I wonder if you can make a .Zip version since i put most of my programs on a thumb drive,
if there's any legal issues that can happen bc of this request simply close the issue,

Thank you

**Comment by 418teapot2** [comment]
You're asking for a portable version, you could probably build a portable version from sources however i'm not sure

**Comment by diorite6767** [comment]
> You're asking for a portable version, you could probably build a portable version from sources however i'm not sure

that's what i mean but i can't build it bc i am using an old machine which is running win 7, 
and if i upgrade my preformance will degrade

**Comment by smartfrigde** [comment]
Just use the devbulds, there're in zips
