### ISSUE TITLE
linux wayland checks/patches don't do anything

### ISSUE THREAD

**Issue by ghost** [smartfrigde/armcord#342]
`appendSwitch("ozone-platform=wayland");` doesn't append any switches/flags and the app runs in XWayland, 
but the correct way `appendSwitch("ozone-platform","wayland");` just causes #336 (blank window) and also doesn't run the app in wayland however switches **do get appended**

it's possible to make armcord actually run in wayland with `--ozone-platform=wayland` argument when running from terminal

WebRTCPipeWireCapturer isn't enabled, so no pipewire capture (armcord can only share other XWayland apps and itself)
though enabling that myself just crashes the app after clicking on the screenshare button with SIGSEGV (Address boundary error) in my case

`appendArgument()` is another documented way of doing this but I couldn't get it to work

`WaylandWindowDecorations` should probably be enabled regardless without a check for GNOME

`UseOzonePlatform` isn't required since electron12

thought I should make an issue about these findings

**Comment by orowith2os** [comment]
I'm taking another shot at this over in https://github.com/ArmCord/ArmCord/pull/356, we'll see if that works. Worst case ArmCord uses a wrapper similar to what I'm using in the Flatpak.

**Comment by orowith2os** [comment]
We don't use any Wayland checks anymore, as they've been moved to ArmCord packages for the time being.
