### ISSUE TITLE
You can't hear people in a vc after a while

### ISSUE THREAD

**Issue by Linux123123** [smartfrigde/armcord#345]
**Describe the bug**
After sitting in call for a while, some users cannot be heard. It happends quite randomly and I couldn't figure, what exactly causes it.

**To Reproduce**
1. Join a vc in a server
2. Wait for the bug to appear
3. You can't hear certain people

**Expected behavior**
You can always here the person in the call.

**Desktop (please complete the following information):**
 - OS: Linux
 - Method of installation: AUR
 - Version: 3.1.4

**Additional context**
Disconnecting from the call and connecting again fixes the issue, until it happends again.

**Comment by smartfrigde** [comment]
#318
