### ISSUE TITLE
Window remains small under Wayland

### ISSUE THREAD

**Issue by ghost** [smartfrigde/armcord#349]
**Describe the bug**
Window remains small under Wayland

**To Reproduce**
1. Start ArmCord with the launch arguments `--enable-features=WaylandWindowDecorations,WebRTCPipeWireCapturer --ozone-platform-hint=auto` or `--enable-features=UseOzonePlatform,WaylandWindowDecorations,WebRTCPipeWireCapturer --ozone-platform=wayland`

**Expected behavior**
Window restores to previous size

**Screenshots**
[Screencast from 2023-02-09 00-26-58.webm](https://user-images.githubusercontent.com/101745538/217682958-3ff5c838-0620-40ff-ae65-6621afabfd92.webm)

**Desktop (please complete the following information):**
 - OS: Arch Linux, Gnome 43, Wayland
 - Method of installation: armcord-bin
 - Version: 3.1.4

**Additional context**

**Comment by aquifolly** [comment]
I can reproduce this on SnowflakeOS

**Comment by smartfrigde** [comment]
Try disabling skip splash

**Comment by aquifolly** [comment]
that doesn't solve the issue

**Comment by ghost** [comment]
Issue isn't resolved when "Skip Splash Screen (Experimental)" is either state

**Comment by aquifolly** [comment]
It also seems to happen under xwayland

**Comment by smartfrigde** [comment]
How are you closing the app? Electron has it in common that if ArmCord process is killed by either the system or CTRL+C it counts that as a crash and clears the configuration files. Let's say you use Gnome X/close button in workspaces view to close ArmCord, that actually kills it and doesn't properly close it. Please send contents of `~/.config/ArmCord/storage/window.json`

**Comment by aquifolly** [comment]
for some reason it did actually solve itself when I re-enabled the splash screen

**Comment by aquifolly** [comment]
it just took a bit

**Comment by ghost** [comment]
> How are you closing the app? Electron has it in common that if ArmCord process is killed by either the system or CTRL+C it counts that as a crash and clears the configuration files. Let's say you use Gnome X/close button in workspaces view to close ArmCord, that actually kills it and doesn't properly close it. Please send contents of `~/.config/ArmCord/storage/window.json`

I'm using the X/close button on the window. The contents of `~/.config/ArmCord/storage/window.json` do change when using X/close button.

Closing the window after loading:
`{"width":300,"height":350,"isMaximized":false,"x":0,"y":0}`

Changing the size of the window after loading, then closing the window:
`{"width":1304,"height":1060,"isMaximized":false,"x":0,"y":0}`

[output.txt](https://github.com/ArmCord/ArmCord/files/10841282/output.txt)

> It also seems to happen under xwayland

The issue isn't present for me under XWayland, although I want to use native.

> for some reason it did actually solve itself when I re-enabled the splash screen

I've tried 12 times, the issue hasn't resolved.

**Comment by FractalGeodes** [comment]
Similar issue here, Wayland Gnome on NixOS with ArmCord version 3.2.0
If ArmCord is closed properly then it retains its previous size, if not it resets to a smaller size.
Under both circumstances upon attempting to resize the window it shrinks even smaller (to around the size of the splash screen)

**Comment by smartfrigde** [comment]
Can you reproduce this on 3.2.1?

**Comment by ghost** [comment]
> Can you reproduce this on 3.2.1?

Just upgraded now, the issue is resolved! :smile: :+1:
