### ISSUE TITLE
Provide a build with "Thorium" fork & Win 7 future

### ISSUE THREAD

**Issue by legovo** [smartfrigde/armcord#350]
There is such a fork of Chromium, Thorium, there are a lot of optimizations and improvements in it. Many complain about the performance of Discord, so this will not be unnecessary.

Project website: https://thorium.rocks/
Main repo: https://github.com/Alex313031/Thorium

Thorium has builds for AVX and AVX2. The last builds to support for Win7/ SSE2 & 3, and the latest builds for M1 Mac are "special builds" and they're are separated. I would like to see these Thorium-based builds, including the one based on the latest Chromium version for Win 7, with SSE 2/3 minimum. There's also Intel Mac and Linux support somewhere. Why not have a separate Armcord build based on them? Thorium 109 will still work normally for old PCs for a while, while offering better performance.

I'm not sure how applicable this is in Armcord and generally implementable, but I'd really like to see it.

**Comment by lexisother** [comment]
We are already in the process of moving to another framework. Besides, I don't think anybody will be happy having 55 release assets for ArmCord.

**Comment by CanadaHonk** [comment]
If/when Armcord switches to Gluon for 4.0, you'd be able to use Thorium by running with --thorium (or probably an option somewhere if it's made).
