### ISSUE TITLE
3.1.7's Electron 23 drops support for Windows 7/8/8.1

### ISSUE THREAD

**Issue by matsys-regressiontest** [smartfrigde/armcord#366]
**Describe the bug**
ArmCord.exe fails on Windows 7.

The setup installs properly, but running ArmCord.exe displays the following error:
"The procedure entry point GetPackageFamilyName could not be located in the dynamic link library KERNEL32.dll."

**To Reproduce**
1. Be on Windows 7
2. Run ArmCord.exe (for 3.1.7)

**Expected behavior**
Running the program should launch ArmCord.

**Screenshots**
![error](https://user-images.githubusercontent.com/114315187/225449012-af61ddc9-b302-4a36-ab94-98dc3d0cde43.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Method of installation: Setup .exe (x86-64)
 - Version 3.1.7

**Additional context**
Version 3.1.6 - Egg yolk's ArmCord.exe functions normally.
Electron 23 drops support for Windows 8 and 8.1 as well.

**Comment by amarevite** [comment]
Are we sure this is an Electron issue? When I extract ArmCord.Setup.3.1.7.exe with 7zip, the $PLUGINSDIR folder has another .7z file in it that's labeled for arm. If I extract that folder and run ArmCord.exe, I get this error:
![image](https://user-images.githubusercontent.com/35640607/225186026-8aaa54eb-9871-4d60-ba3e-119ba0b9ac0a.png)
I get the same symptoms (doesn't install properly, only leaves an uninstall file). I'm on Windows 10 Pro 22H2.

**Comment by okibcn** [comment]
No, the problem is not dropping support for Windows 7/8/8.1... the problem is that the Windows installer is actually for Windows On Arm, and this is why you can't install it in any Windows 32 or 64 bits. The actual failure is described in issue #367

**Comment by smartfrigde** [comment]
You're right, [Electron 23](https://www.electronjs.org/blog/windows-7-to-8-1-deprecation-notice) is indeed dropping Windows 7/8.1 support. I'm gonna be working on providing builds of ArmCord on older Electron versions soon and gonna notify you when the downloads are up in this gh issue. I highly recommend you to switch to Windows 10/11 though.

**Comment by matsys-regressiontest** [comment]
> switch to Windows 10/11

I tried in 2015 and one last time in 2020. None of the attempts ever worked.

**Comment by smartfrigde** [comment]
Try Linux then, anything will be better than outdated and unsecure OS that's gonna be drastically loosing software support

**Comment by smartfrigde** [comment]
Legacy windows builds are available here: https://github.com/ArmCord/ArmCord/releases/tag/e22
