### ISSUE TITLE
ArmCord.Setup.3.1.7.exe is actually ArmCord.Setup.3.1.7.ARM64.exe

### ISSUE THREAD

**Issue by okibcn** [smartfrigde/armcord#367]
**Describe the bug**
Incorrect installer for Windows x86_64, it is actually the installer for Windows on Arm

**To Reproduce**
1. In a Windows 32 or 64 download [ArmCord.Setup.3.1.7.exe](https://github.com/ArmCord/ArmCord/releases/download/v3.1.7/ArmCord.Setup.3.1.7.exe)
2. Execute the binary
3. See error

**Expected behavior**
The software installs as 3.1.6, but with 3.1.7 we get this....

**Screenshots**
![image](https://user-images.githubusercontent.com/22417711/225198531-22af45ad-a42d-496d-990e-f2ccb0c62daf.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11 x86_64]
 - Method of installation setup exe
 - Version [e.g. 3.1.7]

**Comment by kris3713** [comment]
Can confirm, also had the same issue as well.

**Comment by justinjohn0306** [comment]
Same here

**Comment by okibcn** [comment]
Yes, [ArmCord.Setup.3.1.7.exe](https://github.com/ArmCord/ArmCord/releases/download/v3.1.7/ArmCord.Setup.3.1.7.exe) and [ArmCord.Setup.3.1.7.ARM64.exe](https://github.com/ArmCord/ArmCord/releases/download/v3.1.7/ArmCord.Setup.3.1.7.ARM64.exe) assets are actually the same file with different names. They both have the same checksum/hash.

**Comment by the-eduardo** [comment]
^ same problem '-'

**Comment by smartfrigde** [comment]
Fixed, redownload the installer

**Comment by kris3713** [comment]
@smartfrigde Thank you so much!
