### ISSUE TITLE
Can't join servers - MacOS

### ISSUE THREAD

**Issue by figurativly1984** [smartfrigde/armcord#370]
I'm using macos which i know isn't the main objective of this project but i'm experiencing a myriad of issues. Most importantly, i can't join servers. If i join through a link, the captcha takes a long time to load, frequently glitches out, and when i finally do complete it, it loops back forcing me to do the captcha again. If i look through public communities to join a server, the button at the top that says something like 'join this server' isn't clickable.

**Comment by smartfrigde** [comment]
Are you using Tor or any proxies/vpns that might cause captcha to take a long time to load?

**Comment by smartfrigde** [comment]
Stale
