### ISSUE TITLE
Unable to click any of the buttons on top of the window (macOS)

### ISSUE THREAD

**Issue by k1nomoto** [smartfrigde/armcord#373]
I'm unable to click any of these buttons, including the search bar
I'm in macOS Ventura 13.2.1, using ArmCord 3.1.7, Intel

<img width="1198" alt="image" src="https://user-images.githubusercontent.com/24980563/228370343-faaec0b6-c8f2-49e8-b127-a05e3a24cc0f.png">

EDIT: It seems to fix when I hover on that area using Inspect Element and delete the respective HTML tag — however, the Maximize/Minimize/Close buttons disappear as well

<img width="460" alt="image" src="https://user-images.githubusercontent.com/24980563/228371189-fa3c8aa7-7eaa-4b6b-932c-fee5b49b83b7.png">

**Comment by smartfrigde** [comment]
Enable native titlebar in settings for now

**Comment by smartfrigde** [comment]
Fixed
