### ISSUE TITLE
[Feature Request] Better Desktop icon

### ISSUE THREAD

**Issue by oomfiee** [smartfrigde/armcord#374]
**Is your feature request related to a problem? Please describe.**
The default armcord desktop icon is hard to locate on your desktop due to it being barely seeable (i am open to suggestions)

**Describe the solution you'd like**
Using cord icon instead of the current desktop icon

**Describe alternatives you've considered**
Replacing the current desktop icon with a cord icon with a background to make it more seeable in the desktop

**Additional context**
![armcord-but-more-easily-findable](https://user-images.githubusercontent.com/80048740/228671028-7bbba1ca-3614-40ed-920c-40cfbad39a90.png)

**Comment by orowith2os** [comment]
@gianni-rosato if you want to suggest a new icon, this would be the place ;)

Also: I'd appreciate it if a new logo is in SVG form, it helps for scaling and file size.

**Comment by gianni-rosato** [comment]
Lovely! Do u want it to look GNOME-y, or is there a particular aesthetic u have in mind? I can make mock-ups if you'd like

**Comment by orowith2os** [comment]
It can't hurt to have it in several styles. A dedicated symbolic icon would probably also be nice to have, there might be a few other variants that should be had for accessibility reasons.

**Comment by gianni-rosato** [comment]
Sure, makes sense. Is there a particular stylistic direction you'd like to take here? Maybe you could sketch something or describe it to me so I can better understand the vision?

**Comment by lexisother** [comment]
Please note this icon would not only be for Linux. No design-language-specific designs, please. The icon would display on all platforms.

**Comment by orowith2os** [comment]
Having it be cord-based might be the easiest path, since ArmCord already uses that style. 

Including a modified Discord logo might also work, if you can figure that out. I don't really have many ideas, go ham ig?

**Comment by lexisother** [comment]
No modified Discord logos. This goes against the rules and I do not want to deal with IP related issues.

**Comment by oomfiee** [comment]
> @gianni-rosato if you want to suggest a new icon, this would be the place ;)
> 
> Also: I'd appreciate it if a new logo is in SVG form, it helps for scaling and file size.

I would make it as svg if i gotten the cord svg as well (since the one in the design is using the one from the git repo)

**Comment by gianni-rosato** [comment]
For the record, SVGs do limit the use of certain features like mesh gradients, so is it okay if it isn't an SVG? If it has to be an SVG that's ok, I'll work within that limitation

**Comment by lexisother** [comment]
You can use mesh gradients in SVGs by styling them with CSS. Look into `radial-gradient`.

**Comment by gianni-rosato** [comment]
Also, FYI, "Arm" is a registered trademark of Arm Limited, so this logo change needs to happen quickly. I'm not entirely sure how it would fall under fair use

**Comment by lexisother** [comment]
> Also, FYI, "Arm" is a registered trademark of Arm Limited, so this logo change needs to happen quickly.

That's like me saying you should rename your project "aviator" because that name is trademarked by medical hardware company Abbott Laboratories.

**Comment by gianni-rosato** [comment]
fair, but you're referring to the architecture, which changes things a bit

**Comment by gianni-rosato** [comment]
![xyz.armcord.ArmCord](https://user-images.githubusercontent.com/35711760/228972582-1c6d854e-d983-49cd-a00a-29fc5540005d.svg)

Let me know how this looks. It's rather basic right now but I'm not entirely sure if that's what you're looking for or not. Would love feedback

**Comment by lexisother** [comment]
> fair, but you're referring to the architecture, which changes things a bit

No it doesn't. Did you even read Arm's terms on the topic?

**Comment by gianni-rosato** [comment]
Maybe I'm wrong, I may just be overly cautious with this stuff. You're right, you probably know better than I do

**Comment by oomfiee** [comment]
> For the record, SVGs do limit the use of certain features like mesh gradients, so is it okay if it isn't an SVG? If it has to be an SVG that's ok, I'll work within that limitation

Yeah its fine if its not a svg, i am just sorts wanting to know which format i should send here

**Comment by gianni-rosato** [comment]
I sent an SVG above, as it seems that's what's preferred. Let me know what you guys think

**Comment by orowith2os** [comment]
The one you sent is too 3D imo. I think it feels better flat, like the original proposal is. That just feels too simple though.

I prefer SVGs for desktop icons so that there aren't dozens of resolutions .png files to be used; if someone wants a specific resolution, they can rasterize it.

**Comment by gianni-rosato** [comment]
![xyz.armcord.ArmCord-flat](https://user-images.githubusercontent.com/35711760/228979061-a3a60e70-8e25-462d-b10a-85ff3764d287.svg)

More like this, do you think? And I agree about SVGs, it is why GNOME wants to use them system-wide in the future.

**Comment by orowith2os** [comment]
The placement of the connectors looks off, the armcord style where it's sort of like a D might be best. But having just the cord sounds too minimalistic.

**Comment by gianni-rosato** [comment]
Could you give me a more specific illustration of what you're looking for? Maybe sketch it on a piece of paper & send a pic here?

**Comment by orowith2os** [comment]
I'll try tossing something together, I really shouldn't be so picky while I have a million other things to do >>

**Comment by gianni-rosato** [comment]
Lol, not a problem. I'd like to help you execute your vision as precisely as possible, I'm sorry if I'm asking for too many specifics

**Comment by oomfiee** [comment]
![armcord-svg-flat](https://user-images.githubusercontent.com/80048740/228984858-d2f43737-5d0d-4cc8-9083-df61b87c0fa3.svg) 
here is the svg

**Comment by oomfiee** [comment]
(note the cord icon itself is not a svg so it may not look crisp as the background)

**Comment by TheEvilSkeleton** [comment]
FWIW we could get inspired by Discord's icon, like [WebCord](https://github.com/flathub/io.github.spacingbat3.webcord):

![WebCord logo](https://user-images.githubusercontent.com/50847364/229244271-a319c835-7889-4ef0-8f70-34fed138ff1d.png)

Edit: This could conflict with https://github.com/ArmCord/ArmCord/issues/374#issuecomment-1490939730

**Comment by gianni-rosato** [comment]
I think @lexisother doesn't want to do that for fear of copyright infringement

**Comment by TheEvilSkeleton** [comment]
Yeah that's totally fair

**Comment by ryzendew** [comment]
> ![armcord-svg-flat](https://user-images.githubusercontent.com/80048740/228984858-d2f43737-5d0d-4cc8-9083-df61b87c0fa3.svg) here is the svg

i hope to god this is used i have seen all the rest they are ugly

**Comment by RyzenDew** [comment]
![228984858-d2f43737-5d0d-4cc8-9083-df61b87c0fa3](https://user-images.githubusercontent.com/84041391/230224538-5aeccea2-9c25-48ef-9076-58b942276792.svg)
Sorta kicked it up a small notched

**Comment by RyzenDew** [comment]
![228984858-d2f43737-5d0d-4cc8-9083-df61b87c0fa3](https://user-images.githubusercontent.com/84041391/230224734-3c6fec66-cd50-4f01-8969-49847dd00087.svg)
took his and added some flair

**Comment by RyzenDew** [comment]
https://drive.google.com/file/d/1BAghTTLyvDtdPmPeNextGnihS-FQyX4r/view?usp=sharing since github hates me i uploaded my icon based off of oomfiee

**Comment by lexisother** [comment]
Doesn't at all fit with our design.

**Comment by orowith2os** [comment]
I like the ones suggested by @RyzenDew, it doesn't feel as plain as the other logos. The alt version seems like it would work well on any desktop with its outline.

I'd love to see some monochrome or grayscale ones too, for use in high contrast situations.

Maybe a different blue/purple, more like the original proposed logo has.

**Comment by ryzendew** [comment]
> Doesn't at all fit with our design.

what style? not really seeing any

**Comment by RyzenDew** [comment]
![alt4](https://user-images.githubusercontent.com/84041391/230391567-a35253a2-bb40-4d03-bd35-29ae0227389f.png)
![alt5](https://user-images.githubusercontent.com/84041391/230391699-1e9fe579-9441-4baa-9c13-5bf3f2bfac4a.png)
alt 4 and 5

**Comment by RyzenDew** [comment]
![alt4](https://user-images.githubusercontent.com/84041391/230392061-4aafc319-27ec-41d6-bee4-6f8aebfd7e4d.png)
![alt5](https://user-images.githubusercontent.com/84041391/230392064-8c302a8a-29ec-413f-b44b-49bb7b3dcca4.png)
ALT 4 and 5 

More boring less flashy and to be fair the cord in the image get's in the way

**Comment by smartfrigde** [comment]
All of our existing branding assets are held in this [repo](https://github.com/ArmCord/BrandingStuff). I would much rather see alterations of these to fit style with every OS (e.g Windows 10/11 having Metro-like tiles (11 would just have that rounded), macOS with their [3D-ish icons.](https://preview.redd.it/eohd83fjrhy51.jpg?auto=webp&s=151faa667f4d94fe9fcb4fb6f659cfe489169593)). Linux is a weird case due to how people are often using icon packs and stuff like that, I think the macOS style icons flattened would be a good fit. I also want to mention that I would like colors to remain the same as the assets we've created before for consistency, only exception I can imagine is the macOS icon having more vibrant colors to fit with the rest of the system.

**Comment by lexisother** [comment]
Whatever has been posted so far deviates wildly from what we already had, and from what we had in mind from a redone icon. If I were the sole person to make a choice, I would adopt OPs icon in a heartbeat and be done with it.

**Comment by ryzendew** [comment]
change is scary for you guys got it goodluck

**Comment by lexisother** [comment]
Not inherently scary, we are just not willing to overthrow our entire branding just to fit other people's needs.

**Comment by smartfrigde** [comment]
> change is scary for you guys got it goodluck

We only like change when it's for the good. All of the propositions except for the OPs were objectively bad.

**Comment by ryzendew** [comment]
![image](https://user-images.githubusercontent.com/84041391/230471503-8973433a-d3a9-4ab9-a8bc-5703831be2f8.png)
oh it's good change you just can't see it i did a poll in 2 servers and this won by 2k votes

**Comment by lexisother** [comment]
We aren't going with your icon. There's no need to further solidify your point. Stop, or I will put an interaction block in place.

**Comment by oomfiee** [comment]
i remade the cord icon with stuff from the branding repo (thanks smartfrigde for linking it here)

![armcord_flat_remake](https://user-images.githubusercontent.com/80048740/230478719-c092deff-e309-470f-bfd1-a6e3e85a8280.svg)

**Comment by lexisother** [comment]
Feel free to increase the size of the cord icon a tad! While it is centered, it has a lot of padding around it, I wonder how it looks with a little less of that padding.

**Comment by oomfiee** [comment]
> Feel free to increase the size of the cord icon a tad! While it is centered, it has a lot of padding around it, I wonder how it looks with a little less of that padding.

this is what i was able to do without making any visual issues

![armcord_flat10](https://user-images.githubusercontent.com/80048740/230487958-5ba5fa5e-f01f-4d58-93c5-35c6beb24db4.svg)

**Comment by lexisother** [comment]
Owh, I did not mean make the icon thinner. I moreso meant making it fill up a bit more of the blurple space.

**Comment by oomfiee** [comment]
> Owh, I did not mean make the icon thinner. I moreso meant making it fill up a bit more of the blurple space.

ah alrightly doin it

**Comment by oomfiee** [comment]
done
![armcord_flat12](https://user-images.githubusercontent.com/80048740/230495022-ea79afe5-4be1-4ec6-8c90-deea9020501b.svg)

**Comment by lexisother** [comment]
Looks perfect! Thoughts? @smartfrigde

**Comment by SkyePrism** [comment]
I love this 😍

**Comment by smartfrigde** [comment]
It's perfect, gonna switch dev builds to it soon

**Comment by oomfiee** [comment]
Thanks <3
