### ISSUE TITLE
no red notification indicator on the taskbar

### ISSUE THREAD

**Issue by UNSTOP4BLE** [smartfrigde/armcord#375]
its kinda annoying that i cant check whether someone pinged me by looking at the icon on the taskbar, i ended up dragging the little discord icon out of "show hidden icons" to see the pings but its very tiny and its annoying to check at the other side of the screen when im used to just looking at the discord icon on the taskbar.

**Comment by smartfrigde** [comment]
OS, what desktop environment?

**Comment by UNSTOP4BLE** [comment]
windows 10

**Comment by baraa272** [comment]
windows 11 also have this problem here 
using vencord and already enabled dynamic icon

**Comment by smartfrigde** [comment]
MS store sadly doesn't support changing icons dynamically afaik
You either need to use standard setup.exe builds or just use the tray icon ping indicator

**Comment by baraa272** [comment]
But I'm using the standard exe build ????

**Comment by baraa272** [comment]
I'm not using Ms store build 
I used the exe build from here
