### ISSUE TITLE
No Pings?

### ISSUE THREAD

**Issue by okuue** [smartfrigde/armcord#376]
I don't recieve any pings after a while with armcord in the background. My friends dm's show up after I tab over, but I do not recieve any sort of notification.
Sometimes I tab over and the client sort of reloads itself
How do i make it so that i recieve all notifications?

Im using performance mode with vencord and minimize to tray enabled with stable build, is there anything else in settings i could use to enable it
Idk how to reproduce, it's like this from the start when i picked up armcord 

**Desktop (please complete the following information):**
 - OS: Windows
 - Method of installation setup.exe
 - Version 3.1.7

**Comment by smartfrigde** [comment]
![Screenshot_2023-04-19-09-44-16-43_572064f74bd5f9fa804b05334aa4f912.jpg](https://user-images.githubusercontent.com/37928912/233004726-b388e6ba-1af6-47c4-a593-e97c14400f14.jpg)
