### ISSUE TITLE
Screenshare can't stream games

### ISSUE THREAD

**Issue by Yomiia** [smartfrigde/armcord#377]
**Describe the bug**
When I want to share a game window, it doesn't show up on "ArmCord Screenshare".

**To Reproduce**
1. Go to 'a vocal channel'
2. Click on 'Share your Screen'
3. Scroll down to 'Nothing'

**Expected behavior**
There should be all game windows (screen 1).

**Screenshots**
![image](https://user-images.githubusercontent.com/80260767/231885732-b82a6515-5b1f-4dc9-97a8-50696e54fe2a.png)
![image](https://user-images.githubusercontent.com/80260767/231886293-59b48702-af0b-49ab-9b65-8e951ee14301.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10 Enterprise LTSC]
 - Method of installation [setup.exe]
 - Version [3.1.7]

**Additional context**
It does show up when the application is in windowed mode (screen 2). However, the stream stops being shared as soon as I turn the game back to fullscreen.

**Comment by Yomiia** [comment]
Another related issue: the windows that show up in ArmCord Screenshare (like my web browser in the screens) don't have sound when I stream.
Expected behaviour: There is sound on the windows I stream.

EDIT: There is no sound either using Legacy Capturer in the options.

**Comment by smartfrigde** [comment]
Some games don't allow for overlays which means ArmCord can't screenshare them. It's unfixable, as for screensharing audio, it's unsupported
