### ISSUE TITLE
add the ability to install third party plugins on vencord for armcord

### ISSUE THREAD

**Issue by Cxsmo-ai** [smartfrigde/armcord#379]
add the ability to install third party plugins on vencord for armcord

**Comment by lexisother** [comment]
Impossible and out of our control.

**Comment by ardishko** [comment]
> @lexisother may I ask why? Also, is there _any_ sort of workaround for this?

Vencord is compiled WITH the plugins themselves, how you would have to go about it would be to let users add their own plugins and recompile which is something you can already do. But It's a bit messy.

Long story short, plugins are not modular like on BD, they are part of the clientmod itself so you can't just add or remove one.
