### ISSUE TITLE
Funky behaviour using ipv6 fetching vencord after electron update 22->23

### ISSUE THREAD

**Issue by philipwilk** [smartfrigde/armcord#380]
**Describe the bug**
On v3.1.7, vencord is inaccessible if ipv6 is used by the system. It is accessible if ipv4 is used.
This means that the oops error box appears (and vencord is not fetched)
![image](https://user-images.githubusercontent.com/50517631/233124510-2932b358-2972-4538-af13-a899e36d88f4.png)
This works on v3.1.6.

**To Reproduce**
1. Open armcord 
2. Oops page when it tries to download vencord, ENETUNREACH in the console

**Expected behavior**
1. No oops and vencord is fetched over ipv6

**Screenshots**
### Using ipv6
![image](https://user-images.githubusercontent.com/50517631/233126976-c9a1d42d-e7c1-4467-817f-014f151955aa.png)
### Using ipv4 only
![image](https://user-images.githubusercontent.com/50517631/233127125-a3b271fe-3faa-4c41-82e0-2e2d2256b955.png)

### Using ipv6
![image](https://user-images.githubusercontent.com/50517631/233126168-3879f1c3-f02e-4e7a-92d8-847b17b0fbd3.png)
### Using ipv4 only
![image](https://user-images.githubusercontent.com/50517631/233126468-c54bd981-6d55-48f9-8b9e-ea0ccc120efe.png)

**Desktop (please complete the following information):**
 - OS: Linux NixOS 22.11 
 - nixpkgs (using .deb package from releases page)
 - Version 3.1.7

**Comment by jadewilk** [comment]
I think this is funky behaviour because github doesnt properly support ipv6, not sure how it was even working on 3.1.6 but whatever.
