### ISSUE TITLE
Full Android support via LSPosed (Xposed) rooted

### ISSUE THREAD

**Issue by joeyoropesa-dev** [smartfrigde/armcord#381]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
N/A

**Describe alternatives you've considered**
N/A

**Additional context**

The integration can be done via rooted device and LSPosed that can have itself the libraries and binaries to emulate everything that is needed to be emulated to be able to run plugins support from this desktop client, convert it and to hook it into Discord app or into your modded Discord client app you can also make if you want.

Of course, it needs more work to integrate this but just imagine how we can just via some type of bridge to connect different platforms and integrate plugins from one platform to another without writting the plugins from scratch. Every element, UI and etc... via this method to be hosted as the feature in Discord and that feature to be sent to Discord client app via LSposed that runs some type of bridge between this modded client and android app.

More details or maybe better ideas for integrating this project to Android mobile devices in some github repository that will be only for android devices so that the desktop client app source code will not be changed nor broken.

**Comment by Vendicated** [comment]
what?

**Comment by smartfrigde** [comment]
Just no.
