### ISSUE TITLE
[Suggestion] IPA file for IOS files

### ISSUE THREAD

**Issue by SnarkyDeveloper** [smartfrigde/armcord#383]
Is it possible to compile this as an ipa file so that it is downloadable from a jailbreak or @altstoreio so that I can run Armcord on Apple. The reason this will work even on the newest devices because apple is only Arm64.

**Comment by the-r3dacted** [comment]
Go ahead port Electron to iOS

**Comment by lexisother** [comment]
![](https://cdn.discordapp.com/emojis/737998524880519179.webp?size=44&quality=lossless)
