### ISSUE TITLE
"Crashes" on Wayland/Nvidia - armcord killed by SIGTRAP

### ISSUE THREAD

**Issue by Milliw** [smartfrigde/armcord#384]
**Describe the bug**
Trying to run ArmCord using native Wayland by `flatpak run xyz.armcord.ArmCord --enable-features=UseOzonePlatform --ozone-platform=wayland` results in getting several crash reports on Gnome GUI.

**Expected behavior**
Application start without errors.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/11760209/234599279-8850952f-e132-4d60-88a9-66fde18f576d.png)

**Desktop (please complete the following information):**
 - OS: Nobara 37, Gnome 43.2, Wayland
 - Flatpak/AppImage
 - Version 3.1.7
 - Nvidia RTX 2060, driver 525.105.17, 2 displays (DP, HDMI)

**Additional context**
Came to this project "by accident" as I was/am looking for/trying a working Discord app.
So far all apps that run Electron (as far as I can tell) have similar/same issues. Only _discord-screenaudio_ works without these but introduces others so I want to give ArmCord a try.

Starting ArmCord without arguments it runs without errors but in Xwayland mode but then has same mentioned issues.
I want to say, that I did find above mentioned arguments only here in the issues list and do not 100% know what they are doing.

I use `xwininfo` to check for Wayland/Xwayland.

**Comment by orowith2os** [comment]
Run it with the USE_WAYLAND variable set to 1 instead, as I have everything properly set up in there. Also try to reproduce on somewhat vanilla Fedora, as this could be a Nobara-specific issue.

Also also, downgrade your NVIDIA drivers (and afterwards run `flatpak update`) to see if it's an issue with the newest drivers.

**Comment by Milliw** [comment]
> Run it with the USE_WAYLAND variable set to 1 instead

I'm sorry, but I found no information anywhere on the repo how to do this.
That's why I used the mentioned flags(?).

I don't know, but the log output is confusing, too. Example:
```
...
Using Wayland; enabling PipeWire for video capture
USE_WAYLAND not set, running through Xwayland
Using NVIDIA on Wayland, applying workaround
...
```
So what?? ^^

Besides the errors shown, and the minimal window size bug I had ArmCord running yesterday quite fine so far.

> Also try to reproduce on somewhat vanilla Fedora

I will, if additionally needed later on

> downgrade your NVIDIA drivers

Will not do this. Don't want to break things as I do not have the needed skills and this isn't the latest available driver, too. Nobara delivered the latest and because of some breaking bug reverted it few days later.

**Comment by orowith2os** [comment]
> Will not do this. Don't want to break things as I do not have the needed skills and this isn't the latest available driver, too. Nobara delivered the latest and because of some breaking bug reverted it few days later.

Then I can't determine if it's a bug related to NVIDIA or an ArmCord issue. 

> I'm sorry, but I found no information anywhere on the repo how to do this.

`flatpak run --env=USE_WAYLAND=1 xyz.armcord.ArmCord`

**Comment by Milliw** [comment]
Thanks @orowith2os 
So I have to tell flatpak to run the app in Wayland mode, if I understand right. Didn't know that.
Running ArmCord this way looks promising and it did not show my reported behaviour which is a plus! 
But then there's another thing: Clicking the screen sharing button has no effect. To be expected?

**Comment by orowith2os** [comment]
> But then there's another thing: Clicking the screen sharing button has no effect. To be expected?

For now, yes. You have to enable the legacy screencapturer manually. I will enable it myself for everyone at some point, but it's a minor tweak until then. I will also improve how to run it on Wayland, so you can just enable access to the Wayland socket.
