### ISSUE TITLE
[FEATURE] Introduce login by QR CODE for MFA users

### ISSUE THREAD

**Issue by D3vil0p3r** [smartfrigde/armcord#385]
**Is your feature request related to a problem? Please describe.**
I keep Multifactor Authentication enabled on Discord and I just discovered ArmCord and I would like to use it. Official Discord app provides the possibility to login by QR Code for users enabling MFA. ArmCord sadly does not have this feature and each time I must login on it, I need always to generate backup codes and it is a lot uncomfortable.

**Describe the solution you'd like**
I would like that, on Login window, ArmCord provides the possibility to login by QR Code (by using your mobile phone) as occurs on the official Discord app for MFA users.

**Comment by smartfrigde** [comment]
You can login by QR code in ArmCord normally. Make sure your ArmCord window is big enough for the QR code to display (the default wifnow size 800x600 isn't big enough for it)

**Comment by D3vil0p3r** [comment]
Oh yes. You're right. Since the default size of login window does not show immediately the QR Code due to its default size, is it possible to change the default size of the login window in order that also the other users don't fall in my same doubt?

**Comment by smartfrigde** [comment]
Fixed in latest commit
