### ISSUE TITLE
Hardware accel?

### ISSUE THREAD

**Issue by techflashYT** [smartfrigde/armcord#386]
**Is your feature request related to a problem? Please describe.**
Armcord doesn't seem to offer the option for hardware acceleration.

**Describe the solution you'd like**
Offer hardware acceleration.

**Describe alternatives you've considered**
I've considered going back to the stock Discord App, where hardware acceleration is availible.

**Additional context**
![No hw accel option](https://user-images.githubusercontent.com/72118300/236074837-5d3df70a-6e1f-46ae-8440-cbfaa78030d5.png)
No Hardware Acceleration option ^^^
I am using Arch Linux, installed Armcord via the `armcord-git` AUR package.
My specs are:
Intel Core i3-12100f
16GB DDR4 3200 MHz
AMD Radeon RX 560 4GB

**Comment by lexisother** [comment]
It is already enabled by default. The fact that you're not noticing a difference means hardware acceleration is not relevant for you.

**Comment by techflashYT** [comment]
I do actually notice a difference, not in overal responsiveness, but in resource usage.
Somehow it uses less resources on the render process (when idle), but when it's actually rendering stuff, it uses a ton of CPU.

**Comment by smartfrigde** [comment]
Electron hardware accel is much different frrom official Discord client one. Make sure Chromium has hardware accel on your machine, if it doesn't then there's nothing we can do
