### ISSUE TITLE
can't get armcord out of "full screen mode" 

### ISSUE THREAD

**Issue by Plaguewave7** [smartfrigde/armcord#387]
hey, I am having trouble with armcord being in fullscreen mode, taking up my whole screen, how do I get it back into windowed mode,  I tried f11, it did absolutely nothing at all to change the fact it's permanantly stuck in full screen mode. 

![image](https://user-images.githubusercontent.com/71691723/236375932-749e6665-b215-4ea1-9ea4-042d5fd1b16a.png)
how do I fix this?

Note: this is a full screen screencap and not a screen snipped screencap and as you can see, it's in full screen when I need it in windowed mode and nothing makes it get out of fullscreen mode

**Comment by smartfrigde** [comment]
Temp fix
CTRL+SHIFT+I click console and paste `document.exitFullscreen();`
This should fix it

**Comment by smartfrigde** [comment]
Fixed
