### ISSUE TITLE
Flatpak tray icon

### ISSUE THREAD

**Issue by NSurtsev** [smartfrigde/armcord#388]
On my Fedora Silverblue 38 with extension "AppIndicator and KStatusNotifierItem Support" enabled the Flatpak ArmCord has system tray icon not like default "fork", but like "3 dots".
Fix it, please!

**Comment by orowith2os** [comment]
This is a known issue, it's likely an issue with the extension itself, not ArmCord. There are already issues on the appropriate repositories.
