### ISSUE TITLE
Armcord client detected as browser client

### ISSUE THREAD

**Issue by Davilarek** [smartfrigde/armcord#390]
**Describe the bug**
Armcord client is detected as browser client by discord, which is somewhat excepted

**To Reproduce**
1. Install Vencord mod
2. Enable PlatformIndicator plugin
3. See your own profile on the user list
4. See "web" platform

**Expected behavior**
Display status as "desktop"
*note: it's not Vencord's fault that it displays web status icon*

**Screenshots**
![obraz](https://user-images.githubusercontent.com/62715937/236638179-3b12de02-30e2-49ff-a32a-d429a069c093.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Method of installation: setup
 - Version: 3.1.7

**Additional context**
None

**Comment by Vendicated** [comment]
Because ArmCord loads web Discord. This is expected behaviour

**Comment by Davilarek** [comment]
that's what I said in the "Describe the bug", maybe Armcord could use some methods to trick Discord into thinking it's actually a desktop client

**Comment by smartfrigde** [comment]
Unnecessary hacky stuff

**Comment by Vendicated** [comment]
why do u care whether u show as desktop or web, it does not matter

**Comment by Davilarek** [comment]
it's suspicious to be on web discord and have rich presence
