### ISSUE TITLE
Screenshare not working in Armcord Flatpak

### ISSUE THREAD

**Issue by amsyarzero** [smartfrigde/armcord#391]
**Describe the bug**
Pressing the *Share Your Screen* button while in a voice call does not do anything. Other buttons (e.g. Mute/Unmute, Camera) function properly.

**To Reproduce**
1. Join a voice call
2. Press the *Share Your Screen* button

**Expected behavior**
A window pop-up showing what screen to share should pop-up.

**Screenshots**
![amogus](https://user-images.githubusercontent.com/81513934/236737302-861c0a05-0fbe-42d8-97f6-01b5c43b30cc.gif)

**Desktop (please complete the following information):**
 - OS: Linux (Vanilla OS 22.10)
 - Method of installation: Flatpak
 - Version: 3.1.7

**Additional context**
In other installations of Armcord (e.g. AUR), screenshare works.

**Comment by okseb** [comment]
Same here

```
OS: Linux (Fedora 37)
Method of installation: Flatpak
Version: 3.1.7
```

**Comment by orowith2os** [comment]
Enable the legacy screencapturer in the ArmCord settings.
