### ISSUE TITLE
arRPC does not work on Armcord Flatpak

### ISSUE THREAD

**Issue by amsyarzero** [smartfrigde/armcord#392]
**Describe the bug**
arRPC that is included in does not read any applications that use Discord Rich Presence (e.g. Cider, Visual Studio with Discord extension).

**To Reproduce**
1. Open any application that sends out Rich Presence to Armcord.
2. Discord status doesn't show Rich Presence.

**Expected behavior**
Rich Presence should show whenever an application sends out Rich Presence to Armcord.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux (Vanilla OS 22.10)
 - Method of installation: Flatpak
 - Version: 3.1.7

**Additional context**
- arRPC in Armcord installed using other methods (e.g. AUR) works.
- I found [this article](https://github.com/flathub/com.discordapp.Discord/wiki/Rich-Precense-(discord-rpc)). Not sure if this is applicable to this exact situation, but it's good for reference.

**Comment by Vendicated** [comment]
do the thing you sent and it will work. nothing from armcord's side to fix, this is just how flatpak sandboxing works

**Comment by orowith2os** [comment]
Just change app/com.discordapp.Discord to .flatpak/xyz.armcord.ArmCord/xdg-run. I have this detailed in https://github.com/flathub/xyz.armcord.ArmCord

**Comment by amsyarzero** [comment]
Thanks @Vendicated and @orowith2os , I should've looked further into it. Right now, Cider (AppImage) works, but the extension I used with Visual Studio Code (Flatpak) doesn't, even after adding the filesystem permissions.

However, that is a minor issue for me, so I'll just close this issue. Thanks again!
