### ISSUE TITLE
GUI refresh when open new interface

### ISSUE THREAD

**Issue by defduydinh** [smartfrigde/armcord#396]
![Bug](https://github.com/ArmCord/ArmCord/assets/75720903/3b9482ed-3c8a-4e88-bf6a-06c3767638d8)

Whenever I open new tab ie. GIF, emotes, settings, or another chat servers, it refreshes to blank screen then reappear to be normally.
This happens constantly when switching or opening anything.

using window 10, downloaded Armcord via Window store.
using nvidia gpu + intel cpu.

**Comment by smartfrigde** [comment]
Can you please retry on 3.2.0?

**Comment by defduydinh** [comment]
Hi, this is version 3.2.0. I also tried window store version, same issue.

**Comment by smartfrigde** [comment]
I'm unable to reproduce this, can you please install ArmCord using standard exe build and then run it from Powershell like this:
`.\ArmCord.exe --disable-gpu`

**Comment by defduydinh** [comment]
`--disable-gpu` option seems to fixed it, I don't see the issue anymore. Is there a setting in armcord to toggle disable-gpu? As I can't find that within the setting menu.

**Comment by defduydinh** [comment]
![image](https://github.com/ArmCord/ArmCord/assets/75720903/063e3715-e867-41cd-8c2d-a8f84e37cda3)
Workaround by adding `--disable-gpu` to launch property.
Closing as this solved issue.
