### ISSUE TITLE
Fresh install joining servers opens a new window that is signed out

### ISSUE THREAD

**Issue by SomeAspy** [smartfrigde/armcord#401]
**Describe the bug**
When freshly installed, armcord will open a new window whenever you click an invite link. this includes the "Support Discord Server" invite in the taskbar. This opened window will be signed out of discord. However signing into it seems to retain it for future windows, however, this odd behavior still seems unintentional

**To Reproduce**
1. Fresh install Armcord (unknown if this persists across uninstalls)
2. Use a discord invite link (I tested with the "Join support server" button in taskbar)
3. This opens a new window to accept the invite, which is signed out regardless of login status in the actual application

**Expected behavior**
Windows opened by Armcord should be signed in.

**Screenshots**
![image](https://github.com/ArmCord/ArmCord/assets/33640860/2c845bd9-bbd6-427d-a178-5c32fd1bf535)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Method of installation: AUR (armcord-git)
 - Version: 3.20.0

**Additional context**
```
Canary 200918 (ced0a14)
Vencord 458c7ed (Web)
Electron 22.3.3
Chromium 108
Linux 64-Bit
ArmCord Version: 3.2.0
```

**Comment by smartfrigde** [comment]
Can't be fixed afaik, unless we move the tokens around the windows, which I really don't want to do. Might add an alert if somebody is logged out in the invite window, tell them it's intended behaviour? Open for suggestions
