### ISSUE TITLE
Include commit hash in system info area

### ISSUE THREAD

**Issue by SomeAspy** [smartfrigde/armcord#402]
**Is your feature request related to a problem? Please describe.**

There's not really a problem here but I think it will possibly make debugging easier in some cases.

**Describe the solution you'd like**
![image](https://github.com/ArmCord/ArmCord/assets/33640860/175ef942-052e-45c1-9f12-f0da3fc83887)
(Edited in with dev tools)
![image](https://github.com/ArmCord/ArmCord/assets/33640860/9a286297-5c61-4330-90e6-837e961da74a)

**Comment by lexisother** [comment]
There is no point. We work using tagged releases, and you can simply look at the tag on the repo if you wish to view the source code at that point in time.
