### ISSUE TITLE
Armcord grabs media key controls from other windows

### ISSUE THREAD

**Issue by SomeAspy** [smartfrigde/armcord#403]
**Describe the bug**
Armcord will grab media focus from other apps, causing media keys to control content in discord instead of other apps.
This is a bug because this is not standard behavior from the Discord app.

**To Reproduce**
1.	Start video in discord
2. 	Attempt to use media keys for external app

**Expected behavior**
Armcord should not grab media focus.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Method of installation: AUR (armcord-git)
 - Version: 3.20

**Additional context**
```
Canary 200969 (c641505)
Vencord 3e3d05f (Web)
Electron 22.3.3
Chromium 108
Linux 64-Bit
ArmCord Version: 3.2.0
```

**Comment by Vendicated** [comment]
fixing this is trivial

https://github.com/Vencord/Desktop/blob/aae4223294783e0bd9edb2f7ede3615bac89c231/src/main/index.ts#L38-L43

**Comment by smartfrigde** [comment]
fixed
