### ISSUE TITLE
Flatpak tray icons do not show on Plasma

### ISSUE THREAD

**Issue by Liassica** [smartfrigde/armcord#406]
**Describe the bug**
When using the Flatpak version of ArmCord, tray icons do not show on Plasma. The label (armcord) still shows in the system tray, but there is no icon. This happens no matter which icon is chosen in the ArmCord settings.

**To Reproduce**
1. Install Flatpak version of ArmCord
2. Choose any tray icon in the ArmCord settings
3. View system tray

**Expected behavior**
The selected tray icon shows.

**Screenshots**
![Screenshot_2023-06-09T14-29-40CDT](https://github.com/ArmCord/ArmCord/assets/115422798/476bc6e5-1029-4229-9b76-51c603d3a793)
![Screenshot_2023-06-09T14-29-59CDT](https://github.com/ArmCord/ArmCord/assets/115422798/a46aa505-7343-44d1-9cd7-77946e315412)

**Desktop (please complete the following information):**
 - OS: Fedora Linux 38 KDE Plasma
 - Method of installation: Flatpak from Flathub
 - Version: 3.2.0

**Additional context**
I have not edited the files in any way.

**Comment by smartfrigde** [comment]
Electron issue, unfixable

**Comment by Jackaed** [comment]
Eh? The flatpak versions of other discord clients work properly in this regard, e.g. webcord, regular discord client.

Is it specific to electron 24?

I'm experiencing the same issue on Hyprland.

**Comment by smartfrigde** [comment]
Flatpak uses Electron 21 for screenshare to work on Wayland, however that got fixed in latest Electron versions so it's just matter of waiting
