### ISSUE TITLE
Flatpak version freezes after extended use

### ISSUE THREAD

**Issue by Liassica** [smartfrigde/armcord#408]
**Describe the bug**
ArmCord freezes after extended use. This occurs on any performance mode.

**To Reproduce**
1. Download Flatpak version of ArmCord
2. Use for a while (a few hours usually) on any performance mode
3. Interface freezes, rendering ArmCord unusable until restart

**Expected behavior**
ArmCord remains responsive even after extended use.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Fedora Linux 38 KDE
 - Method of installation: Flatpak from Flathub
 - Version: 3.2.0

**Additional context**
RAM usage nears 3 GB when it freezes, could be that causing the crash.

**Comment by smartfrigde** [comment]
Discord has a memory leak that ArmCord can't fix
