### ISSUE TITLE
crash when clicking "registered games" in settings (vencord)

### ISSUE THREAD

**Issue by dxcvvxd** [smartfrigde/armcord#411]
**Describe the bug**
noticed that rpc isnt working with anything (it did on arch, im using artix + openrc right now)
tried to click anything related to it and noticed that armcord crashes when i press "registered games"

**To Reproduce**
1. open armcord
2. go to settings
3. press "registered games"
4. profit?
**Expected behavior**
i expect it to 1. have rpc working 2. not crash (obviously)

**Screenshots**
-

**Desktop (please complete the following information):**
 - OS: Artix Linux (w/openrc)
 - Method of installation: aur
 - Version: 3.2.0-2 (bin version)

**Additional context**
it worked for me on arch linux, dont know what happened there, i'll try to use the -git version from aur.
edit: git version is the same, no rpc and still crashes.

**Comment by Vendicated** [comment]
Simply don't click on that tab? It's desktop only.

**Comment by dxcvvxd** [comment]
well, what i also have mentioned is the rpc itself not working (spotify, games etc).
and it did work before on arch linux (like a week ago), i dont know what it can be caused by.

> It's desktop only.

yes? yes it is, i know that, and i am on dekstop.

**Comment by smartfrigde** [comment]
arRPC works on my end, please make sure the game you're playing is [detactable](https://disgamebrowser.openasar.dev/). As for registered games tab crashing, it's a Discord web thing and it is not supported by arRPC.
![obraz](https://github.com/ArmCord/ArmCord/assets/37928912/108b36dc-6a1f-4b8f-be3f-4dfe67166710)

**Comment by dxcvvxd** [comment]
> make sure the game you're playing is [detactable](https://disgamebrowser.openasar.dev/)

so from what i understand, spotify isnt detectable? (and again, it worked before)

**Comment by smartfrigde** [comment]
You need to link it to your Discord profile and allow activity status in Discord settings.
