### ISSUE TITLE
"Keybind maker" isn't showing up

### ISSUE THREAD

**Issue by NickHam13** [smartfrigde/armcord#412]
**Describe the bug**
Maybe I'm just being a moron, but I can't for the life of me find the keybind maker that this text describes. It's not in the settings sidebar, and I can't find any other sidebar it could be referring to
![image](https://github.com/ArmCord/ArmCord/assets/49380508/a877c8b7-4909-4166-a460-8fc7462edb6d)

**Desktop (please complete the following information):**
 - OS: Windows
 - Method of installation: Setup .exe
 - Version: 3.2.1

**Comment by smartfrigde** [comment]
It's an unfinished feature, and you're on the dev builds so
