### ISSUE TITLE
ArmCord is blank on startup

### ISSUE THREAD

**Issue by sanctifyy** [smartfrigde/armcord#414]
**Describe the bug**
After updating to 3.2.0 ArmCord refuses to load discord 

**To Reproduce**
Run ArmCord
**Expected behavior**
Discord to appear on the home page

**Screenshots**
![image](https://github.com/ArmCord/ArmCord/assets/87588511/69426fbc-a6a4-46de-a6b8-93293732ca2b)

**Desktop (please complete the following information):**
 - OS: Windows
 - Method of installation: Setup exe
 - Version: 3.2.0

**Additional context**
I have tried uninstalling from control panel and re-installing with no success

**Comment by smartfrigde** [comment]
Can you go into settings by right clicking the tray icon? From there, scroll all the way to the bottom until you see a copy debug info button. Click that and send the output here

**Comment by sanctifyy** [comment]
**OS:** win32 Windows 10 Home
**Architecture:** x64
**ArmCord version:** 3.2.0
**Electron version:** 24.3.0
`{
    "windowStyle": "default",
    "armcordCSP": true,
    "minimizeToTray": true,
    "startMinimized": false,
    "automaticPatches": false,
    "inviteWebsocket": true,
    "mobileMode": false,
    "alternativePaste": false,
    "disableAutogain": false,
    "dynamicIcon": false,
    "channel": "stable",
    "mods": "vencord",
    "performanceMode": "performance",
    "trayIcon": "default",
    "skipSplash": false,
    "useLegacyCapturer": false,
    "doneSetup": true
}`

**Comment by smartfrigde** [comment]
Delete `ArmCord` folder in `%AppData%`
