### ISSUE TITLE
aur arch builds do not work on wayland

### ISSUE THREAD

**Issue by Redhawk18** [smartfrigde/armcord#416]
**Describe the bug**
screensharing from native aur builds does not work **only** on wayland

**To Reproduce**
1. install either aur build
2. be on wayland
3. open armcord and enable legacy screenshare
4. join a voice channel and click the share button

**Expected behavior**
As on x11 it would just work

**Screenshots**

**Desktop (please complete the following information):**
Linux Malos 6.3.9-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 21 Jun 2023 20:46:20 +0000 x86_64 GNU/Linux
kde

**Additional context**

**Comment by orowith2os** [comment]
This is an upstream Electron issue, not ArmCord.

See https://github.com/electron/electron/pull/38833
