### ISSUE TITLE
Unable to change the Screen Share Quality and FPS

### ISSUE THREAD

**Issue by Kai-2601** [smartfrigde/armcord#418]
**Describe the bug**
There is no option to change the Screen Share Quality and FPS both before and after the stream has started.

**To Reproduce**
1. Be in a call
2. Click on the Screen Share button
3. Pick a screen/program to share
4. Unable to pick/change stream quality and fps

**Expected behavior**
To have an option to be able to change the Quality and FPS of the Screen Share stream both before starting the stream and during the stream

**Screenshots**
![stream quality](https://github.com/ArmCord/ArmCord/assets/69786669/12d5afe8-77e8-41bc-9c15-c1a3945fd4c1)
![streams](https://github.com/ArmCord/ArmCord/assets/69786669/3f7484cb-9e80-4e2d-8e40-f584a282965e)

**Desktop (please complete the following information):**
 - OS: Windows 10 22H2
 - Method of installation: Installer
 - Version: 3.2.0

**Additional context**
Screen Share Stream quality is stuck at 720p and 30 FPS
Enabling and disabling the 'FakeNitro' plugin for Nitro Quality makes no difference.

**Comment by orowith2os** [comment]
This is an issue with the web version of Discord, which ArmCord uses. @smartfrigde was looking at implementing this feature, but it'll be a while.

**Comment by smartfrigde** [comment]
~~There's testing going in our support server, join it and check announcements channel~~
2024 Update: that patch broke with Discord updates seeking new alternatives

**Comment by tim-gromeyer** [comment]
Where can I find the discord/support server?

**Comment by smartfrigde** [comment]
@tim-gromeyer https://discord.gg/TnhxcqynZ2

**Comment by smartfrigde** [comment]
https://github.com/ArmCord/ArmCord/issues/511#issuecomment-2171816864
