### ISSUE TITLE
Option to Remove the Tilebar

### ISSUE THREAD

**Issue by VehementHam** [smartfrigde/armcord#420]
Is there an option to remove the tile bar? It looks ugly
![image](https://github.com/ArmCord/ArmCord/assets/75701545/dd76e999-f35b-44e9-8d04-5ebbd0449797)

If there is no option please add one.

**Comment by orowith2os** [comment]
Change the ArmCord theme to "Native" in ArmCord settings, and that should fix it up. Additionally, if that doesn't work, make sure your compositor supports the KDE SSD protocol on Wayland; GTK doesn't yet support xdg-decoration.

**Comment by VehementHam** [comment]
Can I change disable the bar in a custom theme?
