### ISSUE TITLE
Failed to connect to session bus | Won't launch

### ISSUE THREAD

**Issue by ghost** [smartfrigde/armcord#421]
**Describe the bug**
Launching the program fails with the following output:
```
[james@voidD620 ~]$ flatpak run xyz.armcord.ArmCord
Passing the following arguments to Electron: --enable-gpu-rasterization --enable-zero-copy --enable-gpu-compositing --enable-native-gpu-memory-buffers --enable-oop-rasterization --disable-gpu-blocklist --enable-features=UseSkiaRenderer
[3 zypak-helper] Failed to connect to session bus: [org.freedesktop.DBus.Error.NotSupported] Using X11 for dbus-daemon autolaunch was disabled at compile time, set your DBUS_SESSION_BUS_ADDRESS instead
[3 zypak-helper] src/helper/main.cc:40(DetermineZygoteStrategy): Assertion failed: bus
/app/bin/startarmcord: line 39:     3 Aborted                 zypak-wrapper /app/bin/armcord/armcord "${FLAGS[@]}" "$@"
[james@voidD620 ~]$
```

**Steps to reproduce the behavior:**
1. Install ArmCord for the first time via flatpak.
2. Attempt to launch the program.
3. Observe the lack of a window and the error output above. 

**Expected behavior**
ArmCord should launch and function in a new window, presumably without the above error output. 

**Computer:**
 - OS: Void Linux, kernel 6.3.12_1, i3wm/X11
 - Method of installation: flatpak from flathub
 - Version: 3.2.0

**Comment by orowith2os** [comment]
Make sure you've got D-Bus installed and enabled, and have xdg-desktop-portal (and xdg-desktop-portal-gtk, if you don't use a DE) installed.

I'm not sure on what needs to be done to enable the session bus for Void.

**Comment by ghost** [comment]
> Make sure you've got D-Bus installed and enabled, and have xdg-desktop-portal (and xdg-desktop-portal-gtk, if you don't use a DE) installed.
> 
> I'm not sure on what needs to be done to enable the session bus for Void.

Dbus is installed and enabled. I can see it's running in htop, as well as elogind. xdg-desktop-portal and xdg-desktop-portal-gtk are also installed.

**Comment by orowith2os** [comment]
Is the D-Bus *user* session running? That and the system ones are two different things.

**Comment by ghost** [comment]
> Is the D-Bus _user_ session running? That and the system ones are two different things.

I think so. In htop, I can see dbus-daemon processes and related xdg processes running as my user. There's also other dbus processes running as root, and another as a "dbus" user.

**Comment by orowith2os** [comment]
it looks like the D-Bus environment variable was never set, so it can't be found? Run `echo $DBUS_SESSION_BUS_ADDRESS` and if that outputs nothing (it should be along the lines of `unix:path=/run/user/1000/bus`) then you need to set up more things on your system.

**Comment by ghost** [comment]
> it looks like the D-Bus environment variable was never set, so it can't be found? Run `echo $DBUS_SESSION_BUS_ADDRESS` and if that outputs nothing (it should be along the lines of `unix:path=/run/user/1000/bus`) then you need to set up more things on your system.

My dbus envars were configured incorrectly. Void does things really weird, like putting them in "/tmp/dbus-tXD5siHW1p,guid=47caaf1fdbe2a82f69a3a48764b49cb6" and changing the id every login, instead of /run/user/1000/bus. 

I added "export $(dbus-launch)" to my .xprofile and now ArmCord launches correctly and I was able to login.
