### ISSUE TITLE
add discord useragent

### ISSUE THREAD

**Issue by eltrevii** [smartfrigde/armcord#422]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
add the useragent from the desktop discord app

**Describe alternatives you've considered**
n/a

**Additional context**
get the useragent from the official desktop app of every os (windows, linux & macos) with `navigator.userAgent` and add it to the armcord app

**Comment by smartfrigde** [comment]
It won't magically fix alll of the problems and make all the features work. I don't see a reason why

**Comment by eltrevii** [comment]
oof💀
at least i tried

**Comment by Vendicated** [comment]
in fact this makes discord think your client is capable of things it can't actually do. Namely, it breaks voice chat entirely

It also makes your requests look more suspicious

**Comment by eltrevii** [comment]
bruh
