### ISSUE TITLE
Can we get arRPC updated to the latest?

### ISSUE THREAD

**Issue by Andrew-J-Larson** [smartfrigde/armcord#423]
This merge fixes an issue with an app that I use with ArmCord: https://github.com/OpenAsar/arrpc/pull/39

**Comment by smartfrigde** [comment]
already updated, just wait for the stable release

**Comment by Andrew-J-Larson** [comment]
> already updated, just wait for the stable release

Thanks, is there a milestone tracker I can monitor?
