### ISSUE TITLE
Crashes when trying to share screen on Wayland with Plasma

### ISSUE THREAD

**Issue by tabbi-dev** [smartfrigde/armcord#424]
**Describe the bug**
Armcord completely crashes whenever the Share Screen button is clicked whilst in a VC.

**To Reproduce**
1. In Plasma with Wayland, join any vc channel in a server
2. Click on 'Share Your Screen'
3. Crash

**Desktop (please complete the following information):**
 - OS: Arch Linux,
 - Kernel: Linux
 - DE: KDE Plasma
 - Method of installation: AUR
 - Version: 3.2.0

**Comment by orowith2os** [comment]
Electron issue, should be fixed next release.
