### ISSUE TITLE
[Bug] Version doesn't match

### ISSUE THREAD

**Issue by Andrew-J-Larson** [smartfrigde/armcord#425]
If you install the latest version of ArmCord on a Raspberry Pi, launch it and sign in, then right click on the status icon... It shows version 3.1.3 instead of the newest version 3.2.1

**Comment by orowith2os** [comment]
*Where* are you installing it from? Who's creating the binaries? Is it a third party? Are they coming directly from ArmCord?

**Comment by Andrew-J-Larson** [comment]
> *Where* are you installing it from? Who's creating the binaries? Is it a third party? Are they coming directly from ArmCord?

https://github.com/Botspot/pi-apps

**Comment by Andrew-J-Larson** [comment]
And I did already check that it targets the latest version.

**Comment by smartfrigde** [comment]
I don't think this is an ArmCord issue? Report this to Pi-Apps
