### ISSUE TITLE
theme-modifiable titlebar

### ISSUE THREAD

**Issue by eltrevii** [smartfrigde/armcord#426]
**Is your feature request related to a problem? Please describe.**
im not sure if this is a bug or a feature request, but some discord themes modify the titlebar, and the armcord titlebar stays the same

**Describe the solution you'd like**
change the titlebar in some way so it can be modified (size, background, etc)

**Describe alternatives you've considered**
n/a

**Additional context**
it breaks some themes like [softx](https://raw.githubusercontent.com/DiscordStyles/SoftX/deploy/SoftX.theme.css)
![image](https://github.com/ArmCord/ArmCord/assets/59333567/cefd475e-7c9b-45c6-8abf-558cccb50158)
![ArmCord_4ZoTXBc2ml](https://github.com/ArmCord/ArmCord/assets/59333567/4f1db56c-b351-414b-944b-57cd27c9a87a)

**Comment by lexisother** [comment]
This is already possible. You will have to modify the theme to use ArmCord's classes.

**Comment by smartfrigde** [comment]
Ask your theme dev to support it or write some CSS yourself
