### ISSUE TITLE
Dead Link for FreeBSD

### ISSUE THREAD

**Issue by therealnv6** [smartfrigde/armcord#427]
**Describe the bug**
The `FreeBSD` installation instruction link seems to be dead.

**To Reproduce**
1. Go to https://github.com/ArmCord/ArmCord/blob/dev/README.md#freebsd
2. Click on "[these instructions](https://gist.github.com/aaxyria/4d29c982ac85d5d26f98a51040b5de37)"
3. Voila, page not found. https://gist.github.com/aaxyria/4d29c982ac85d5d26f98a51040b5de37

**Expected behavior**
For the page to work

**Screenshots**
![image](https://github.com/ArmCord/ArmCord/assets/96917554/eb4e517c-eba9-4fa4-885b-ceee884554ac)

**Desktop (please complete the following information):**
 - OS: FreeBSD
 - Method of installation N/A
 - Version N/A

**Comment by therealnv6** [comment]
Seems like the user changed their username, here is the new link! https://gist.github.com/txxlchains/4d29c982ac85d5d26f98a51040b5de37. Will open a PR.

**Comment by ERROR-404-NULL-NOT-FOUND** [comment]
This link is dead again, after a search, it seems that the new link is https://gist.github.com/axyolotl/4d29c982ac85d5d26f98a51040b5de37
