### ISSUE TITLE
can't disable minimize to tray 

### ISSUE THREAD

**Issue by pagusupu** [smartfrigde/armcord#430]
**Describe the bug**
trying to disable minimize to tray just toggles the tray setting instead, with minimize to tray staying on

**Expected behavior**
minimize to tray turns off 

**Desktop**
 - OS: Win 10
 - Method of installation: Scoop
 - Version: 3.2.1

**Comment by smartfrigde** [comment]
fixed with https://github.com/ArmCord/ArmCord/commit/e6ad02b598aa3fa0d234bb444a963580bc5cf04e
