### ISSUE TITLE
Changing install location 

### ISSUE THREAD

**Issue by snoopchallenge** [smartfrigde/armcord#432]
**Is your feature request related to a problem? Please describe.**
I don't want ArmCord to be installed to my C: drive

**Describe the solution you'd like**
Have an option to change the install location of ArmCord

**Describe alternatives you've considered**
Have the installer not delete the folder of ArmCord and instead delete the files inside so people can make a symbolic link to another drive

**Additional context**
I am using windows 11

**Comment by smartfrigde** [comment]
![obraz](https://github.com/ArmCord/ArmCord/assets/37928912/73c06105-1512-493e-a842-8c3552a46e70)
Solved in https://github.com/ArmCord/ArmCord/commit/5145410f06a89790a4141f2ce9beb6aed34b5025
