### ISSUE TITLE
Global keybind maker empty menu / error

### ISSUE THREAD

**Issue by EtsefZale** [smartfrigde/armcord#433]
**The Bug:**
Whenever I try to create a keybind via the ArmCordGlobal Keybinds Maker, it shows nothing in the menu.

**To Reproduce:**
1. Go to the "Global keybinds" menu
2. Empty with no text or buttons. If I go into Inspect Element, there's _maybe_ 4 lines of code. Shown in the image below.
    2a. Sometimes it may show an error, as shown in the third screenshot.

**Expected behavior:**
There _should_ be a menu here, right?

**Screenshots:**
![image](https://github.com/ArmCord/ArmCord/assets/65312670/850ed093-c5d5-4200-a96e-5a287035af77)
![image](https://github.com/ArmCord/ArmCord/assets/65312670/90e78ea5-2b07-4268-b93c-b09d5f77962f)
![image](https://github.com/ArmCord/ArmCord/assets/65312670/8120f5c3-7908-48e2-a689-93da6012ee6d)

**Desktop:**
Windows 11
Discord Stable 216385
ArmCord Version 3.3.0
Installed via Microsoft Store

**Comment by EtsefZale** [comment]
Sorry, had my mouse cursor covering some text in the third screenshot. Here it is with it out of the way:
![image](https://github.com/ArmCord/ArmCord/assets/65312670/842f8e0a-bf00-44f1-bf10-062fb57be5f3)

**Comment by smartfrigde** [comment]
> There should be a menu here, right?     

Not really, I built the MS Store version off a dev build by mistake with this menu left out because I forgot about it (that's also why version is 3.3.0, when it's actually 3.2.1). It's currently not even functional on actual dev builds so just ignore this for now, I'll upload a proper stable build to MS Store soon

**Comment by EtsefZale** [comment]
oh yeah i gotcha. so just switch to github version I assume?

**Comment by smartfrigde** [comment]
If that button just being there bothers you then yeah, but there's no actual need lol
