### ISSUE TITLE
Latest release causes deadlocks

### ISSUE THREAD

**Issue by vars1ty** [smartfrigde/armcord#436]
**Describe the bug**
The most recent release causes the entire client to freeze after about 4 seconds.

**To Reproduce**
1. Download ArmCord from Flatpak
2. Run it in a Wayland compositor (might not be needed, just my setup)
3. Watch it freeze

**Expected behavior**
The client works as expected.

**Screenshots**
Here's a [video](https://streamable.com/btrk66) of the behavior.

**Desktop (please complete the following information):**
 - OS: Linux
 - Method of installation: Flatpak
 - Version: 3.2.2 - Raspberry

**Comment by vars1ty** [comment]
**Update**: Tried the AUR version as well, clearing all configs etc. Same deadlock and eventual crashes, and DevTools claim it has been disconnected too.

**Comment by gitmylo** [comment]
Yeah i just get a grey screen once it loads, and it stays like that.

**Comment by cat-master21** [comment]
This also happens with me on the latest Flatpak version (3.2.2), Gnome 44, Fedora 38 on both Wayland and Xorg session. By pressing quickly enough I can get just barely through installation and then it crashes again.

**Comment by wesleyote** [comment]
A grey screen always appears a few seconds after completely loading. This is on Armcord 3.2.2 from Flatpak on X11.

**Comment by orowith2os** [comment]
An update will be released tomorrow, going back to a stable Electron version; ArmCord 3.2.2 uses a beta version of it. Unfortunately, this means screensharing will be a bit broken again.
