### ISSUE TITLE
Global Push to Talk

### ISSUE THREAD

**Issue by fontomp** [smartfrigde/armcord#438]
Armcord seems to use the modified browser version of discord rather than the standa-alone client. This is unfortunate as the browser version's push to talk is limited since it cannot listen to keyboard inputs when it is not in-focus. It would be convienent if a work around to find a system-wide push to talk was found.

I don't know exactly at all how to do it, but someone has already made a google chrome script on that's available on github. Perhaps take a look? https://github.com/mjmartis/discord_web_sys_ptt

**Comment by orowith2os** [comment]
Global keybinds are a work in progress, and should be usable for this once they're done. For now, just mute it at the system level.

**Comment by smartfrigde** [comment]
Duplicate of #88
