### ISSUE TITLE
Question: How to get Transparency working

### ISSUE THREAD

**Issue by sawrams** [smartfrigde/armcord#439]
im using ArmCord 3.2.3, and can't get transparency working, i set it in settings and restarted the app, but nothing changed
Is there some theme i need to apply for transparency working?

**Comment by Vendicated** [comment]
yes you need a specific theme. here's one example that should work https://dablulite.github.io/css-snippets/VesktopMica/import.css

**Comment by sawrams** [comment]
> yes you need a specific theme. here's one example that should work https://dablulite.github.io/css-snippets/VesktopMica/import.css

Thanks!
