### ISSUE TITLE
Feature request: Ability to block rpc

### ISSUE THREAD

**Issue by road2react** [smartfrigde/armcord#440]
**Is your feature request related to a problem? Please describe.**
Sometimes, when opening a Discord invite link in browser, I would prefer if the desktop client would not open.

**Describe the solution you'd like**
Discord web client should be able to not communicate with the desktop client.

**Comment by smartfrigde** [comment]
You mean ArmCord as in desktop client or the official Discord client?

**Comment by road2react** [comment]
> You mean ArmCord as in desktop client or the official Discord client?

ArmCord as the desktop client

**Comment by smartfrigde** [comment]
![image](https://github.com/ArmCord/ArmCord/assets/37928912/76e0f137-0488-4113-b60e-59bfdb3a9112)
Just disable the rpc setting
