### ISSUE TITLE
Update the dynamic tray icon to Discord icon

### ISSUE THREAD

**Issue by mBelisarius** [smartfrigde/armcord#441]
**Is your feature request related to a problem? Please describe.**
Not related to a bug. Title.
System: Linux with ArmCord 3.2.3 (Flatpak). Settings: "Tray icon": Dynamic, "Dynamic icon" disabled.

**Describe the solution you'd like**
Change the dynamic tray icon to the Discord icon (keeping the number of notifications).

(left) Official Discord app tray icon. (right) ArmCord app with dynamic tray icon.
![image](https://github.com/ArmCord/ArmCord/assets/95736227/d185df85-7910-4c14-9b05-a71b4b80a552)

**Comment by SomeAspy** [comment]
After poking around a bit, we get the tray icon from the discord favicon, which is the right one. I suppose we could alter the image on the fly or let it max out at 9+ (this would require having 11 different versions of each icon we want to make dynamic, each with a different number bubble)
I can't see a way to do this without being quite wasteful with resources, whether they be the amount of images we have to package or generating a new image every time you get a ping.
Of course, we remain open to suggestions.
![image](https://github.com/user-attachments/assets/f8ca2007-7fac-48b4-a93b-856d4156fdc6)
