### ISSUE TITLE
Menus don't work in developer tools

### ISSUE THREAD

**Issue by Davilarek** [smartfrigde/armcord#442]
**Describe the bug**
(Context) menus don't work in developer tools.

**To Reproduce**
1. Open devtools
2. For example, in elements tab, try to right click an element
3. See no menu displayed
4. The same issue happens in other places where context menus are used in developer tools.

**Expected behavior**
Context menus to work

**Screenshots**
https://github.com/ArmCord/ArmCord/assets/62715937/682a9133-6f48-4e81-8f4f-5bf6de9d14ba

**Desktop (please complete the following information):**
 - OS: Windows
 - Method of installation: setup exe
 - Version: 3.2.3

**Additional context**

**Comment by Vendicated** [comment]
this is a chromium/electron bug that can be fixed via `app.commandLine.appendSwitch("disable-features", "WidgetLayering");`

https://github.com/electron/electron/issues/38790

**Comment by smartfrigde** [comment]
fixed in latest commit

**Comment by Davilarek** [comment]
still happens on 3.2.4
