### ISSUE TITLE
Discord Gateway dies after ~5 minutes of ArmCord not being focused

### ISSUE THREAD

**Issue by Davilarek** [smartfrigde/armcord#443]
**Describe the bug**
Discord Gateway dies after ~5 minutes of ArmCord not being focused,
I observed this issue many many times before.
It happens without any mods.
This issue may result in for example, no message notification.

**To Reproduce**
1. Open devtools (for observation)
2. Leave discord open and just switch to another window
3. After 5 to 10 minutes go back to devtools
4. See gateway start to reconnect at the same moment you focus on devtools/main armcord window

**Expected behavior**
The discord gateway should not close

**Screenshots**
![obraz](https://github.com/ArmCord/ArmCord/assets/62715937/6211399f-089e-40d3-8c81-06eafcb4b022)

**Desktop (please complete the following information):**
 - OS: Windows
 - Method of installation: setup exe
 - Version: 3.2.3
 Note: this doesn't happen on linux

**Additional context**

**Comment by Davilarek** [comment]
According to my observation, the client "forgets" to send the `heartbeat` which results in the gateway getting terminated.
Last heartbeat sent before termination:
![obraz](https://github.com/ArmCord/ArmCord/assets/62715937/fa77ea6e-0bab-4586-895e-713a94e60a23)
Last message sent by gateway:
![obraz](https://github.com/ArmCord/ArmCord/assets/62715937/d733d21e-7b86-4bf1-b9c5-6a6509f778c2)
That's 55 seconds difference
The heartbeat interval was: `41250` (41.25 seconds)

**Comment by okuue** [comment]
same issue here, did you find a fix?

**Comment by smartfrigde** [comment]
Try running with `--disable-renderer-backgrounding` flag

**Comment by Davilarek** [comment]
I'm unable to test this fix/workaround since I switched to Arch, where this issue doesn't happen.
