### ISSUE TITLE
BUG: Tray Icon Not Displaying Properly in Flatpak Version on Linux

### ISSUE THREAD

**Issue by tim-gromeyer** [smartfrigde/armcord#446]
**Describe the bug**

The tray icon for ArmCord is not displaying correctly on the Linux Flatpak version. Instead of showing the selected logo, it only displays three dots, which typically indicates that no icon was specified.

**To Reproduce**

1. Install ArmCord via Flatpak.
2. Open the application.
3. Observe the tray icon list, where you will see three dots instead of the expected logo.

**Expected behavior**

The selected logo/icon should be displayed as the tray icon for ArmCord.

**Screenshots**
Left is the standard Discord app (Flatpak version), In the middle ArmCord, and right is Steam

![image](https://github.com/ArmCord/ArmCord/assets/58736434/4eed97e7-5ae0-475e-a92f-da583c1e2a8c)

**Desktop (please complete the following information):**
 - OS: Linux, openSUSE Tumbleweed
 - Method of installation Flatpak
 - Version 3.2.3
 - Desktop Enviroment: GNOME with [AppIndicator and KStatusNotifierItem Support](https://extensions.gnome.org/extension/615/appindicator-support/)

**Additional context**
I have tried selecting various icons, but none of them are showing up in the tray. I have also attempted restarting the application and my system, but the issue persists.

EDIT: It works in the RPM version

**Comment by orowith2os** [comment]
Upstream extension bug, and potentially an issue of the spec as a whole.

**Comment by tim-gromeyer** [comment]
Can you link the issue please?

**Comment by tim-gromeyer** [comment]
@orowith2os ?
