### ISSUE TITLE
Saving accounts for multi-instance

### ISSUE THREAD

**Issue by ZainHan33** [smartfrigde/armcord#453]
I dont know if this is possible

For multi-instance, save detail for every account so login is automatic. 

On windows, it remembers the first account saved, but every instance opened after the first one is the login screen.

**Comment by ddodogames** [comment]
You can use the discord's account switcher feature? It allows you so that you can switch between your alts without having to log out and login on the other one and thus i believe this makes the process less painful.

Personally i'm not sure on why do you need that though.

**Comment by ritiek** [comment]
Facing similar issue on Arch having installed armcord-bin (3.2.7-1) through AUR.

I enabled the "Multi Instance" option in armcord settings. But right now, any successive armcord instances open up to the login page. It'd be nice if successive instances are able to reuse the same configuration so it's not required to relogin and resync our vencord plugins and themes everytime on new instances (after the first one).

My usecase of having multiple instances (windows) of armcord running is to be able to open up and monitor different guild channels at the same time.

**Comment by ritiek** [comment]
I made an attempt to fix this behaviour (https://github.com/ArmCord/ArmCord/pull/604).

**Comment by TheAwesome98-Real** [comment]
> but every instance opened after the first one is the login screen

this still happens. i'd like to be able to have 2 instances with different accounts logged in while using the same data dir if possible
