### ISSUE TITLE
Avoid dupe instances

### ISSUE THREAD

**Issue by awsms** [smartfrigde/armcord#456]
When launching ArmCord, verify if there is another instance running. If that's the case, bring the running one to the foreground

**Comment by Void48** [comment]
> When launching ArmCord, verify if there is another instance running. If that's the case, bring the running one to the foreground

Been having the same issue with ArmCord opening another instance after clicking the taskbar icon when minimized in tray

**Comment by takase1121** [comment]
If you use a recent enough (as in a few months old) of ArmCord, it should already check for instances (and allow multi-instances, please check that in ArmCord settings!).

Not sure if this will fix it or not, but it did for me a while ago in #458 

# back up all your settings.

Close ArmCord completely and delete the `~/.config/ArmCord` folder (or `APPDATA/armcord` on Windows, I'm not too sure). This seemed to fixed it for me.

**Comment by awsms** [comment]
> If you use a recent enough (as in a few months old) of ArmCord, it should already check for instances (and allow multi-instances, please check that in ArmCord settings!).
> 
> Not sure if this will fix it or not, but it did for me a while ago in #458
> 
> # back up all your settings.
> Close ArmCord completely and delete the `~/.config/ArmCord` folder (or `APPDATA/armcord` on Windows, I'm not too sure). This seemed to fixed it for me.

Unfortunately, this workaround is not reliable for me (have to re-do it everytime I exit and relaunch armcord).

**Comment by daddyov2** [comment]
This is happening to me on ChromeOS. Tried to remove and reinstall and it still happens (and not sure I can navigate to ~/.config/ArmCord as it stands)

Opens one instance logged in, and then another non-logged in instance

**Comment by smartfrigde** [comment]
Can you re-test on latest release?

**Comment by SomeAspy** [comment]
Closing because no response in over a month.
