### ISSUE TITLE
APT Repo still on 3.2.3

### ISSUE THREAD

**Issue by ToasterUwU** [smartfrigde/armcord#457]
**Describe the bug**
For some reason, the APT Repo shows 3.2.3 to be the newest version.

**To Reproduce**
1. Have armcord 3.2.4 installed, so that the armcord repo gets added
2. `apt show armcord -a`
3. If you have 3.2.4 installed, you will see that 3.2.4 has `APT-Sources: /var/lib/dpkg/status`
4. And below it it shows the armcord version you can get from the Repo, which is version 3.2.3 as the newest one, and `APT-Sources: https://eu.armcord.xyz/apt-repo stable/main amd64 Packages` as source

**Expected behavior**
The newest version should be installable trough APT as well

**Screenshots**
```
aki@Barbara:/etc/apt/sources.list.d$ apt show armcord -a
Package: armcord
Version: 3.2.4
Status: install ok installed
Priority: optional
Section: default
Maintainer: smartfridge@vivaldi.net
Installed-Size: 256 MB
Depends: libgtk-3-0, libnotify4, libnss3, libxss1, libxtst6, xdg-utils, libatspi2.0-0, libuuid1, libsecret-1-0
Recommends: libappindicator3-1
Homepage: https://github.com/armcord/armcord#readme
License: OSL-3.0
Vendor: smartfridge@vivaldi.net
Download-Size: unknown
APT-Manual-Installed: yes
APT-Sources: /var/lib/dpkg/status
Description: ArmCord is a custom client designed to enhance your Discord experience while keeping everything lightweight.

Package: armcord
Version: 3.2.3
Priority: optional
Section: default
Maintainer: smartfridge@vivaldi.net
Installed-Size: 249 MB
Depends: libgtk-3-0, libnotify4, libnss3, libxss1, libxtst6, xdg-utils, libatspi2.0-0, libuuid1, libsecret-1-0
Recommends: libappindicator3-1
Homepage: https://github.com/armcord/armcord#readme
License: OSL-3.0
Vendor: smartfridge@vivaldi.net
Download-Size: 68,5 MB
APT-Sources: https://eu.armcord.xyz/apt-repo stable/main amd64 Packages
Description: ArmCord is a custom client designed to enhance your Discord experience while keeping everything lightweight.
```

**Desktop (please complete the following information):**
 - OS: Linux (Ubuntu based Distro)
 - Method of installation: APT and .deb file
 - Version: All Versions

**Comment by TheQuos** [comment]
I've been using Armcord for a few months now and had this problem since I can remember. I think I had to get the .deb file for each update (or at least the last 2).

**Comment by ToasterUwU** [comment]
> I've been using Armcord for a few months now and had this problem since I can remember. I think I had to get the .deb file for each update (or at least the last 2).

This is the first version with this issue for me. I installed the last 5 all via APT just fine.

**Comment by smartfrigde** [comment]
This is caused by this issue https://github.com/ArmCord/ArmCord/issues/454, it won't get updated unless that gets fixed

**Comment by smartfrigde** [comment]
I updated the debs on the apt-repo to e27 beta 2, since ~~the tag hasn't changed you might need to try to force apt to redownload the debs~~. Nevermind forgot the apt was still stuck on 3.2.3
