### ISSUE TITLE
No microphone audio

### ISSUE THREAD

**Issue by re7gog** [smartfrigde/armcord#459]
**Describe the bug**
When I change mic input level from default, nobody can hear me

**To Reproduce**
1. Go to Settings - Audio and video
2. Click and scroll input sensitivity
3. Join voice chat
4. No voice input

**Expected behavior**
Working voice input with changed input sensitivity from default

**Screenshots**
-

**Desktop (please complete the following information):**
 - OS: Windows 11 22621.2215
 - Method of installation: Setup exe
 - Version: 3.2.4

**Additional context**
Stable channel + Vencord mod

**Comment by SomeAspy** [comment]
Can you reproduce this in https://github.com/ArmCord/ArmCord/releases/tag/v3.2.8?

**Comment by re7gog** [comment]
I dropped this client, too many bugs, vesktop better, bye 👋

**Comment by SomeAspy** [comment]
Damn

**Comment by thepwrtank18** [comment]
yeah i'm dropping too, too many bugs
