### ISSUE TITLE
Completely blank window

### ISSUE THREAD

**Issue by RealFX-Code** [smartfrigde/armcord#460]
**Describe the bug**
When I try and open ArmCord the window is completely blank, and I've tried running it "natively" under wayland (with the arguments i passed), and running it with "--disable-gpu" to no avail.
**To Reproduce**
1. Download ArmCord from flathub on Void Linux
2. Try to open ArmCord

**Expected behavior**
ArmCord Opens

**Screenshots**
https://transfer.sh/hSgxioqhy9/recording.mp4

**Desktop (please complete the following information):**
 - OS: Void Linux
 - Method of installation: Flathub/Flatpak
 - Version: 3.2.4

**Additional context**
I'm running Sway under Wayland fwiw

**Comment by smartfrigde** [comment]
https://github.com/ArmCord/ArmCord/issues/454
