### ISSUE TITLE
ArmCord not running on Apple Silicon

### ISSUE THREAD

**Issue by Logster9982** [smartfrigde/armcord#461]
**Describe the bug**
ArmCord cannot run on MacOS silicon in the native Arm64 application. Any attempt to run gives the OS "App is damaged and can't be opened dialogue. 

**To Reproduce**
1. Download Arm64 .dmg or app
2. Run installation process (Drag to applications folder)
3. Run Application

**Expected behavior**
Start the Armcord loading screen, then go to the discord ui.

**Screenshots**
<img width="257" alt="Screenshot 2023-09-09 at 11 23 31 PM" src="https://github.com/ArmCord/ArmCord/assets/53102654/47eb373a-3534-4c2c-8541-65ee6a8d6cdd">

**Desktop Information:**
 - OS: MacOS
 - Method of installation: Both dmg and .app
 - Version: 3.2.4
 - M2 Max Macbook Pro

**Additional context**
This is not the same as the "This application is unsafe" dialogue which simply requires the user to go to system settings and manually allow the application. This error cannot be bypassed and does not give a security prompt, it just quits the application. The x86_64 version running through Rosetta2 still functions fine and has no issues even on 3.2.4.

**Comment by georgemoodier** [comment]
The webcord discord client has the same issue, see [here](https://github.com/SpacingBat3/WebCord/issues/173) (the issue thread also offers solutions for the problem)

**Comment by Logster9982** [comment]
Thanks for showing me that, I was able to get the native arm version running by using 

`codesign --force --deep --sign - /Applications/WebCord.app made`

to resign the application. If that doesn't work for anyone else, removing the app from the blacklist might be needed too:

`xattr -r -d com.apple.quarantine /Applications/WebCord.app`

The native version runs so well compared to Rosetta, hoping the signing issue that seems to be plaguing a lot of electron apps gets fixed soon.

**Comment by Logster9982** [comment]
No updates were listed here, but current MacOS 14 and 15 no longer have the broken label and just run after allowing through settings. Most likely the bug in the base electron branch was fixed and merged into here with an update.
