### ISSUE TITLE
Icon is oversized in macOS

### ISSUE THREAD

**Issue by biennvops** [smartfrigde/armcord#462]
**Describe the bug**
As title.

**To Reproduce**
1. Have ArmCord on dock

**Expected behavior**
The app icon should have the same shape and size as other icons.

**Screenshots**
<img width="347" alt="Screenshot 2023-09-12 at 13 16 22" src="https://github.com/ArmCord/ArmCord/assets/96908843/4c09b697-e300-4826-826f-94174dfd095c">

**Desktop (please complete the following information):**
 - OS: macOS
 - Method of installation: dmg
 - Version: 3.2.4

**Additional context**
This issues happen because the usage of png file for icon. macOS expects an ICNS file as app icon for dynamic resizing.
I've made two new app icons as a fix.

Ver1: The same icon like before, only fixed for macOS
<img width="349" alt="Screenshot 2023-09-12 at 13 20 03" src="https://github.com/ArmCord/ArmCord/assets/96908843/59f92765-2f69-43cf-94ef-d5949a2fced9">

Ver2: With white background
<img width="344" alt="Screenshot 2023-09-12 at 13 18 03" src="https://github.com/ArmCord/ArmCord/assets/96908843/1794427f-d0e1-472c-a3b8-bdc4917d669b">

These two versions can be downloaded here: [armcord-icons.zip](https://github.com/ArmCord/ArmCord/files/12583083/armcord-icons.zip)

I could have made a pull request for this, but I don't know if this icon style will break other OSes (Windows, Linux, etc.) or not.
Also I can't decide which icon should be choosen. (I like the Ver2 one tho)

**Comment by orowith2os** [comment]
Does macOS accept SVGs for the icon? If so, I believe Windows supports them too, and Linux heavily encourages them.

**Comment by biennvops** [comment]
> Does macOS accept SVGs for the icon? If so, I believe Windows supports them too, and Linux heavily encourages them.

I'm not sure, I've never tested SVGs for the app icons. macOS still prefers ICNS though.

**Comment by smartfrigde** [comment]
Thank you so much for fixing this, I used version 2 of your icon in [this commit](https://github.com/ArmCord/ArmCord/commit/e9678f10939b6b5353fd6dc845956ac001fa95d7)
