### ISSUE TITLE
Cannot launch ArmCord on Arch Linux

### ISSUE THREAD

**Issue by tazz4843** [smartfrigde/armcord#463]
**Describe the bug**
I recently got an update to the AUR package a few hours ago (using `armcord-git` to fix #454). The default install won't launch with an undefined symbol error:
```
niko@niko-desktop ~ > armcord
/usr/lib/electron25/electron: symbol lookup error: /usr/lib/electron25/electron: undefined symbol: av_stream_get_first_dts, version LIBAVFORMAT_60
```

**To Reproduce**
1. `paru -Syu`
2. `paru -S armcord-git`
3. `armcord`

**Expected behavior**
No error to happen and ArmCord to launch

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Method of installation: AUR
 - Version: `armcord-git-r756.81273de-1`

**Additional context**
Installing `electron27-bin` from the AUR (`paru -S electron27-bin`) and modifying `/usr/bin/armcord` such that it points to that instead (`electron=/usr/bin/electron27`) fixes both #454 and this one at the same time.

**Comment by askiiart** [comment]
I was experiencing the same issue, but only with `armcord-bin`, and installing `armcord-git` instead worked for me on my laptop, but I did not have any issues on my desktop. On my laptop, the pre-built binary version works on some distros, but not on others (such as Arch), but on my desktop (and my second laptop) it works regardless of distro.

Desktop:

- Arch Linux with Budgie DE
- Ryzen 5 3600
- RX 580 8GB
- `armcord-bin` works

Laptop:

- Arch Linux with Budgie DE
- Intel i5-11300H
- Intel Xe Graphics (TGL GT2)
- `armcord-bin` crashes as described in #454 , but `armcord-git` works

Second laptop:

- Arch Linux with Budgie DE
- Intel i5-6200U
- Intel iGPU
- `armcord-bin` works

**Comment by askiiart** [comment]
With 3.2.5, ArmCord now works for me, what about for you @tazz4843 ?

**Comment by SomeAspy** [comment]
closing as another user has reported it as fixed
