### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by i0x0** [smartfrigde/armcord#470]
**Describe the bug**
I install armcord from both flatpak, deb, and source and when I try to do the setup, it works for a few seconds and then i get a black screen and also getting
```
(node:45170) UnhandledPromiseRejectionWarning: TypeError: Object has been destroyed
    at IpcMainImpl.<anonymous> (/opt/ArmCord/resources/app.asar/ts-out/ipc.js:94:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
(Use `armcord --trace-warnings ...` to show where the warning was created)
(node:45170) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

**To Reproduce**
1. Launch it, as if you're opening it for the first time

**Expected behavior**
To not get a blank screen?

**Screenshots**
![Screenshot from 2023-09-23 19-42-27](https://github.com/ArmCord/ArmCord/assets/29006605/d337c4c3-3abc-49ea-b072-b9fba19a4ee1)

**Desktop (please complete the following information):**
 - OS: Zorin OS 16.3 (Ubuntu 22.04)
 - Method of installation: flatpak, deb, source
 - Version: 3.3.0

**Additional context**
Weirdly when I was running Arch and installed it from the AUR, I didn't get this issue

**Comment by 0xk1f0** [comment]
Having the same issue here on Arch Linux, both with the AUR Package and Flatpak.

Same Error code as above.

EDIT:
Tried building from latest master, seems to work fine now.

**Comment by smartfrigde** [comment]
https://github.com/ArmCord/ArmCord/issues/454
