### ISSUE TITLE
Volumebooster plugin missing

### ISSUE THREAD

**Issue by snoopchallenge** [smartfrigde/armcord#473]
**Describe the bug**
Cannot find volume booster plugin whilst using vencord
**To Reproduce**
1. Select client mod Vencord in armcord settings
2. Go to vencord plugins
3. Search for volumebooster in plugins
4. Cannot see volumebooster

**Expected behavior**
Volumebooster shows in plugins

**Screenshots**
https://imgur.com/a/gq2G5lL

**Desktop (please complete the following information):**
 - OS: Windows
 - Method of installation: setup exe
 - Version: 3.2.4

**Additional context**
https://vencord.dev/plugins/VolumeBooster

**Comment by Vendicated** [comment]
it's only available on the discord desktop app.

**Comment by Milor123** [comment]
> it's only available on the discord desktop app.

and, No found a alternative using ArmCord in 2024?  :/
