### ISSUE TITLE
Window only displays the clear color shortly after launch

### ISSUE THREAD

**Issue by me-self** [smartfrigde/armcord#474]
**Describe the bug**
Shortly after launch, regardless of the current state, the window begins to stay on the clear color.

**To Reproduce**
1. Download the Flatpak off of Flathub
2. Launch it

**Expected behavior**
I expect to see updates to the window

**Screenshots**
![image](https://github.com/ArmCord/ArmCord/assets/115949508/550064e7-5422-4538-a70b-82273cae1fc7)

**Desktop (please complete the following information):**
 - OS: Linux (OpenSUSE)
 - Flatpak
 - Version 3.2.4

**Additional context**
I've tried with both Wayland and Xorg

**Comment by zastrixarundell** [comment]
I geneerally fixed it by disabling and/or enabling the wayland socket and trying to launch it.

**Comment by smartfrigde** [comment]
Can you reproduce this on latest stable version?

**Comment by me-self** [comment]
> Can you reproduce this on latest stable version?

I'm not longer using OpenSUSE, so I can't say whether the issue is in some way specific to certain components of OpenSUSE, but I do not get this issue with the Flatpak on the Fedora derivative which I am now using (Same GPU driver as before; Nouveau driver).

**Comment by smartfrigde** [comment]
It could be hardware acceleration being hit or miss. If you run into this issue in the future try running with it `--disable-gpu` flag
