### ISSUE TITLE
Autogain is always on.

### ISSUE THREAD

**Issue by forgettablepyromaniac** [smartfrigde/armcord#475]
**Describe the bug**
After an update I believe (since it worked for a while before), autogain is always enabled.

**To Reproduce**
Just be using the most recent version of the software.
Disabling autogain in the Armcord settings or in the Voice & Video section does nothing.

**Expected behavior**
For autogain to be disabled when I tell it to be.

**Desktop (please complete the following information):**
 - Linux Mint 21.2
 - apt installation
 - Version 3.2.4

**Additional context**
I only realized this when my friends kept pointing out that I was quiet all the time, so I opened my mic's sound settings, only to realize that it's just going down. I could sit there and watch it decrease as I talked.

This could be a "just my computer" issue, but I still want to try and get it fixed before giving up & moving on.

**Comment by Systemblaster666** [comment]
Having the same problem :)

**Comment by NextWork123** [comment]
for resolve that issue you can go on `/home/$USER/.config/ArmCord/storage/` and modify that file `settings.json` and modify that `"disableAutogain": false,` to `"disableAutogain": true,`

Tell me if you resolve that issue :)

**Comment by forgettablepyromaniac** [comment]
it's oddly not doing it now, I'm going to mess around with it and try my best to recreate it. I **do** know it was a real issue I had, I'm not crazy I swear! But yeah, it's weird to say the least.
