### ISSUE TITLE
Buggy audio in voice channels when there is already people inside

### ISSUE THREAD

**Issue by xppcom** [smartfrigde/armcord#476]
**Describe the bug**

**To Reproduce**
I don't know if this is important or not, but i'm using a VPN (ProtonVPN) with ArmCord
1. Go to a voice channel with people inside
2. Try to hear them
3. You can't their voice is constantly cutting and being robotic
It works fine when logging into discord on firefox

**Expected behavior**
I can hear people properly

**Desktop (please complete the following information):**
 - OS: Gentoo 
 - Method of installation: flatpak
 - Version: 3.2.4

**Comment by Lock-The-Door** [comment]
I seem to have this issue too, and it seems to affect all audio that's playing, not just armcord

**Comment by smartfrigde** [comment]
Try 3.2.6 please

**Comment by Lock-The-Door** [comment]
Looks like it works now
