### ISSUE TITLE
3.2.3 ran without problems in my system. Updated to 3.2.4, and now ArmCord won't start.

### ISSUE THREAD

**Issue by chaosDesigner99** [smartfrigde/armcord#477]
**Describe the bug**
As I said above, I installed ArmCord recently, on version 3.2.3, and it worked fine on my system. Then I updated through `sudo apt upgrade`, and now the program crashes before it loads. I tried opening it through the terminal, and it repeated this error message many times: `[18273:1002/134112.681711:ERROR:gpu_process_host.cc(991)] GPU process exited unexpectedly: exit_code=133`, then it gave this error and aborted launching: `[18273:1002/134112.681766:FATAL:gpu_data_manager_impl_private.cc(448)] GPU process isn't usable. Goodbye.`

**To Reproduce**
Simply update from 3.2.3 to 3.2.4, then start the program.

**Expected behavior**
ArmCord should start after the small loading window shows up, but instead it just aborts.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Method of installation: repository
 - Version 3.2.4

**Comment by KaleiAlma** [comment]
#454 ? It's probably related, even if it's a crash instead of a blank screen...

**Comment by smartfrigde** [comment]
Should be fixed in 3.2.6
