### ISSUE TITLE
Screenshare on Wayland (sway/wl-roots) requires selecting screen 3 times

### ISSUE THREAD

**Issue by ModProg** [smartfrigde/armcord#478]
**Describe the bug**

**To Reproduce**
1. Click the screen share button.
2. Select screen
3. Select screen again
4. *Now the Preview for the screen share appears in Discord and the sound is played.*
5. Select screen one last and final time, now it works.

**Expected behavior**
Should only need to select screen once

**Desktop (please complete the following information):**
 - OS: Linux + Sway
 - Method of installation aur
 - Version 3.3.0

**Additional context**
This might be related to the wl-roots xdg-desktop-portal implementation, maybe e.g. gnome caches the request when it happens multiple times in short succession and wl-roots does not.

Probably this could be worked around by `ArmCord` caching the response from the first request of starting the screen share. (I haven't looked at ArmCord's source, so I don't know if this is actually what happens.)

**Comment by Sollace** [comment]
Same issue here. It asks which screen, then asks which window, then asks which screen.

Only the last selection is used.

Cancelling or simply closing any of the prompts without making a selection renders screensharing completely broken until a restart (clicking the button to start screenshare does nothing).

Screenshare also has no audio.

Edit:
Environment for me is using the Flatpak version on Manjaro + KDE with the wayland session.

**Comment by Frontear** [comment]
This issue is present on Webcord as well, which makes me believe it might be an Electron/Chromium specific issue.

**Comment by takase1121** [comment]
I think its an Electron specific issue. The first two prompts might be to display thumbnails when picking Window / Screen and the 3rd one is for the actual screensharing.

**Comment by v1ctorio** [comment]
Same happens on Hyprlnd/nixos package

**Comment by smartfrigde** [comment]
I think this fixed with one of Electron updates
