### ISSUE TITLE
Screen is blanked out white during setup

### ISSUE THREAD

**Issue by mak448a** [smartfrigde/armcord#482]
**Describe the bug**
When doing setup, the setup window turns completely white

**To Reproduce**
1. Download ARMCord from flathub.
2. Run in on Fedora 38 KDE spin Wayland
3. Click through a couple of steps
4. BUG!!!!

**Expected behavior**
No screen blanking

**Screenshots**
Even the titlebar is gone!
![image](https://github.com/ArmCord/ArmCord/assets/94062293/5f5fb594-cc96-46ed-b83e-f575991280b4)

**Desktop (please complete the following information):**
 - OS: Fedora Linux 38 KDE Spin
 - Method of installation: Flathub
 - Version: 3.2.4

**Additional context**
Some bad reviews are on KDE Discover because it won't launch

**Comment by zastrixarundell** [comment]
Open flatseal and mess around with the wayland socket. Disable and re-enable a few times and try to launch armcord in-between. After that it starts working.

**Comment by jfaz1** [comment]
Same issue on Fedora/Xorg with both the Flatpak and RPM version. Just blanks out after a (short) while. I managed to get through installation by spamming it fast enough before blanking and get to the login prompt, but I can't login because it blanks before I'm able to.

**Comment by Frontear** [comment]
Happens to me when running natively, so its definitely not a flatpak specific issue. On Wayland, using Hyprland.

**Comment by kkrruumm** [comment]
Same issue here on Void with Gnome Wayland using the Flatpak.

**Comment by SvdB-nonp** [comment]
**Update: The 3.2.4-e27 version seems to work: https://github.com/ArmCord/ArmCord/releases/tag/v3.2.4-e27**
Also, this seems the same issue as https://github.com/ArmCord/ArmCord/issues/454.

---

Original post:
Same. When running from terminal this seems to be the associated eror:

[log.txt](https://github.com/ArmCord/ArmCord/files/12890628/log.txt)
```
[34696:1013/091610.885363:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[34696:1013/091631.980588:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
```

Since it mentions Vsync, I tried turning of VRR, disabling my second screen, and even set the hz back to 60 (from 165). But all seem to have no effect.

- Fedora 38
- Gnome with [VRR patch](https://copr.fedorainfracloud.org/coprs/kylegospo/gnome-vrr/)
- Both Wayland and Xorg
- Both Appimage and Flatpak

**Comment by gordallott** [comment]
3.2.5 has this issue for me on wayland (flatpak install)

```
➜  ~ flatpak info xyz.armcord.ArmCord 

ArmCord - ArmCord is a custom client designed to enhance your Discord
experience while keeping everything lightweight.

          ID: xyz.armcord.ArmCord
         Ref: app/xyz.armcord.ArmCord/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 3.2.5
     License: OSL-3.0
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 258.8 MB
     Runtime: org.freedesktop.Platform/x86_64/22.08
         Sdk: org.freedesktop.Sdk/x86_64/22.08

      Commit: 7753dc1c0859cc88476fe5e7ccca4a334a00b01f656f4916bc2077640879f5a5
      Parent: 46e148e57578ad7129730e3dcf0ea77c60c1d1d39908ba5f3b7ad3d5edccf435
     Subject: Update 2 modules (e52b6f2c)
        Date: 2023-10-22 01:04:04 +0000
```

**Comment by taukakao** [comment]
The new version fixed it for me. Vanilla OS 22.10 and Fedora 38. Both Flathub.
I had to manually remove the data folder in ~/.var/app/xyz.armcord.ArmCord though, otherwise it wouldn't start.

**Comment by mak448a** [comment]
I'll try too and close the issue if it works. Thanks!
Edit: it works great!
