### ISSUE TITLE
RNNoise not working

### ISSUE THREAD

**Issue by snoopchallenge** [smartfrigde/armcord#483]
**Describe the bug**
Microphone is not detected when using rnnoise in vencord

**To Reproduce**
1. Active the RNNoise plugin
2. Restart vencord
3. Try to talk in a voice chat
4. Discord shows no voice

**Expected behavior**
Microphone is detected

**Screenshots**
https://imgur.com/a/eTC17V5 

**Desktop (please complete the following information):**
 - OS: Windows
 - Method of installation setup exe
 - Version 3.2.4

**Additional context**
Microphone is detected while using the krisp noise cancellation in discord

**Comment by smartfrigde** [comment]
Report upstream
