### ISSUE TITLE
Window won't show up on laptop with discrete gpu

### ISSUE THREAD

**Issue by CyberDruga** [smartfrigde/armcord#485]
**Describe the bug**
When  I start the application it stays on tray and don't show anything at all.

**To Reproduce**
This is quite a complicated setup to reproduce the error, but here it goes: 
I'm using a laptop with a discrete Nvidia gpu. There's an option in it's bios that allows me to use only the discrete gpu, which run things smoother, but it makes Armcord not show it's screen for some reason, and that's it. Disabling this option makes Armcord work again, but at the cost of everything running slower.

**Expected behavior**
Show the screen like it usually does

**Desktop (please complete the following information):**
 - OS: Nobara Linux 38
 - Method of installation: Flatpak
 - Version: 3.2.4

**Additional context**
using `--disable-gpu` makes things work somewhat decently, but I keep getting this pop-up every time I change servers: 
![image](https://github.com/ArmCord/ArmCord/assets/22626848/ca0bece5-0448-4404-b9e8-48095119ee62)

I've made this small shell script to downgrade Armcord until I found a version that works, and to also collect some logs:
```bash
flatpak remote-info --log flathub xyz.armcord.ArmCord --system | awk '/Commit/ {print $2}' | while read line; do echo trying commit $line; sudo flatpak update --commit=$line xyz.armcord.ArmCord --system -y; flatpak run xyz.armcord.ArmCord --system; done &> logs.txt
```

And here are the said logs:

[logs.txt](https://github.com/ArmCord/ArmCord/files/12908616/logs.txt)

They stop right after I found a version that works fine.

**Comment by smartfrigde** [comment]
Newest release should fix this
