### ISSUE TITLE
Registered Games and Game Overlay gone

### ISSUE THREAD

**Issue by NotANumberNaN** [smartfrigde/armcord#487]
Under the Activity Settings section of settings, there's only Activity Privacy in Armcord, whereas in vanilla Discord there is also Registered Games and Game Overlay.

Vencord:
![image](https://github.com/ArmCord/ArmCord/assets/146566842/2b9653cf-6f6f-43d1-a1f3-eaf1f8feb7a5)

Vanilla Discord:

![image](https://github.com/ArmCord/ArmCord/assets/146566842/8b601d44-734f-4729-a0e9-466143e78c99)

![image](https://github.com/ArmCord/ArmCord/assets/146566842/344a6e09-96d6-4457-ba61-ee22a8693211)

**Comment by dxcvvxd** [comment]
this is related to #411 that i opened a while back, you can check it out

**Comment by ghost** [comment]
Same issue here, is there a fix for it?

**Comment by smartfrigde** [comment]
There's no game overlay implemented in ArmCord and there are no plans for an implementation for now, as for registered games tab. That's useless since we're not using Discord's detection system but arRPC
