### ISSUE TITLE
ArmCord App Injection Missing

### ISSUE THREAD

**Issue by Nailington** [smartfrigde/armcord#491]
**Describe the bug**
I am missing the ArmCord settings part in settings, and certain things are not working, such as arRPC.
**To Reproduce**
1. Open Armcord
2. Navigate to Settings
3. Armcord Specific List is Missing

**Expected behavior**
ArmCord Specific Settings Section appears

**Screenshots**
![image](https://github.com/ArmCord/ArmCord/assets/111466491/482cab03-64d7-4f92-ab6a-3aca2ac84d2b)
![image](https://github.com/ArmCord/ArmCord/assets/111466491/374cc657-347a-407b-97b9-39c915998908)

**Desktop (please complete the following information):**
 - OS: Arch Linux x86_64 [6.5.8-arch1-1]
 - Method of installation: AUR (armcord-bin)
 - Version: 3.2.5-2 (From pacman -Qi armcord)

**Additional context**
I noticed this issue yesterday morning, but Vencord also wasn't working right. More specifically Vencord did load, but no plug-ins took effect. I noticed an update was released yesterday and installed it around 5:30PM (Eastern) and Vencord started working again, but ArmCord stuff specifically seems to not load. I can still change settings by opening the menu the tray, but this is inconvenient.

**Comment by Nailington** [comment]
Seems related to https://github.com/ArmCord/ArmCord/issues/411 and possibly https://github.com/ArmCord/ArmCord/issues/487

**Comment by Kyouki-DotExe** [comment]
Also on Arch but both Flatpak + AUR ArmCord's are broken and don't load any plugins for me neither. Cloud Settings also fail to get oauth.

**Comment by 3top1a** [comment]
I'm getting the same thing, it also says "There is a new version of armcord available" on startup, both in the AUR version and the latest AppImage.

**Comment by smt923** [comment]
I'm getting this on windows too, I thought I did something wrong but I guess it is just broken, I had none of the added Armcord settings but I was able to see the stuff added from vencord, I also had "new version of armcord available" when using the github release (3.2.5) but that was not the case with the MS store release (3.3.0)

Win11 22H2

**Comment by Nailington** [comment]
Where does it say that "New Version" pop up, I don't think I have ever seen that in memory, including when I updated yesterday. I just was checking for updates like I do regularly

**Comment by Nailington** [comment]
> Also on Arch but both Flatpak + AUR ArmCord's are broken and don't load any plugins for me neither. Cloud Settings also fail to get oauth.

I also am unable to use Cloud Settings I realize. Never really care about the cloud sync, but it has errored every launch since yesterday.

**Comment by smt923** [comment]
> Where does it say that "New Version" pop up, I don't think I have ever seen that in memory, including when I updated yesterday. I just was checking for updates like I do regularly

Probably different as I'm on windows but for me, if I use the release off of github I see it in the loading splash before it loads, I don't see it if I use the MS store version which reports 3.3.0


> > Also on Arch but both Flatpak + AUR ArmCord's are broken and don't load any plugins for me neither. Cloud Settings also fail to get oauth.
> 
> I also am unable to use Cloud Settings I realize. Never really care about the cloud sync, but it has errored every launch since yesterday.

also seem to be getting this with a "could not retrieve oauth configuration" notification, I tried using vencord through vesktop and using that cloudsync appears to be working fine, so I imagine it might be something related to armcord and these other things messing up

**Comment by Nailington** [comment]
> > Where does it say that "New Version" pop up, I don't think I have ever seen that in memory, including when I updated yesterday. I just was checking for updates like I do regularly
> 
> Probably different as I'm on windows but for me, if I use the release off of github I see it in the loading splash before it loads, I don't see it if I use the MS store version which reports 3.3.0
> 
> > > Also on Arch but both Flatpak + AUR ArmCord's are broken and don't load any plugins for me neither. Cloud Settings also fail to get oauth.
> > 
> > 
> > I also am unable to use Cloud Settings I realize. Never really care about the cloud sync, but it has errored every launch since yesterday.
> 
> also seem to be getting this with a "could not retrieve oauth configuration" notification, I tried using vencord through vesktop and using that cloudsync appears to be working fine, so I imagine it might be something related to armcord and these other things messing up

What confuses me mainly is that I am pretty certain there wasn't an update BEFORE the issue arose (in fact armcord was flagged out of date in aur). But I had just reopened the app when the issue started.... I am not sure how updates work with it though. Maybe there was a mini online update or something.

**Comment by Kyouki-DotExe** [comment]
Apparently an update Webpack to rspack_dev which broke VenCord along other things, which is likely our source of problems.

**Comment by pwall2222** [comment]
https://github.com/Vendicated/Vencord/commit/4e27722b543f8a7c86270276df68d7cb89adeec3 I think they fixed it with this commit but I'm not quite sure.

**Comment by Nailington** [comment]
Does that affect ArmCord though?

**Comment by blackthorne7** [comment]
exact same issue here, Fedora x86.

I believe smartfridge said he's aware of the issue and working on a fix (from the discord server).
