### ISSUE TITLE
The builds website is no longer available

### ISSUE THREAD

**Issue by dxomg** [smartfrigde/armcord#492]
**Describe the bug**
The builds website is no longer available

**To Reproduce**
1. Go to 'https://build.armcord.xyz/'

**Expected behavior**
It should load a page with builds that use old electron version

**Screenshots**
![image](https://github.com/ArmCord/ArmCord/assets/101947415/1fd56c69-2cea-4781-a499-584a830662e8)

**Desktop (please complete the following information):**
 - OS: Windows 7 Professional 64Bit
 - Method of installation: Not required
 - Versio: Not required

**Additional context**
It was mentioned at the end of #366 to download from there, but the resource is no longer available

**Comment by docrR** [comment]
This may be of interest to you: https://github.com/docrR/ArmCord-Windows-7

It's based on the latest testing version of Supermium Electron 28 from win32, offshoot from the Supermium browser.

**Comment by dxomg** [comment]
Great!

**Comment by smartfrigde** [comment]
I moved Win7 builds to win7 branch with CI, now you can find E22 armcord builds here:
https://github.com/ArmCord/ArmCord/releases/tag/e22
