### ISSUE TITLE
Hex string being parsed in the window title

### ISSUE THREAD

**Issue by NSG650** [smartfrigde/armcord#494]
**Describe the bug**
Whenever you are in a group chat with the group name in the form of a hex string such as "\x41\x42", The hex string gets parsed, ie it shows up as "AB" in the window title and not "\x41\x42" which is seen in the normal client.

**To Reproduce**
1. Create Group Chat
2. Rename the Group Chat to a hex string such as "\x41"
3. The title bar or any other places where the window title is used shows "A" instead of "\x41"

**Expected behavior**
It should show "\x41" instead of parsing it and showing A.

**Screenshots**
![image](https://github.com/ArmCord/ArmCord/assets/51860844/a30733bd-a207-4eb5-af48-ad8c5ad7f53c)
![image](https://github.com/ArmCord/ArmCord/assets/51860844/e4dd62cc-7bc4-467c-8fc7-c7b783c0a323)

**Desktop (please complete the following information):**
 - OS: Any, Screenshot shown is of Linux but it works on other OS as well
 - Method of installation: AUR on Linux (armcord-bin). Used the releases installer for Windows.
 - Version: 3.2.5

**Comment by smartfrigde** [comment]
![image](https://github.com/user-attachments/assets/e5c4ab0f-f740-4222-aab3-f6d055a93514)
Can't reproduce on latest version, probably got fixed along the way
