### ISSUE TITLE
ArmCord AUR Packages won't start (blank screen)

### ISSUE THREAD

**Issue by liaminventions** [smartfrigde/armcord#495]
**Describe the bug**
When I install the `armcord`, `armcord-bin`, or `armcord-git` AUR package, it won't launch and shows a blank screen.
The Flatpak version seems to work though.

**To Reproduce**
1. Install any of the three packages, (`armcord`, `armcord-bin` or `armcord-git`) on an arch linux machine with `paru`
2. try to open armcord.

**Expected behavior**
ArmCord starts without a blank screen. 

**Screenshots**
![20231028-092055](https://github.com/ArmCord/ArmCord/assets/33787286/a1010445-0d0f-45d8-9660-325867ac1749)

**Desktop (please complete the following information):**
 - OS: Arch Linux x86_64 (6.5.9-zen2-1-zen)
 - Method of installation: aur
 - Version `3.2.5-2`, `r756.81273de-1`

**Additional context**
Logs from terminal (`armcord` command) :

[armcord.txt](https://github.com/ArmCord/ArmCord/files/13195879/armcord.txt)

**Comment by Nailington** [comment]
I have had this issue before.... Can you check the file `~/.config/ArmCord/storage/window.json` and check to see if an extra bracket is present? I remember that for some reason an extra bracket was in that file randomly, and produced that error and behavior.

**Comment by liaminventions** [comment]
> I have had this issue before.... Can you check the file `~/.config/ArmCord/storage/window.json` and check to see if an extra bracket is present? I remember that for some reason an extra bracket was in that file randomly, and produced that error and behavior.

Yes! That Fixed it!
I removed an extra bracket at the end.

(also tysm for the reply)

before:
```
{
    "width": 788,
    "height": 1032,
    "isMaximized": false,
    "x": 9,
    "y": 39
}
}
```

after:
```
{
    "width": 788,
    "height": 1032,
    "isMaximized": false,
    "x": 9,
    "y": 39
}
```

Anyone know why this was here?
(Is this a packaging problem?)

**Comment by liaminventions** [comment]
(oops i accidentally marked this as complete, we still need to find out what this came from)

**Comment by Nailington** [comment]
I have zero clue why that is an issue. I just know I have had it happen once in the past, and haven't had it happen again.

**Comment by TheM1Stery** [comment]
I had the same issue but in my case the window.json file was empty. Deleting it fixed it(it gets generated again after launch with correct values)

**Comment by KibSquib48** [comment]
I'm having a similar issue with the Flatpak on Fedora 39.
Here's my log from `flatpak run xyz.armcord.ArmCord`
```
Using Wayland, enabling PipeWire for video capture.
Screenshare may be broken on first start.
Make sure you have the legacy screencapturer enabled.
Wayland socket is available, running natively on Wayland.
To disable, remove the --socket=wayland permission.
Passing the following arguments to Electron: --enable-gpu-rasterization --enable-zero-copy --enable-gpu-compositing --enable-native-gpu-memory-buffers --enable-oop-rasterization --disable-gpu-blocklist --ozone-platform=wayland --enable-features=UseSkiaRenderer,WebRTCPipeWireCapturer,WebRTCPipeWireCapturer
[3:1114/150342.741576:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
Wayland detected, using PipeWire for video capture.
[Config manager] doneSetup: true
[Config manager] performanceMode: battery
ArmCord has been run before. Skipping setup.
Battery mode enabled
[Config manager] windowStyle: default
[3:1114/150343.335425:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:1114/150343.335479:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[Config manager] armcordCSP: true
[Config manager] doneSetup: true
[Config manager] customIcon: /app/bin/armcord/resources/app.asar/assets/desktop.png
Setting up CSP unstricter...
[Config manager] trayIcon: default
[Config manager] customIcon: /app/bin/armcord/resources/app.asar/assets/desktop.png
[Config manager] tray: false
[Config manager] skipSplash: false
[Config manager] tray: false
[Config manager] windowStyle: default
[Config manager] mods: vencord
[Config manager] noBundleUpdates: undefined
Downloading mod bundle
[Config manager] mods: vencord
https://github.com/Vendicated/Vencord/releases/download/devbuild/browser.js
[Mod loader] Loaded ArmCord Mod Loader made by Vendicated
(node:3) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at getWindowState (/app/bin/armcord/resources/app.asar/ts-out/utils.js:249:27)
    at createCustomWindow (/app/bin/armcord/resources/app.asar/ts-out/window.js:309:50)
    at init (/app/bin/armcord/resources/app.asar/ts-out/main.js:91:53)
    at async /app/bin/armcord/resources/app.asar/ts-out/main.js:106:9
(Use `armcord --trace-warnings ...` to show where the warning was created)
(node:3) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
[65:1114/150343.649961:ERROR:gbm_pixmap_wayland.cc(82)] Cannot create bo with format= YUV_420_BIPLANAR and usage=GPU_READ_CPU_READ_WRITE
WebContents #1 called ipcRenderer.sendSync() with 'modInstallState' channel without listeners.
WebContents #1 called ipcRenderer.sendSync() with 'get-app-version' channel without listeners.
Error occurred in handler for 'getLang': Error: No handler registered for 'getLang'
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:88753)
    at WebContents.emit (node:events:514:28)
Warning: vkCreateInstance: Found no drivers!
Warning: vkCreateInstance failed with VK_ERROR_INCOMPATIBLE_DRIVER
    at CheckVkSuccessImpl (../../third_party/dawn/src/dawn/native/vulkan/VulkanError.cpp:88)
    at CreateVkInstance (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:458)
    at Initialize (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:344)
    at Create (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:266)
    at operator() (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:521)
```

My window.json is empty

**Comment by TheM1Stery** [comment]
> e

I had the same issue, just delete the window.json file and it will work

**Comment by TheM1Stery** [comment]
> My window.json is empty

@KibSquib48 
I had the same issue, just delete the window.json and it well resolve itself(new correct window.json file will be generated by ArmCord).

**Comment by KibSquib48** [comment]
> > My window.json is empty
> 
> @KibSquib48 I had the same issue, just delete the window.json and it well resolve itself(new correct window.json file will be generated by ArmCord).

that worked, thank you!

**Comment by liaminventions** [comment]
this just started happening again, so I can't close this yet

it shows the discord loading screen and then becomes blank.

the command-line logs show
```
[43095:1226/084337.490455:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
```

![image](https://github.com/ArmCord/ArmCord/assets/33787286/4cff53e1-9847-4817-a2f7-132bfa763ff1)

I already removed my `window.json` file

**Comment by liaminventions** [comment]
UPDATE: I fixed it! the issue is that i was using the "electron" binary.

i fixed it by editing `/usr/bin/armcord` and changing `/usr/bin/electron` to `/usr/bin/electron27`.

![image](https://github.com/ArmCord/ArmCord/assets/33787286/e63b58ec-8d6d-4e7d-ab40-33ff03fe5af6)
