### ISSUE TITLE
Folder buttons in settings do nothing.

### ISSUE THREAD

**Issue by MagmaSlime123** [smartfrigde/armcord#497]
**Describe the bug**
Title. The themes, plugins, storage, and native crashes folders do not exist. I also have no idea where ArmCord stores itself since no folder exists.

**To Reproduce**
Install ArmCord, go into its settings, and try opening these folders.

**Expected behavior**
These buttons to open the expected folders.

**Desktop (please complete the following information):**
 - OS: Windows.
 - Method of installation Microsoft Store.
 - Version: 
![image](https://github.com/ArmCord/ArmCord/assets/51277766/fe614349-a323-4216-969e-8e32222b5081)

**Additional context**
It also seems the ArmCord version isn't displayed, thus I'm only able to use the tray icon.

**Comment by Ghostyface1337** [comment]
I'm pretty sure ArmCord is still bugged since discord pushed an update that broke it a few days ago, so plugins and themes dont work atm, but i think vencord is fixed
