### ISSUE TITLE
Are there any plans to implement screenshare audio?

### ISSUE THREAD

**Issue by sasspaper** [smartfrigde/armcord#498]
**Is your feature request related to a problem? Please describe.**
No audio during screensharing

**Describe the solution you'd like**
[Vesktop](https://github.com/edisionnano/Screenshare-with-audio-on-Discord-with-Linux) has already found a solution to this besides the discordscreen-audio app

**Describe alternatives you've considered**
Crying

**Comment by smartfrigde** [comment]
Duplicate of https://github.com/ArmCord/ArmCord/issues/435
