### ISSUE TITLE
Fails to launch if window.json is empty

### ISSUE THREAD

**Issue by TheSunCat** [smartfrigde/armcord#504]
**Describe the bug**
Somehow my `window.json` file in `storage` got saved as an empty file, and ArmCord would no longer run until I removed the file.

**To Reproduce**
1. Save `storage/window.json` as an empty file
2. Attempt to start ArmCord
3. Observe it fails to start

**Expected behavior**
ArmCord should gracefully handle this as if the file were missing.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Method of installation: aur
 - Version: r1001.19d02f6-1

**Additional context**
Relevant logs:
```js
[Mod loader] Loaded ArmCord Mod Loader made by Vendicated
(node:22736) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at getWindowState (/usr/share/armcord/app.asar/ts-out/utils.js:255:27)
    at createNativeWindow (/usr/share/armcord/app.asar/ts-out/window.js:331:50)
    at init (/usr/share/armcord/app.asar/ts-out/main.js:96:53)
    at async /usr/share/armcord/app.asar/ts-out/main.js:107:9
(Use `electron --trace-warnings ...` to show where the warning was created)
(node:22736) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```

**Comment by jade-tea-h** [comment]
I believe this is the same as #464, if a little more succinct

**Comment by TheSunCat** [comment]
Oop, you're right. I will close my issue then.
