### ISSUE TITLE
No rich presense on linux + wayland

### ISSUE THREAD

**Issue by Seme4eg** [smartfrigde/armcord#505]
I am using emacs with [elcord](https://github.com/Mstrodl/elcord), which allows me to connect to discord rpc and stream emacs events to it (and elcord reports to me that it does indeed connect to rpc). But i still don't see the any status/changes in my armcord profile. I created an [issue](https://github.com/Mstrodl/elcord/issues/90) in elcord repo, but it seems like its on your end (or arRPC's). Of course i did enable rpc in armcord settings.

OS: arch linux
Compositor: Hyprland

**Comment by dxcvvxd** [comment]
im having the same issue with literally almost everything except for osulazer which just works but everything else isnt even trying to display rpc

**Comment by Seme4eg** [comment]
well for me i wouldn't say "isn't trying", my elcord is connecting to something and even starts updates and sends events, they just don't appear in armcord

**Comment by xTrayambak** [comment]
Yep. Same. I don't get any RPC for Neovim, Emacs, Minecraft, or hell, anything for that matter. I checked Armcord's logs, and yes, arRPC does indeed start up.

**Comment by udaysinh-git** [comment]
Same here ! , rpc doesnt seem to work anymore it used to work when i first used armcord but it does not work for anything neither vscode nor minecraft

**Comment by xTrayambak** [comment]
I wrote a simple program to query arRPC on the port it reports it is running on and it returns empty data.

**Comment by Seme4eg** [comment]
Looking at armcord logs i see that after each message my emacs sends there is a reset event
![image](https://github.com/ArmCord/ArmCord/assets/24554850/08cfc78a-5081-4333-9c7d-cd9d42d30d0e)

**Comment by SeongGino** [comment]
Running into the same issue here, but not on Wayland (Kwin X11 user). It does generate the rich presence node in `/run/user/{id}/discord-ipc-0`, but rich presence data sent from apps (in my case through the Wine-Discord bridge) doesn't get displayed - but does on regular Discord.

I know that it *did* work in Armcord at some point, but it's been a while since I last checked admittedly...

Advise how to get those logs so I can be sure?

**Comment by xTrayambak** [comment]
![image](https://github.com/ArmCord/ArmCord/assets/59499552/41e03fdd-69b9-4f69-a44f-d09e90c4dac8)
I've seen this error constantly spammed in the terminal, is this related to the problem?

**Comment by ArjixWasTaken** [comment]
Can you try out my PR and see if it fixes the issue for you?

https://github.com/ArmCord/ArmCord/pull/531

I won't provide any build because you can't trust that the build I give you does not have a token logger.

(And you shouldn't trust strangers for builds)

**Comment by SeongGino** [comment]
@ArjixWasTaken Don't know what logs I'm supposed to be getting, but at least visually, no change using your repo (still nothing showing).

**Comment by ArjixWasTaken** [comment]
Is arRPC enabled in ArmCord's settings? (not vencord)

**Comment by SeongGino** [comment]
> Is arRPC enabled in ArmCord's settings? (not vencord)

Not using any client mods, but yes - and even re-toggled it off and on again just to be sure. Object still present in `/run/user/{userid}/discord-ipc-0`.

**Comment by Seme4eg** [comment]
Sorry it took me so long to test out your branch. Did a clean install, wiped all data, built from your branch. Still getting a reset after each rpc event.
![image](https://github.com/ArmCord/ArmCord/assets/24554850/be4bafb6-046f-44ff-b222-74fd1f7d7d83)

**Comment by liaminventions** [comment]
this is happening for me as well.

log:
```
[arRPC > ipc] new connection!
[arRPC > ipc] handshake: {
  client_id: '431179120836214795',
  nonce: '0ec850d9-0ada-44af-b01f-4750d3acdc83',
  v: 1
}
[arRPC > ipc] sending {
  cmd: 'DISPATCH',
  evt: 'READY',
  data: {
    v: 1,
    user: {
      id: '1045800378228281345',
      username: 'arRPC',
      discriminator: '0000',
      avatar: 'cfefa4d9839fb4bdf030f91c2a13e95c',
      flags: 0,
      premium_type: 0
    },
    config: {
      api_endpoint: '//discord.com/api',
      cdn_host: 'cdn.discordapp.com',
      environment: 'production'
    }
  }
}
[arRPC > ipc] message {
  cmd: 'SET_ACTIVITY',
  args: {
    pid: 12917,
    activity: {
      state: '4mat - Paper Dolls',
      details: 'Playing',
      timestamps: [Object]
    }
  },
  nonce: 'a667d355-13bd-437c-a8d4-de127b405ca5'
}
[arRPC > ipc] sending {
  cmd: 'SET_ACTIVITY',
  data: null,
  evt: null,
  nonce: 'a667d355-13bd-437c-a8d4-de127b405ca5'
}
[arRPC > ipc] socket closed false
```

here i am using https://github.com/Bond-009/cmus-discord-rpc to test

**Comment by smartfrigde** [comment]
Try 3.2.6

**Comment by Seme4eg** [comment]
Works, my emacs events are displaying \o/
