### ISSUE TITLE
Opening ArmCord from the tray icon reveals an error.

### ISSUE THREAD

**Issue by ninathedev** [smartfrigde/armcord#506]
**Describe the bug**
Attempting to show ArmCord by clicking on the tray icon reveals a JavaScript Error.

**To Reproduce**
1. Navigate to the tray icon.
2. Click on the tray icon/Right click then click on 'Open ArmCord'.
3. See error

**Expected behavior**
I expected to see the ArmCord window open.

**Screenshots**
![image](https://github.com/ArmCord/ArmCord/assets/145730763/81537320-f3e5-405a-95ef-98decb43f4b2)

**Desktop (please complete the following information):**
 - OS: Windows
 - Method of installation: Microsoft Store
 - Version 3.3.0

**Additional context**
It happens even if I relaunch it.

**Comment by ghost** [comment]
Hello, please see #513 (also, try to remove `window.json` if it's already empty).

**Comment by smartfrigde** [comment]
Try 3.2.6
