### ISSUE TITLE
Themes not working

### ISSUE THREAD

**Issue by cynlik** [smartfrigde/armcord#510]
**Describe the bug**
If I reinstall themes will work for a while but next day it will stop working.
No themes will load after this bug happens.

**To Reproduce**
It just sorf of happens. 

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 23.10
 - Method of installation: sudo apt install
 - Version: 3.2.5

**Comment by smartfrigde** [comment]
Please try latest ArmCord version, we've rewritten the theme loader
