### ISSUE TITLE
Can't edit streaming resolution

### ISSUE THREAD

**Issue by Francesco146** [smartfrigde/armcord#511]
**Describe the bug**
I can't config the screen share resolution, it always auto-select the 720p-30fps

**To Reproduce**
1. Go to a voice channel
2. Screen share

**Expected behavior**
When you select the window to share, it should give you the option to select also the quality of the stream.

**Screenshots**
<img width="363" alt="image" src="https://github.com/ArmCord/ArmCord/assets/49027005/7292a59c-14f7-4902-b9d4-9b34f65c5597">

**Desktop (please complete the following information):**
 - OS: macOS Sonoma 14.1
 - DMG
 - 3.2.5

**Comment by SVENDEMAN100** [comment]
Why is this not resolved yet?

**Comment by Vendicated** [comment]
because you haven't opened a pull request to fix it yet.

**Comment by Chaython** [comment]
The issue is Armcord is really just like running discord in a chromium web browser w/ vencord plugin installed.
It uses the hangouts screensharing api, not discord's own screensharing.

**Comment by Francesco146** [comment]
it's still occurring at the version 3.2.6

**Comment by smartfrigde** [comment]
I've wrote a small Shelter plugin that allows you to change screenshare quality and patches the bitrate (so it's not pixelated/laggy etc).

Steps:
1. Enable Shelter from the mods list in ArmCord settings (you might need to restart 2 times for it to appear)
2. Add the plugin using this url `https://armcord.github.io/shelter-plugins/screenshareQualityFix/`
3. Set the quality in the plugin settings, see screenshot below
4. Test with your friend and share the results here or in our [Discord server](https://discord.gg/A2PUsMTbmN)
