### ISSUE TITLE
opensuse package

### ISSUE THREAD

**Issue by Redhawk18** [smartfrigde/armcord#516]
I'd like to ask for a opensuse package, or repo.

**Comment by Redhawk18** [comment]
and any work done to package to rpm could also be done for fedora users as well

**Comment by Redhawk18** [comment]
and any work done to package to rpm could also be done for fedora users as well

**Comment by orowith2os** [comment]
Any Fedora packages would have to reside in, or rely on, RPMFusion, as Fedora's legal guidelines don't allow Electron (well, a dependency of Electron) to be shipped. 

Is there a particular reason why Flatpak would not work for your use case?

**Comment by Redhawk18** [comment]
> Any Fedora packages would have to reside in, or rely on, RPMFusion, as Fedora's legal guidelines don't allow Electron (well, a dependency of Electron) to be shipped.
> 
> Is there a particular reason why Flatpak would not work for your use case?

In the past I remember the official discord flatpak had problems, but I can't really remember what they were.

**Comment by orowith2os** [comment]
The Discord Flatpak is not the same as the ArmCord Flatpak - and many issues you're likely to come across are either easily solvable or due to old Electron versions.

Even Discord is officially supporting their Flatpak now, so I'd expect the situation to improve there too.
