### ISSUE TITLE
apt repo down

### ISSUE THREAD

**Issue by dj1ch** [smartfrigde/armcord#519]
**Describe the bug**
as i update the repositories on my machine, i get updates as normal, however the armcord repo doesn't seem to work. I get this error: 

`E: Failed to fetch https://eu.armcord.app/apt-repo/dists/stable/InRelease  523   [IP: 172.67.162.38 443]`
`E: The repository 'https://eu.armcord.app/apt-repo stable InRelease' is no longer signed.`

this essentially means that it cannot reach the repo. if i attempt to visit the repo link, it leads to a cloudflare page telling me the host is down.

**To Reproduce**
1. open terminal
2. run `sudo apt update`

**Expected behavior**
to update/refresh repositories normally, along with being able to update normally.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Linux(debian)]
 - Method of installation [by apt repository]
 - Version [latest stable]

**Additional context**
it seems like this just started happening. i was just able to update from the repository a couple days ago.

**Comment by dj1ch** [comment]
i just recently switched linux distros, not sure if we should close this now?

**Comment by orowith2os** [comment]
You not being affected by the problem because you completely stepped around it does not mean others will not come across it. You might as well be walking over a wet spot on a floor and leaving it open for someone else to slip on.

**Comment by NotQuiteApex** [comment]
+1'ing, I am still having issues. It appears to be giving 523 HTTP errors, so it's just something on their end failing.

**Comment by dj1ch** [comment]
> You not being affected by the problem because you completely stepped around it does not mean others will not come across it. You might as well be walking over a wet spot on a floor and leaving it open for someone else to slip on.

i never closed the issue, as other people seem to have this issue. the reason i switched distros was not because of this problem.

**Comment by sabrehagen** [comment]
Also experiencing, my builld is blocked on this.

**Comment by RogueRaiden** [comment]
yeah mistakenly tried to follow the terminal based install, it couldn't find it and now every time i open Discover i get this 

E: Failed to fetch https://eu.armcord.app/apt-repo/dists/stable/InRelease  523   [IP: 104.21.15.99 443]
E: The repository 'https://eu.armcord.app/apt-repo stable InRelease' is not signed.
W: Updating from such a repository can't be done securely, and is therefore disabled by default.
W: See apt-secure(8) manpage for repository creation and user configuration details.
E: https://eu.armcord.app/apt-repo stable InRelease is not (yet) available (523   [IP: 104.21.15.99 443])

don't know how to get rid of the message now

installed Armcord through a different method and it doesn't even stream Discord audio anyway lol

**Comment by Davilarek** [comment]
```sh
sudo rm /etc/apt/sources.list.d/armcord.list
sudo apt update
```
should help

**Comment by codingnooob** [comment]
It's a server-side issue, pinging the server returns errors 523 (network unreachable) and/or 301 (moved permanently) per [this](https://discord.com/channels/820732039253852171/1174603591076548729) thread on the discord channel.

Just to show that it's down for everyone:
https://www.isitdownrightnow.com/eu.armcord.app.html
https://downinspector.com/check/eu.armcord.app

**Comment by codingnooob** [comment]
![Screenshot from 2023-11-29 16-27-48](https://github.com/ArmCord/ArmCord/assets/66186626/a3b59123-522d-4286-82bc-d1274759e9cd)

**Comment by dj1ch** [comment]
> ![Screenshot from 2023-11-29 16-27-48](https://private-user-images.githubusercontent.com/66186626/286778663-a3b59123-522d-4286-82bc-d1274759e9cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzODYxNTcsIm5iZiI6MTcwMTM4NTg1NywicGF0aCI6Ii82NjE4NjYyNi8yODY3Nzg2NjMtYTNiNTkxMjMtNTIyZC00Mjg2LTgyYmMtZDEyNzQ3NTllOWNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDIzMTA1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmY2M2YjdlM2EwODE2ZGViYWQ1NjU3YTAyNjc5YWJkMGUzMjg5YmU2YjI2NWY2NGU0NDM3MGNlYTI1ZGMyYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YDepMVVi99MZzmPHE7Sx6iwtjsPVPLz4kaouFJJqTQE)

makes sense. thank you

**Comment by codingnooob** [comment]
> > ![Screenshot from 2023-11-29 16-27-48](https://private-user-images.githubusercontent.com/66186626/286778663-a3b59123-522d-4286-82bc-d1274759e9cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzODYxNTcsIm5iZiI6MTcwMTM4NTg1NywicGF0aCI6Ii82NjE4NjYyNi8yODY3Nzg2NjMtYTNiNTkxMjMtNTIyZC00Mjg2LTgyYmMtZDEyNzQ3NTllOWNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDIzMTA1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmY2M2YjdlM2EwODE2ZGViYWQ1NjU3YTAyNjc5YWJkMGUzMjg5YmU2YjI2NWY2NGU0NDM3MGNlYTI1ZGMyYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YDepMVVi99MZzmPHE7Sx6iwtjsPVPLz4kaouFJJqTQE)
> 
> makes sense. thank you

No problem 👍

**Comment by whitehatblackcoffee** [comment]
Running 'curl -fsSL https://eu.armcord.app/pgp-key.public | sudo gpg --dearmor -o /usr/share/keyrings/armcord.gpg' gives 'curl: (22) The requested URL returned error: 523'

**Comment by dj1ch** [comment]
> Running 'curl -fsSL https://eu.armcord.app/pgp-key.public | sudo gpg --dearmor -o /usr/share/keyrings/armcord.gpg' gives 'curl: (22) The requested URL returned error: 523'


yeah, the repo is down for the most part, we just need to wait on the developers to fix everything. won't close the issue tho.

**Comment by smartfrigde** [comment]
Check readme for new apt server and instructions on how to remove the old one, sorry for inconvenience!
