### ISSUE TITLE
Discord aRPC not detecting anything

### ISSUE THREAD

**Issue by AveryX01** [smartfrigde/armcord#520]
Bug Description: As the title suggests, my ArmCord doesn't detect anything. 

Reproduction Steps: I'm not sure what caused this, the first few weeks I used to use ArmCord it used to work perfectly but just the last week or so I've noticed that it just doesn't detect anything anymore.  I've tried re-installing ArmCord, deleting the discord and ArmCord directories and trying to install and re-install yet nothing seems to work?

Platform: Windows 11

Screenshot 1 & 2 (Showing plugin enabled)
Screenshot 3 (arRPC not detecting anything despite supported game being open)
![image](https://github.com/ArmCord/ArmCord/assets/86320597/7f7f7a86-91de-4c1b-9569-f3d1f72fa827)
![image](https://github.com/ArmCord/ArmCord/assets/86320597/83a28fde-8da1-4d31-a856-afd7ef9565cb)
![image](https://github.com/ArmCord/ArmCord/assets/86320597/238c6d88-8b14-4e30-b3bd-d2d8fef90923)

Pardon me if this is something I should've posted on the arRPC github but it specifically says on there that ArmCord has the plugin built in so it should just work directly off this.

**Comment by dxcvvxd** [comment]
having the same issues here on linux, regardless of the build and version im using
