### ISSUE TITLE
Notifications not working under Windows 10 LTSB 2016 (1607)

### ISSUE THREAD

**Issue by vbedesu** [smartfrigde/armcord#523]
**Describe the bug**
The notifications are not working for Windows 10 LTSB 2016 (1607), when I get notified or someone sends me messages I hear a ping sound, but not a notification. I'm on Online Mode and not on Do Not Disturb.

**To Reproduce**
1. Install ArmCord on Windows 10 2016 LTSB
2. Open ArmCord, Log In
3. Go to Settings, click Notifications, Enable Desktop Notifications
4. No notifications at all.

**Expected behavior**
Notifications should be working.

**Screenshots**
![image](https://github.com/ArmCord/ArmCord/assets/99480390/c6d079b7-cef8-490e-b471-476a4fd373dc)

**Desktop (please complete the following information):**
 - OS: Windows 10 LTSB 2016 (1607) NT 10.0.14393
 - Method of installation [EXE]
 - Version [3.2.5]

**Comment by smartfrigde** [comment]
Can you reproduce this on latest version?
