### ISSUE TITLE
Package for Apple Silicon does not work

### ISSUE THREAD

**Issue by bachrc** [smartfrigde/armcord#524]
**Describe the bug**
Installing the package, either arm64-mac dmg or zip, does not produce a usable app, and MacOS says the app isn't functionning, and should go to trash

**To Reproduce**
1. Download a arm64 release on Macbook M3
2. Install it/Move it to the application folder
3. MacOS says it belongs to the trash

**Comment by Git-North** [comment]
xattr -cr /path/to/application.app

**Comment by bachrc** [comment]
The error message still appeared, but when restarting it, it seems like it works! Thanks!
