### ISSUE TITLE
Microsoft Store page is gone

### ISSUE THREAD

**Issue by diskscape** [smartfrigde/armcord#529]
**Describe the bug**
ArmCord is missing from the Microsoft Store. The link in the Github page redirects to an error message saying "We are sorry, the page you requested cannot be found.
The URL may be misspelled or the page you're looking for is no longer available."

**To Reproduce**
1. Go to readme.md
2. Scroll down to 'How to run/install it?'
3. Click on 'Get it from Microsoft'

**Expected behavior**
A download page on the Microsoft Store, allowing the user to download the app on a local Windows machine and view app reviews and info.

**Screenshots**
![image](https://github.com/ArmCord/ArmCord/assets/39781374/74d28687-cebb-4556-bd8c-ef1969a83630)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Method of installation: Microsoft Store
 - Version [e.g. 3.0.7]: N/A

**Additional context**
A few weeks ago, it would not come up in Microsoft Store search results but could be downloaded if the user had already done so with their account.

**Comment by SomeAspy** [comment]
https://github.com/microsoft/winget-pkgs/pull/167164

**Comment by SomeAspy** [comment]
that was winget, my bad

**Comment by smartfrigde** [comment]
Currently fighting with Microsoft with their broken certification system, I'll update when we pass it

**Comment by smartfrigde** [comment]
https://apps.microsoft.com/store/detail/9PFHLJFD7KJT?cid=DevShareMCLPCB

ArmCord should be available again on Microsoft Store in few hours!
