### ISSUE TITLE
[dev] pnpm install fails on node v20

### ISSUE THREAD

**Issue by markfswe** [smartfrigde/armcord#535]
See https://github.com/pnpm/pnpm/issues/6424

Please either upgrade pnpm & pnpm-lock or set up proper semver for nodejs in package.json, because >= 18 is not correct, as 20 is not supported by current project.

**Comment by cappscolton** [comment]
This is an issue for me using corepack and armcord-git from AUR.
Bumping pnpm to 8.14.1 (latest) fixed the build/install for me.
Thoughts on bumping pnpm?

**Comment by smartfrigde** [comment]
Please see if it works now

**Comment by markfswe** [comment]
Fixed in https://github.com/ArmCord/ArmCord/commit/8a0585d18130042737da96b85cdb399de35f9cd6
