### ISSUE TITLE
Client Spontaneously Broke on RPI 5

### ISSUE THREAD

**Issue by UrkiMimi** [smartfrigde/armcord#539]
**Describe the bug**
The bug makes the app unusable since it won't launch. It will stay at a grey window for a minute, then it switches to the Discord loading animation with no text below it.

**To Reproduce**
1. Just open the app.

**Expected behavior**
I expected the app to open properly with no fuss and open the main discord page.

**Screenshots**
![Screenshot from 2023-12-27 21-17-15](https://github.com/ArmCord/ArmCord/assets/74517821/eb15d1aa-3260-4ef9-b492-81665ce6e75a)

**Desktop (please complete the following information):**
 - OS: Ubuntu 23.10 arm64
 - Method of installation .deb from Github releases
 - Version 3.2.5

**Additional context**
I'm not sure how it broke but it stopped working after I did an update to my system.

**Comment by UrkiMimi** [comment]
I forgot to attach the terminal log that I got from this so here it is. 
[armcordlog.txt](https://github.com/ArmCord/ArmCord/files/13783042/armcordlog.txt)

**Comment by UrkiMimi** [comment]
I got it to work again by deleting the ArmCord config but I'm keeping this issue up cause I still think this is a bug

**Comment by ghost** [comment]
Hello, 
I'm facing the same issue about this snippet:

`(node:13003) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)`
    `at getWindowState (/opt/ArmCord/resources/app.asar/ts-out/utils.js:249:27)`
    `at createCustomWindow (/opt/ArmCord/resources/app.asar/ts-out/window.js:309:50)`
    `at init (/opt/ArmCord/resources/app.asar/ts-out/main.js:91:53)`
    `at async /opt/ArmCord/resources/app.asar/ts-out/main.js:106:9`.

I was able to trace it back thanks to the web application's console:
`Uncaught (in promise) Error: Error invoking remote method 'getLang': Error: No handler registered for 'getLang'`.

This points to 'splash.html':

    <body>
        <div class="container">
            <video autoplay loop class="logo" id="splashscreen-armcord">
                <source src="https://armcord.app/discord_loading.webm" type="video/webm" />
            </video>
            <p id="text-splashscreen"></p>
        </div>
    </body>
    <script>
        async function loadLang() {
            const text = document.getElementById("text-splashscreen");
            if (window.navigator.onLine === false) {
                text.innerHTML = await internal.getLang("loading_screen_offline");
            } else {
                text.innerHTML = await internal.getLang("loading_screen_start");
                if (window.internal.version === "3.3.0") {
                    console.log("Running a development build of ArmCord. Skipping updater.");
                } else {
                    const response = await fetch("https://armcord.app/latest.json");
                    const data = await response.json();
                    if (data.version !== window.internal.version) {
                        var elem = document.createElement("img");
                        elem.classList.add("logo");
                        elem.src = "https://armcord.app/update.webp";
                        document.body.prepend(elem);
                        document.getElementById("splashscreen-armcord").remove();
                        text.innerHTML = await internal.getLang("loading_screen_update");
                    } else {
                        console.log("ArmCord is up to date.");
                    }
                }

                function check() {
                    if (internal.installState === "installing") {
                        text.innerHTML = "Installing mods";
                    } else if (internal.installState === "done") {
                        return true;
                    } else if (internal.installState === "modDownload") {
                        text.innerHTML = "Updating " + armcord.mods;
                    } else if (internal.installState === "none") {
                        text.innerHTML = "Nothing to install.";
                        return true;
                    } else {
                        return true;
                    }
                }

                while (check() === false) await new Promise((r) => setTimeout(r, 10));
                setTimeout(() => {
                    window.internal.splashEnd();
                }, 3000);
            }
        }

        loadLang();
    </script>
</html>

Thus, loadLang() is at fault and I'm trying to fix it (mine is located in /usr/lib/armcord/app.asar at line 2334).

P.S.
After reading https://github.com/ArmCord/ArmCord/issues/513 I'm not sure anymore about what I just wrote above here, by which I mean that it could be actually an error generated due to the bad configuration file and not malfunctioning code.

**Comment by smartfrigde** [comment]
Should work in 3.2.6
