### ISSUE TITLE
ArmCord breaks under Electron v28.1.1

### ISSUE THREAD

**Issue by s-liwka** [smartfrigde/armcord#540]
**Describe the bug**
After updating electron to v28.1.1 armcord no longer launches properly, instead it's stuck on a gray screen. Log: https://pastebin.com/VS8iFUDr

**To Reproduce**
1. Install Electron v28.1.1
2. Launch armcord

**Screenshots**
![image](https://github.com/ArmCord/ArmCord/assets/116428267/db36a1ca-b68b-4f20-88f5-59702a99aac2)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Method of installation: chaotic-aur
 - Version: r1016.f678b7f-1
 
 EDIT: I know about #534 but i am neither running nvidia nor wayland

**Comment by s-liwka** [comment]
Same under 28.1.0
Downgraded 27.2.1-1 and armcord works fine

**Comment by UQuark** [comment]
A small workaround that does not require downgrade (Arch):
1. Install Electron 27:  `pacman -S electron27`
2. Edit `/usr/bin/armcord`, changing electron executable:
```
#!/bin/sh

electron=/usr/bin/electron27 <--- HERE
```
3. Kill all ArmCord instances and launch again.

**Comment by Jaoheah** [comment]
> A small workaround that does not require downgrade (Arch):
> 
>     1. Install Electron 27:  `pacman -S electron27`
> 
>     2. Edit `/usr/bin/armcord`, changing electron executable:
> 
> 
> ```
> #!/bin/sh
> 
> electron=/usr/bin/electron27 <--- HERE
> ```
> 
>     3. Kill all ArmCord instances and launch again.

This works.

**Comment by smartfrigde** [comment]
Fixed in 3.2.6
