### ISSUE TITLE
MacOS titlebar broken

### ISSUE THREAD

**Issue by JibbityJobbity** [smartfrigde/armcord#542]
# Describe the bug
On MacOS, the titlebar doesn't seem to be configured properly. I see the close/maximise/minimise buttons overlapping the Discord logo and trying to drag the window by the title bar only really seems to work some of the time.

The problem doesn't seem to magically fix itself when I play around with it.

I freshly installed the application and signed in with no prior vencord/armcord configuration present in the system.

# To Reproduce
This is visible upon opening the app and being signed in.

# Expected behavior
See screenshot

# Screenshots
## ArmCord:
![Screenshot 2024-01-13 at 1 54 30 PM](https://github.com/ArmCord/ArmCord/assets/37820565/197a1e02-c052-4aa1-b66b-2e9706ccd277)

## Discord:
![Screenshot 2024-01-13 at 1 55 26 PM](https://github.com/ArmCord/ArmCord/assets/37820565/809a7fbf-9ebc-444f-9b98-1f5f1cc01226)

**Desktop (please complete the following information):**
 - OS: MacOS 14.2.1
 - Install method: dmg
 - ArmCord version: 3.2.5

**Comment by smartfrigde** [comment]
Fixed in 3.2.6

**Comment by JibbityJobbity** [comment]
Fixed on my end. Thanks!
