### ISSUE TITLE
Failed to render the Plugins and Themes tabs for Vencord

### ISSUE THREAD

**Issue by Anomalocaridid** [smartfrigde/armcord#543]
**Describe the bug**
When I try to access the Plugins and Themes tabs for Vencord, I just get an error saying "Failed to render the Plugins/Themes tab."

**To Reproduce**
1. On a fresh install of ArmCord, select Vencord in the installer and then log in.
2. Attempt to access Vencord's Plugins and Themes tabs
3. Each of them should have just a box with an error in them.

**Expected behavior**
I expected that the tabs would display their respective settings rather than fail to render

**Screenshots**
![Plugins tab error](https://github.com/ArmCord/ArmCord/assets/29845794/31ca1b87-90bf-4a39-92ba-da28dae7ac07)
![Themes tab error](https://github.com/ArmCord/ArmCord/assets/29845794/95385f0a-5835-4ff9-950e-e8581f1c4fc1)

**Desktop (please complete the following information):**
 - OS: NixOS unstable (Linux)
 - Method of installation: nixpkgs unstable
 - Version 3.2.5

**Additional context**
I also do not see the ArmCord settings in the Discord settings, although I can open them by clicking the tray icon.

**Comment by smartfrigde** [comment]
Vencord bug
