### ISSUE TITLE
Ability to skip "you appear to be offline" screen.

### ISSUE THREAD

**Issue by FurblandChannel** [smartfrigde/armcord#544]
**Is your feature request related to a problem? Please describe.**
I use a weird DNS server (it's my ISP's fault) that sometimes replaces the server Windows uses for "online detection" with its own page that doesn't match the proper contents that Windows expects to see. Many apps, including ArmCord, rely on this method to detect whether the user is online. Whenever this happens and I attempt to start ArmCord, it falsely detects my computer as being offline, and I must wait until my ISP stops screwing with my internet to start ArmCord again.

**Describe the solution you'd like**
Some sort of "Start anyway" button on the offline error screen or an option in settings labeled "Bypass internet check" or something similar

Thanks!

**Comment by smartfrigde** [comment]
https://github.com/ArmCord/ArmCord/commit/2d2181fae217938f2ea67d4281ede674920bb088
