### ISSUE TITLE
aRPC not working

### ISSUE THREAD

**Issue by HeadedBranch** [smartfrigde/armcord#552]
**Describe the bug**
The aRPC isn't detecting my games

**To Reproduce**
1. Launch ArmCord
2. open game with RPC e.g Celeste
3. it doesn't appear as status

**Expected behavior**
Celeste to appear as status

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Method of installation setup exe
 - Version 3.2.6

**Additional context**
Doesnt work for any games

**Comment by notboeing747** [comment]
I have been having this issue too, it detected Valorant for a split second the moment I closed it however aside from that I can't seem to get it to detect other games.

**Comment by Nikodemsky** [comment]
Same issue here, aRPC is not detecting any of the Steam games.

**Comment by Benjaneb** [comment]
I'm on Linux and it works for some programs, like vscode, but not Steam games or Minecraft.

**Comment by water-sucks** [comment]
Same with me, it works for `tidal-hifi` but it does not work with Neovim or some of my games, i.e. plugins like `andweeb/presence.nvim`.

**Comment by solitonmedic** [comment]
This is also happening me, but on Linux and with the Dolphin Emulator.

**Comment by BluePurplePro** [comment]
Adding custom games/programs on aRPC is needed at this point

**Comment by genderneutralnoun** [comment]
I'm on Linux (Ubuntu) with native Armcord and no games are showing up in my status at all.

**Comment by HeadedBranch** [comment]
Somehow, it does detect minecraft but no other things on my computer are detected and shown

17 Apr 2024 21:59:19 genderneutralnoun ***@***.***>:

**Comment by smartfrigde** [comment]
Can you retest on 3.2.7? It has updated arRPC

**Comment by Nikodemsky** [comment]
Even before starting Steam it shows, that i'm playing Minecraft - tho i have never installed, nor played Minecraft.

Tried running FF7:R - it still shows Minecraft. For me it's still bugged.

**Comment by theofficialgman** [comment]
same issue here

vscode rpc extension shows it is connected to "armcord" and disconnects when "armcord" is closed. so seems to be on arRPC's end

**Comment by smartfrigde** [comment]
Temporary fix: https://github.com/ArmCord/ArmCord/issues/641#issuecomment-2191952118

**Comment by cantalupo555** [comment]
I've tried everything and Rich presence doesn't work.

**Comment by SomeAspy** [comment]
@cantalupo555 please ensure you are on the latest dev build of armcord at https://github.com/ArmCord/ArmCord/releases/tag/devbuild

**Comment by cantalupo555** [comment]
> @cantalupo555 please ensure you are on the latest dev build of armcord at https://github.com/ArmCord/ArmCord/releases/tag/devbuild

![image](https://github.com/user-attachments/assets/0a56a0e6-b66c-4bdc-9f53-19a6a62659ed)

I tested the version
armcord-3.3.0-arm64.zip and it still doesn't work.

**Comment by smartfrigde** [comment]
Can people still affected by this on devbuilds join our Discord server so we can sort things out?

https://discord.gg/Xm9yxzYD

I've made a thread in the dev build bugs forum, please provide logs of you running ArmCord from terminal there

**Comment by smartfrigde** [comment]
Try 3.2.8

**Comment by cantalupo555** [comment]
> Try 3.2.8

Resolved
![image](https://github.com/user-attachments/assets/699d00dc-1f69-4bfd-941a-61db26ba07cd)
