### ISSUE TITLE
If the app is started when network is down, it will never recover

### ISSUE THREAD

**Issue by haael** [smartfrigde/armcord#555]
**Describe the bug**
If the app is started when network is down, it will display the message "unable to load modules" and then it will be stuck in error state even if the network is restored later. This makes it pointless to start ArmCord at boot time, since it needs to be turned off and on anyway.

**To Reproduce**
Disable network, start ArmCord, enable network.

**Expected behavior**
Recover automatically when network is restored.

**Screenshots**

**Desktop (please complete the following information):**
Linux, Ubuntu Lunar 23.04

**Additional context**

**Comment by SomeAspy** [comment]
Should be fixed by 5690fe1b973bc56cbd145e34b6a5dcca95892ed8
