### ISSUE TITLE
Window title missing on Windows

### ISSUE THREAD

**Issue by VioletGiraffe** [smartfrigde/armcord#556]
I regularly get a window without the title bar on Windows (Win 10, now upgraded to 11, still happens). It seems random but happens very often. So I cannot move nor resize the window.

![image](https://github.com/ArmCord/ArmCord/assets/1175926/b8fd583d-5ff4-4090-a157-90df47cf8199)

**Comment by Pepeshki** [comment]
When you upgraded to windows 11 did you do a full reset or just an upgrade from 10?

**Comment by VioletGiraffe** [comment]
Just an upgrade, but as I said, the problem appeared in Win 10 and persisted into 11, it's not related to the upgrade.

**Comment by Aurum490** [comment]
I've also got this same issue every now and then.

**Comment by VioletGiraffe** [comment]
I have changed something in the settings and it no longer happens. Possibly after activating "Skip splash screen".

**Comment by BluePurplePro** [comment]
Change Armcord theme to Native ~> Restart App
![untitled](https://github.com/ArmCord/ArmCord/assets/84092284/6a166df8-0ab0-4bc4-b66d-0eeeb861f014)

**Comment by VioletGiraffe** [comment]
Was fine for a month, but now 2nd day in a row no title.

**Comment by smartfrigde** [comment]
Can you recheck using a [devbuild](https://github.com/ArmCord/ArmCord/releases/tag/devbuild)?
