### ISSUE TITLE
Users watching my stream experience it in extremely low framerate

### ISSUE THREAD

**Issue by sidoka-contact** [smartfrigde/armcord#557]
I am trying to stream a game using ArmCord, and other users (both official client and ArmCord users) experience my stream in extremely low framerate, 1 fps or even lower.

When starting the stream, both ArmCord and the game run at stable 60 fps, and looking at my own stream, I can see it running at 30 fps, which is expected. But any other user watching my stream report extremely low framerate.

I do not think this is a hardware issue, nor is it an internet connection issue.
I have tried streaming using official client, and it resulted in expected behavior, all the users reported stable 30 fps.
I have tried streaming using BetterDiscord with the YABDP4Nitro plugin, and all the users reported ~60 fps.
Which means my machine is 100% capable of streaming at least in 30 fps.

Here's a video my friend recorded of my stream from their perspective: [video link](https://cdn.discordapp.com/attachments/1206954778681409538/1210918254663573504/Cbljrf_lodx.mov?ex=6607fe01&is=65f58901&hm=24fa2394c69779665dfbfe7b8e810c5e080521ccd6db4d5c1a1a6c23679adf66&) (note the game's framerate, avg. 80 fps)

I also asked my friend to install ArmCord and try streaming. They experienced the exact same issue as me, described above.

What I have attempted to fix the issue:
- try various performance modes
  - both of the modes did not make a difference.
- try various electron/chromium/js flags
  - `--ignore-gpu-blocklist --enable-gpu-rasterization --enable-zero-copy --force_high_performance_gpu --js-flags="--max_old_space_size=3999" --max_old_space_size=3999 --webrtc-max-cpu-consumption-percentage=100 --enable-features=VaapiIgnoreDriverChecks,VaapiVideoEncoder,VaapiVideoDecoder,CanvasOopRasterization,UseMultiPlaneFormatForHardwareVideo`
Did not help.

System info:
- OS: Windows 10, build 22H2
- Installed ArmCord using the "Actions" dev build ArmCordWindows.zip archive.
- ArmCord version: "3.3.0" (dev build # 423)

**Comment by kejioz** [comment]
same thing happening to me

**Comment by smartfrigde** [comment]
I've wrote a small Shelter plugin that allows you to change screenshare quality and patches the bitrate (so it's not pixelated/laggy etc).

Steps:
1. Enable Shelter from the mods list in ArmCord settings (you might need to restart 2 times for it to appear)
2. Add the plugin using this url `https://armcord.github.io/shelter-plugins/screenshareQualityFix/`
3. Set the quality in the plugin settings, see screenshot below
4. Test with your friend and share the results here or in our [Discord server](https://discord.gg/A2PUsMTbmN)

**Comment by SomeAspy** [comment]
feel free to re-open the issue if the plugin does not resolve this!

**Comment by anon88391** [comment]
I am currently experiencing the very same issue as OP using the latest Legcord. I am unable to find the plugin that is supposed to fix it anywhere.

**Comment by oldairokunomega** [comment]
reopening, same issue, they say it is "1 frame per cardi drop"

**Comment by EmersonBiggons** [comment]
> I am currently experiencing the very same issue as OP using the latest Legcord. I am unable to find the plugin that is supposed to fix it anywhere.

Here is on I found that's relatively new. Test if it helps [BetterScreenshareFix](https://shelter.xirreal.dev/betterScreenshareFix/)

**Comment by Kimisen-K** [comment]
Neither of the plugins worked, same issue.

**Comment by EmersonBiggons** [comment]
> Neither of the plugins worked, same issue.

I moved back to Vesktop, I don't know what they do differently but it works perfectly on all fronts. It'd be work investigating where that performance is being lost in Legcord.
