### ISSUE TITLE
No settings button on mobile ui

### ISSUE THREAD

**Issue by GeoNew2011** [smartfrigde/armcord#558]
I'm on phone but used proot to launch Linux I toggled mobile ui and cannot turn it off
**To Reproduce**
Toggle mobile ui
**Expected behavior**
Reinstall reset all

**Screenshots**
![Screenshot_20240326_134103_RVNC Viewer](https://github.com/ArmCord/ArmCord/assets/152255543/cb612388-45f1-4f08-9654-2a433e5573e3)

**Desktop**
 - OS: Debian aarch64
 - Method of installation apt install ./armcord.deb
 - Version 3.2.6

**Additional context**
Add reset button

**Comment by smartfrigde** [comment]
![obraz](https://github.com/ArmCord/ArmCord/assets/37928912/fa11dbfa-a5e8-49c5-acba-15e1bf75924e)
You need to click these three lines and there will be a settings cog on the bottom of your screen. I also recommend using native titlebar if you want to use mobile ui
