### ISSUE TITLE
ArmCord couldn't install internal mod loader, please check if you have stable internet connection and restart the app.

### ISSUE THREAD

**Issue by Pohie** [smartfrigde/armcord#561]
It shows the error message, but the app stays open and says "Starting Armcord". I have to force close it to get out of it. It says this every time I open it, even after I reinstalled it.

(I'm using apple silicon)

![Screenshot 2024-04-01 at 4 18 01 PM](https://github.com/ArmCord/ArmCord/assets/156468404/1afb6705-25f7-461b-8398-6be689b455fc)
![Screenshot 2024-04-01 at 4 18 14 PM](https://github.com/ArmCord/ArmCord/assets/156468404/c5628403-3983-45d2-bc01-863db2f3d2e5)

**Comment by altacountbabi** [comment]
Same issue on arch linux.

**Comment by ThoriumTextile** [comment]
This happens only when autostarting. Launching manually works fine for me. Bit annoying but apparently (read it on the armcord discord) if you setup a launch script instead of using a .desktop file, you can tell it to wait before launching so that it properly detects the internet connection.

**Comment by SomeAspy** [comment]
This should be fixed in the 5690fe1b973bc56cbd145e34b6a5dcca95892ed8, instead of halting the entire process it should just continue without loading mods now. Let me know if you have this issue still!
