### ISSUE TITLE
Custom CSS seemingly crashed Vencord, Vencord no longer loads 

### ISSUE THREAD

**Issue by I2pRandom** [smartfrigde/armcord#563]
**Describe the bug**
Upon loading the CSS to block discords attempt to force the new TOS down my throat via custom CSS.
Vencord then crashes and will no longer load

**To Reproduce**
Load the Custom CSS 
```css
.layerContainer_a2fcaa, .layerContainer_a2fcaa * {
    display: none !important;
}
```
 
**Expected behavior**
CSS prevents layer container a2fcaa from loading, blocking discords attempt to block the screen and force new TOS agreement.

**Screenshots**
Due to extreme hardening on Windows GroupPolicy, I cannot screenshot my desktop.

**Desktop (please complete the following information):**
 - OS: Win11 Pro N v22631.3447
 - Method of installation: armcord website github executable
 - Version: 3.2.6

**Additional context**
This type of behavior has occurred outside of applying this setting in the past. problem may be deeper than the custom CSS functionality.
A found work around is to reinstall ArmCord entirely.

**Comment by SomeAspy** [comment]
I had an issue where the client would crash if you sent messages without accepting the agreement.
I was not able to replicate this crash (I have accepted the TOS already) on arch linux.
You can opt out of the major forced arbitration clause at `arbitration-opt-out@discord.com` and putting the usernames you want to opt out in the body of the email (you must send this email from the email associated with the account)

**Comment by Truinto** [comment]
The TOS also defines direct messages as content, which you 'license' to discord to use in any way. The whole thing is against my country's laws in any way you look at it.
Anyway, the CSS works fine. Except that all context menus don't pop up. E.g. right clicking a server or user shows no dialog. Any idea how to fix that?

**Comment by SomeAspy** [comment]
Closing as this is directly related to an event that happened.
