### ISSUE TITLE
Armcord still uses microphone after a call

### ISSUE THREAD

**Issue by Yama-K** [smartfrigde/armcord#571]
**Describe the bug**
Armcord keeps using the microphone after a call ends

**To Reproduce**
1. Start a call
2. Have a nice and civilized conversation
3. End call
4. Still uses microphone after call for no reason

**Expected behavior**
Stops using the microphone

**Screenshots**
![image](https://github.com/ArmCord/ArmCord/assets/26037681/32a8ccc7-9584-4634-9873-8a914129dcf3)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Method of installation: ArmCord.Setup.3.2.6.exe from github
 - Version: 3.2.6

**Comment by smartfrigde** [comment]
Please retest on 3.2.7

**Comment by Yama-K** [comment]
Werks, great job
