### ISSUE TITLE
Wrong Window Shared & Unable to Change and System Audio Muted When Streaming

### ISSUE THREAD

**Issue by AeroAli** [smartfrigde/armcord#573]
**Describe the Bug**
The wrong window is shared and I am unable to change it from streaming the main monitor contents
System audio muted when streaming in armcord - unmutting system audio in the taskbar works

**To Reproduce**
1. Join a voice channel in a server in armcord
2. Click on 'Share Your Screen'
3. Select what window to share
4. See that system audio is muted and the main display is streamed instead of the selected window
5. Unmute system audio via the taskbar (with no issues)
6. Click 'Change Windows' to swap to the correct window and see that it does not work

**Expected Behavior**
Armcord to stream the selected window and not mute system audio

**Video Recording**

https://github.com/ArmCord/ArmCord/assets/116851070/d502f878-0675-4c8f-9720-7f35ee47caf9

**Desktop:**
 - OS: Windows10
 - Method of installation: .exe from github releases
 - Version: 3.2.7

**In App Version Info:**
- stable 294520 (9ce8cb4)
- Vencord f74da73 (Web)
- Electron 30.0.6
- Chromium 124

**Comment by smartfrigde** [comment]
Should be fixed on 3.3.0
