### ISSUE TITLE
small inconsistencies with context menu

### ISSUE THREAD

**Issue by brokedarius** [smartfrigde/armcord#584]
**Describe the bug**

Search with duckduckgo entry appears twice on my end. Not only that but sometimes I would right click and get the regular discord menu and other times I would get the apps context menu.

**To Reproduce**

Right click several times in a chat window.

**Expected behavior**

Ideally the user should get to decide which one they want in the settings by default and be able to get other one by pressing shift + right click. 

Windows does the same with it's context menu for the extra entries to appear and I thought similar behavior could be applied here as well.

**Screenshots**

![2024-05-27_07-09](https://github.com/ArmCord/ArmCord/assets/95202445/59d4d527-b5c1-4eb3-a683-862911b085c0)

**Desktop (please complete the following information):**
 
- OS: Windows
 - Method of installation: winget
 - Version: latest

**Comment by SomeAspy** [comment]
> Not only that but sometimes I would right click and get the regular discord menu and other times I would get the apps context menu.

@brokedarius if you are highlighting text, it will bring up ArmCord's custom context menu.

Extra DuckDuckGo entry confirmed on Arch linux, Wayland [ArmCord@79ab3ca](https://github.com/ArmCord/ArmCord/commit/79ab3cabb39aa327149dcedcd9336e322de08173)
