### ISSUE TITLE
Screenshare not working on X11, blank white window shown instead

### ISSUE THREAD

**Issue by d-raw** [smartfrigde/armcord#596]
When joining a voice channel and trying to share screen, a blank white window is shown instead of the display picker. 
I have 2 monitors connected to the laptop.
OS: Arch linux
WM: AwesomeWM(X11)
armcord-git version r1118.79ab3ca-1 installed from AUR

Error message shown in stdout when screenshare button is pressed: 
```
(node:5) electron: Failed to load URL: file:///usr/share/armcord/app.asar/ts-out/discord/screenshare/picker.html with error: ERR_FILE_NOT_FOUND
```

![image](https://github.com/ArmCord/ArmCord/assets/117937581/4541fb89-2ec2-45c5-b211-4e928a56daf9)

**Comment by SomeAspy** [comment]
Have you tried re-installing armcord?
The missing file is an internal armcord file, so it should be there.

**Comment by SomeAspy** [comment]
Closing as stale as:
- no response
- nobody else has mentioned this issue
- stable has hit 3.2.8
