### ISSUE TITLE
Refuses to launch 

### ISSUE THREAD

**Issue by thecatontheceiling** [smartfrigde/armcord#609]
**Describe the bug**
Literally ceases to function

**To Reproduce**
1. Install Armcord
2. Open Armcord
3. It can't boot

**Screenshots**
Gets stuck on the below stage:
![image](https://github.com/ArmCord/ArmCord/assets/75037904/9afbb434-8d2c-4a0b-bb8c-bd522fec07e9)

**Desktop:**
 - OS: Windows
 - .exe
 - Latest

**Comment by SomeAspy** [comment]
Hi, are you using the latest dev build or v3.2.7?

I just tested the dev build on windows 11 in a VM, and seemed fine.

**Comment by thecatontheceiling** [comment]
nvm mitmproxy wasn't setup correctly and was blocking half of my apps from making requests :D
