### ISSUE TITLE
massive discord

### ISSUE THREAD

**Issue by AshtonMccloud** [smartfrigde/armcord#612]
**Describe the bug**

**To Reproduce**
not sure but everytime I open armcord everything is insanely massive and there is no way to fix

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux
**Additional context**

**Comment by AshtonMccloud** [comment]
![image](https://github.com/ArmCord/ArmCord/assets/172555294/82b9e111-dc42-4dee-9aa4-971e6bf40d0a)

**Comment by MeowcaTheoRange** [comment]
Are you able to change the zoom level using the `CTRL` `-` and `CTRL` `+` shortcuts? ArmCord saves zoom level between start-ups, so this could be the issue.

**Comment by smartfrigde** [comment]
Ctrl+0 should reset your zoom level

**Comment by MeowcaTheoRange** [comment]
> Ctrl+0 should reset your zoom level

`CTRL` `0` doesn't work on ArmCord (at least, on Linux)
