### ISSUE TITLE
Add an option for disabling smooth scrolling

### ISSUE THREAD

**Issue by thecatontheceiling** [smartfrigde/armcord#623]
**Is your feature request related to a problem? Please describe.**
Discord with smooth scrolling on is extremely blurry (especially on my 240hz monitor) it makes my eyes scratchy.

**Describe the solution you'd like**
add thing to the thing

**Additional context**

```
    if (disableSmoothScroll) {
        app.commandLine.appendSwitch("disable-smooth-scrolling");
    }
```

**Comment by SomeAspy** [comment]
#624
