### ISSUE TITLE
[FR] Add mouse autoscrolling option

### ISSUE THREAD

**Issue by fiftydinar** [smartfrigde/armcord#629]
I believe that WebCord has this implemented, so you can possibly draw the inspiration from them.

**Comment by smartfrigde** [comment]
You can use this flag for now: `--enable-blink-features=MiddleClickAutoscroll`

**Comment by SomeAspy** [comment]
I can do this, give me a bit.

**Comment by SomeAspy** [comment]
Added in [fd79b62](https://github.com/ArmCord/ArmCord/commit/fd79b620880afa5d8d80cde9c3387ad681efc576)
Let me know if you have issues with it.
