### ISSUE TITLE
Rich presence doesn't work again

### ISSUE THREAD

**Issue by Seme4eg** [smartfrigde/armcord#641]
Everything pretty similar to #505. And i am using still all the same - Doom emacs, elcord package, that reports successfull connection to arRPC, but armcord isn't displaying anything. 

Armcord logs: http://0x0.st/XmbF.txt

**Comment by smartfrigde** [comment]
arRPC broke with the Discord update that also broke Vencord, I'm on vacation right now but I managed to make a partial fix in a form of a shelter plugin:

`https://armcord.github.io/shelter-plugins/armcordRPC/`

You just need to install this and RPC should work partially (without images and games (?))

**Comment by Seme4eg** [comment]
Thank you for quick response, sir! Installing and enabling shelter mod you suggested didn't help in my case, so i guess i will be waiting for another fix some day when you will have time. Just in case that matters - i am using latest armcord-bin package from arch AUR.

**Comment by AndroAGENT** [comment]
but I want to use Vencord and still have arRPC.

**Comment by smartfrigde** [comment]
@AndroAGENT  Then you have to wait or contribute ;)

**Comment by AndroAGENT** [comment]
i am patient so ill wait

**Comment by cantalupo555** [comment]
I've tried everything and Rich presence doesn't work.

**Comment by SomeAspy** [comment]
Closed in favor of #552
