### ISSUE TITLE
The Vencord options sometimes don't appear.

### ISSUE THREAD

**Issue by FailSafeNow** [smartfrigde/armcord#642]
Goes like this:

Launch ArmCord, with Vencord installed, and go to Settings. All the sidebar links to Vencord options will be there.

BUT:

Load a theme, or change your current theme, and let the page reload. Then go to Settings. The links to Vencord options won't be there anymore. You'll have to restart the client to get them back.

ArmCord 3.2.7, Windows 11.

**Comment by thecatontheceiling** [comment]
They're not loading for me every time I open the app.

**Comment by smartfrigde** [comment]
Provide logs please

**Comment by smartfrigde** [comment]
@FailSafeNow @thecatontheceiling

**Comment by thecatontheceiling** [comment]
I'm on vacation and I'm 1000+ km away from my PC

**Comment by SomeAspy** [comment]
@FailSafeNow your issue is being migrated to https://github.com/ArmCord/ArmCord/issues/687
@thecatontheceiling your issue appears to be unrelated to this issue, as this issue is related to reloads. If you still can't get vencord to inject properly, feel free to open a new issue.
