### ISSUE TITLE
Notifications not Badging Taskbar Icon

### ISSUE THREAD

**Issue by sp0rrk** [smartfrigde/armcord#651]
Taskbar icon isnt badged despite being set to dynamic. Tray icon does badge though.

<img width="399" alt="image" src="https://github.com/user-attachments/assets/5aa7f27d-a2a6-4e31-ae4c-f4538a25e42f">

**Comment by smartfrigde** [comment]
Can you try latest devbuild? I've changed the way ping count is applied to the icon, make sure dynamic icon is disabled in settings (yes confusing I know, will be resolved when hits stable)

https://github.com/ArmCord/ArmCord/releases/tag/devbuild

**Comment by smartfrigde** [comment]
This is fixed on devbuilds
