### ISSUE TITLE
Notifications do not send no ping noises are heard

### ISSUE THREAD

**Issue by brambora69123** [smartfrigde/armcord#655]
**Describe the bug**
Notifications do not send at all and no ping noise is heard (after a while of being minimized)

**To Reproduce**
1. Install armcord
2. Observe the app not sending notifications and no ping noises

**Expected behavior**
Notifications should be sent and I should be able to hear the ping noise

**Desktop (please complete the following information):**
 - OS: Windows 11 Enterprise LTSC 24H2 26100.1150
 - Method of installation Setup EXE
 - Version: 3.2.7

**Additional context**
Just to clarify I do have notifications enabled, I use the online mode and when I use the normal discord desktop client everything works normally

**Comment by smartfrigde** [comment]
Try running with `--disable-renderer-backgrounding` flag

**Comment by brambora69123** [comment]
I had desktop notifications off.... i dont know why i never turned them off

**Comment by SomeAspy** [comment]
They seem to be off by default on fresh installs and after some updates. This may be related to discord seeing the client as a browser.
