### ISSUE TITLE
ARMCord implementation in Tauri

### ISSUE THREAD

**Issue by enganese** [smartfrigde/armcord#662]
**Is your feature request related to a problem? Please describe.**
Discord weighs a lot. 

**Describe the solution you'd like**
I would like to see Discord/ARMCord using Tauri instead of Electron.

**Describe alternatives you've considered**
There is no stable alternative as per now. One of them is not maintained anymore, while another is just a small test project without support of all discord features.

**Additional context**
It will increase performance, reduce application size, and be more secure.

Tauri: [tauri.app](https://tauri.app/)

**Comment by SomeAspy** [comment]
We looked at this a bit, and I talked about tauri with a few devs. Ultimately, we observed it was a bit over hyped among other things.
![image](https://github.com/user-attachments/assets/66c44664-5897-4faa-8a22-97cee9523912)

**Comment by yellowsink** [comment]
if you wanted more detail, tauri does not exhibit the benefits you think it does (it is NOT faster nor more secure),
comes with plenty of downsides,
is marketed on grifts, ignores the entire reason electron was made in the first place, and most of all asking for a complete rewrite of a project for no gain is simply never happening.
