### ISSUE TITLE
Screenshare = No Audio

### ISSUE THREAD

**Issue by WitheredFOT** [smartfrigde/armcord#663]
Whenever I screenshare, I can't hear the audio. I don't exactly know why, but yeah.

1. Go to a call
2. Click on "Share Screen"
3. Select "Screen 1"
4. And boom, you can't hear audio.

Obviously, I expected to hear my computer and sounds coming from games I screenshare, but nope, I can't hear anything.

 - OS: Win11 22H2 22621.2861
 - Method of installation: .exe application
 - Version: ArmCord 3.2.7; Vencord 80b493d; Discord Stable 312247

I hope this helps and the bug is fixed, it's quite the annoyance.

**Comment by EthanL06** [comment]
Same here. Hope this will get fixed soon

**Comment by smartfrigde** [comment]
Can you try latest devbuild? https://github.com/ArmCord/ArmCord/releases/tag/devbuild

**Comment by WitheredFOT** [comment]
Done, it's fixed, thanks <3
