### ISSUE TITLE
Screeensharing not working, at all

### ISSUE THREAD

**Issue by Resister0** [smartfrigde/armcord#671]
**Describe the bug**
Screensharing does not work, in any server, admin perms or not, even if I own the server.

**To Reproduce**
1. Go to 'Join a voice channel'
2. Click on 'Attempt to screenshare'

**Expected behavior**
Screensharing should start

**Screenshots**
Not applicable

**Desktop (please complete the following information):**
 - OS: [e.g. Linux, Windows, macOS]
 - Method of installation [e.g. snap, setup exe, aur]
 - Version [e.g. 3.0.7]

**Additional context**
None

**Comment by smartfrigde** [comment]
Please specify version and platform you're running ArmCord on

**Comment by Resister0** [comment]
Windows 11, latest windows update
Desktop

**Comment by Resister0** [comment]
I click on screenshare, then on the window I want to screenshare, and legit nothing happens, the menu to select which screen to screenshare closes and nothing happens from there

**Comment by U5KUN** [comment]
Me too.

MacBook Pro 2020 13inch M1
macOS Sonoma 14.0

**Comment by smartfrigde** [comment]
Try 3.2.8

**Comment by SomeAspy** [comment]
closing as stale
