### ISSUE TITLE
Failed to render theme tab

### ISSUE THREAD

**Issue by Astral92** [smartfrigde/armcord#684]
**Describe the bug**
Themes vencord option doesn't work, reinstalling didn't work

**Screenshots**
![image](https://github.com/user-attachments/assets/693a2486-61fd-479a-a40a-8ebf6217250b)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Method of installation setup.exe
 - Version 3.2.8

**Additional context**

**Comment by SomeAspy** [comment]
This appears to be a recent issue with vencord, I'd follow Vencord development status on this one. I'll keep the issue open for the time being however.

**Comment by Astral92** [comment]
> This appears to be a recent issue with vencord, I'd follow Vencord development status on this one. I'll keep the issue open for the time being however.

I want to add that the "Upload Theme" button in vencord themes doesn't always work I have to press it multiple times/ leave the tab then enter it again for it  to work.

Also "Edit QuickCSS" option sometimes open a white blank page. this also happens if I already had quickCSS then click the "Edit  QuickCSS" option

**Comment by SomeAspy** [comment]
fixed upstream
https://github.com/Vendicated/Vencord/commit/eaca14bb5a970073bc3175a5c46791e3a7b77514
