### ISSUE TITLE
[Feature Request]: Supporting custom domains for Armcord theme imports

### ISSUE THREAD

**Issue by oomfiee** [smartfrigde/armcord#689]
**Is your feature request related to a problem? Please describe.**
Supporting the Armcord theme import feature to support any domain.

**Describe the solution you'd like**
Supporting more domains than Github's. (raw.githubusercontent.com)

**Describe alternatives you've considered**
Advanced Theme Manager.

**Additional context**
Armcord's theme import manager does not support any other domain that isnt github's (raw.githubusercontent.com)

**Comment by lexisother** [comment]
ArmCord's theme loader currently only supports BD themes, and as such any files you give it should have a valid BD theme manifest at the top. A regular QuickCSS loader is being worked on.

**Comment by smartfrigde** [comment]
https://github.com/ArmCord/ArmCord/commit/1c9fd5518c08d70fa51bbdab2cc44fc9101b55b4
Quick CSS is done :)
