### ISSUE TITLE
Option to disable hardware acceleration

### ISSUE THREAD

**Issue by k-e-l-p** [smartfrigde/armcord#693]
**Is your feature request related to a problem? Please describe.**
My feature request is in relation to an issue I'm constantly running into with electron apps on my current setup. They always flicker and glitch out. this is more caused by wayland and nvidia being terrible, but, as a workaround, disabling hardware acceleration fixes the glitches at the cost of my CPU, which I'm fine with.

**Describe the solution you'd like**
Add a toggle button in the advanced section of settings to enable/disable hardware acceleration

**Describe alternatives you've considered**
My alternatives are to grin and bear it or switch discord clients to something that offers this option.

**Additional context**
N/A

**Comment by smartfrigde** [comment]
You can simply run ArmCord with the `--disable-gpu` flag. I'll add the option to do that from settings soon

**Comment by SomeAspy** [comment]
oops this was completed in https://github.com/ArmCord/ArmCord/commit/b47662d5a8d33b5e5ffffbac776c38f99c292413
