### ISSUE TITLE
Website says macOS 10.13 or newer, while High sierra(10.13) complains app is too new(requires 10.15 or upper)

### ISSUE THREAD

**Issue by EggToaster** [smartfrigde/armcord#694]
**Describe the bug**
Title explains all.
Website says macOS 10.13 or newer, while High sierra(10.13) complains app is too new(requires 10.15 or upper)

**To Reproduce**
Go to https://armcord.app/download

**Expected behavior**
Should install on high sierra(10.13), or website should say 10.15 or upper.

**Desktop (please complete the following information):**
 - OS: MacOS High sierra 10.13
 - Method of installation .dmg file
 - Version Any but older(aka i'm too lazy to note)

**Comment by smartfrigde** [comment]
Use ArmCord Legacy

https://github.com/ArmCord/ArmCord/releases/tag/legacybuild

Download the file with `e27` in the name

I'll update the website soon

**Comment by EggToaster** [comment]
e27 didn't worked for me, I had to use e24? e25? instead. Anyways, thanks!
