### ISSUE TITLE
Get rid of the annoying "Get the desktop app!" banner

### ISSUE THREAD

**Issue by gamedevsam** [smartfrigde/armcord#711]
**Is your feature request related to a problem? Please describe.**
When I launch Armcord I see a bright green banner at the top telling me to download the desktop client, is there any way to remove this?

![image](https://github.com/user-attachments/assets/4b820ebe-37c8-4a63-acb1-db1c38fb4e0b)

**Describe the solution you'd like**
A setting that would allow me to get rid of that banner.

**Comment by smartfrigde** [comment]
We are technically already doing this here
https://github.com/ArmCord/ArmCord/blob/dev/src/discord/preload/preload.mts#L14

Could you go to settings and use the `Copy debug info` option and send it here?

**Comment by gamedevsam** [comment]
Here you go:

```
**OS:** win32 Windows 11 Pro
**Architecture:** arm64
**ArmCord version:** 3.3.0
**Electron version:** 32.0.1
`{
    "windowStyle": "default",
    "channel": "stable",
    "armcordCSP": false,
    "minimizeToTray": true,
    "keybinds": [],
    "multiInstance": false,
    "mods": "none",
    "spellcheck": true,
    "hardwareAcceleration": true,
    "performanceMode": "none",
    "skipSplash": false,
    "inviteWebsocket": false,
    "startMinimized": false,
    "dynamicIcon": false,
    "tray": true,
    "customJsBundle": "https://armcord.app/placeholder.js",
    "customCssBundle": "https://armcord.app/placeholder.css",
    "disableAutogain": false,
    "useLegacyCapturer": false,
    "mobileMode": false,
    "trayIcon": "dsc-tray",
    "doneSetup": true,
    "clientName": "ArmCord",
    "customIcon": "C:\\Users\\samba\\AppData\\Local\\ArmCord\\resources\\app.asar\\assets\\desktop.png",
    "smoothScroll": true,
    "autoScroll": false
}`
```

**Comment by gamedevsam** [comment]
After I opened and closed the settings menu the banner disappeared, pretty interesting!

**Comment by gamedevsam** [comment]
I'm closing this issue as I cannot reliably repro this issue now.
