### ISSUE TITLE
Minimise the ArmCord window with Command+M on Macintosh

### ISSUE THREAD

**Issue by isopropyl-alco** [smartfrigde/armcord#714]
Hello, on most OS X software you can minimise a window the the keyboard shortcut Command+M, it lives up here on the menu bar
<img width="274" alt="image" src="https://github.com/user-attachments/assets/d636c969-12fa-4b53-ba8b-e5de71e2a3d8">
as someone who uses the Command+M keyboard shortcut a lot to minimise windows I would greatly appreciate it if this was added into ArmCord.

Thank you.

**Comment by SomeAspy** [comment]
Is that minimise option not there for the armcord window when you open the window menu?

**Comment by SomeAspy** [comment]
Nevermind, it's mapped to mute. @smartfrigde what you wanna do about this? https://github.com/ArmCord/ArmCord/blob/19b4be0ae5ca4f055b842019c8aa66d742d5ae80/src/discord/keybinds.ts#L5-L6

**Comment by isopropyl-alco** [comment]
That says Command+Shift+M, not Command+M as it is universally in OS X. 

Pardon my ignorance if I got something wrong.

**Comment by smartfrigde** [comment]
Done here https://github.com/ArmCord/ArmCord/commit/4d98a03265a705382764145fbb205938ce9751e2
