### ISSUE TITLE
[macOS] Support for presenter overlay on macOS Sequoia

### ISSUE THREAD

**Issue by MEMORIEmusic** [smartfrigde/armcord#719]
### **Is your feature request related to a problem? Please describe.**
The current screenshare window is pretty weird and buggy, it doesn't show up a lot of the times, and there are chances of misclicking.
You also cannot select fullscreen apps with the current screenshare setup, which is a major annoyance. This can be fixed by using presenter overlay.

<img width="912" alt="Screenshot 2024-09-17 at 11 42 55" src="https://github.com/user-attachments/assets/bcf9bbc7-3fb7-4b92-a9ef-b6a2c6b7d132">

### **Describe the solution you'd like**
Support for Presenter Overlay, a feature added in macOS Sequoia. It makes for a clean screensharing solution. The official Discord client already seems to have added support for it.

![Screenshot 2024-09-17 at 11 49 51](https://github.com/user-attachments/assets/251a0bbd-46e5-48cf-8c9e-5547d49b9eb6)

**Describe alternatives you've considered**
N/A

**Additional context**
<img width="521" alt="Screenshot 2024-09-17 at 11 51 33" src="https://github.com/user-attachments/assets/551d4585-0d6d-47d7-b60e-639d2fe99312">
<img width="508" alt="Screenshot 2024-09-17 at 11 51 53" src="https://github.com/user-attachments/assets/ab3d947f-f743-473a-ba98-43d85fd028af">

**Comment by smartfrigde** [comment]
When ArmCord stable catches up with latest Electron version, it should be available 

https://github.com/electron/electron/pull/43679

**Comment by SomeAspy** [comment]
Hi, can you check if this works? I think it should be implemented here https://github.com/Legcord/Legcord/commit/a7ef1635ecc363a22993115f5d539ab909be4d35

**Comment by MEMORIEmusic** [comment]
> Hi, can you check if this works? I think it should be implemented here [a7ef163](https://github.com/Legcord/Legcord/commit/a7ef1635ecc363a22993115f5d539ab909be4d35)

Kinda. It let's you pick up the window, but once you start screensharing, it asks you to pick up the window again. It does that 2 times. 
Another thing missing is that we cannot choose the streaming resolution. But yeah, other than that, it works perfectly.

**Comment by SomeAspy** [comment]
Linux has the same issue where the input needs to be selected twice, so I will close this issue as the presenter overlay has been implemented.
I will put this unrelated issue on the issue tracker.
Thanks for the feedback!

**Comment by SomeAspy** [comment]
https://github.com/Legcord/Legcord/issues/758
