### ISSUE TITLE
People can hear sounds of discord on your stream

### ISSUE THREAD

**Issue by moseechev** [smartfrigde/armcord#724]
**Describe the bug**
People can hear sounds of discord on your stream. (Including their voices

**To Reproduce**
1. Start the stream

**Expected behavior**
You should NOT be able to hear your voice on someone's stream.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Method of installation not sure
 - Version 10, not sure which build exactly

**Additional context**
Nothing else

**Comment by SomeAspy** [comment]
merging into #782
