### ISSUE TITLE
flatpak reports: org.freedesktop.Platform branch 22.08 is end-of-life

### ISSUE THREAD

**Issue by dperson** [smartfrigde/armcord#725]
**The 22.08 org.freedesktop.Platform is EoL**
The flatpak platform will receive no more security / bug fixes.

**To Reproduce**
1. Have the `xyz.armcord.ArmCord` flatpak installed
2. Run `flatpak update`
3. See error message in the ouput:
```
Info: runtime org.freedesktop.Platform branch 22.08 is end-of-life, with reason:
   org.freedesktop.Platform 22.08 is no longer receiving fixes and security updates. Please update to a supported runtime version.
Info: applications using this runtime:
   xyz.armcord.ArmCord
```

**Expected behavior**
No errors / warnings of EoL platforms for installed software.

**Screenshots**
N/A it's textual output shown above.

**Desktop (please complete the following information):**
 - OS: Fedora Linux 40 (Silverblue / UniversalBlue)
 - Method of installation: flatpak (FlatHub)
 - Version: 3.3.1

**Additional context**
Thanks for making the best Discord client!

**Comment by SomeAspy** [comment]
Should make it to flathub in about ~3 hours
https://github.com/flathub/xyz.armcord.ArmCord/commit/51f2b71400411fc1f904e6451815210c8e93ed73
