### ISSUE TITLE
Revert various screensharing changes

### ISSUE THREAD

**Issue by Metrokoto** [smartfrigde/armcord#734]
I am trying to screenshare a movie with a friend, however, when trying to do so, I see a distracting, and unwanted yellow border around my browser window, and if I share my audio, I have to keep unmuting my system's audio, as Armcord, for some reason, mutes my playback without reason. 

Please revert whatever changes caused this, as using screenshare on Armcord is now no longer an option for me as a result of this.

**Comment by SomeAspy** [comment]
Can you please attach a screenshot of this?
What OS are you on?

**Comment by Metrokoto** [comment]
> Can you please attach a screenshot of this? What OS are you on?

I am on Windows, and a screenshot is not needed.
Just imagine there is a yellow border around every window that you share via screenshare and that your system audio volume shows as muted.

That did not happen until the recent versions, and I do not like it one bit. It is unneccesary, unwanted, and visually unappealing.

**Comment by smartfrigde** [comment]
The yellow border is a Windows thing:
https://www.reddit.com/r/obs/comments/190bc8g/windows_11_how_to_effectively_get_rid_of_the/

**Comment by SomeAspy** [comment]
Hi, as smartfridge said, this is a windows issue.
However,
This issue is being closed:
- You are being exceptionally cocky about this
- You did not follow the issue template
- You refused to include info requested.

Closed as unrelated to armcord.
![image](https://github.com/user-attachments/assets/82ee7752-4d86-4f37-9b4d-9cc8418b69c6)

**Comment by Metrokoto** [comment]
This issue is related to Armcord.
Regardless of the border, the system audio still mutes itself, why?

**Comment by SomeAspy** [comment]
If you have an issue open a new issue using the issue template.

**Comment by Metrokoto** [comment]
> If you have an issue open a new issue using the issue template.

🤡

**Comment by Metrokoto** [comment]
I told you the issue.
