### ISSUE TITLE
Option to disable autogain is missing

### ISSUE THREAD

**Issue by Metrokoto** [smartfrigde/armcord#735]
In the latest ArmCord versions, the option to disable autogain is missing.
This resulted in my recording device's settings being constantly changed by the ArmCord process, which is behaviour I do not want, as I have external software to control gain and other effects like noise cancellation.

Please restore the setting so that this annoyance can be avoided.

**Comment by SomeAspy** [comment]
Unrelated to armcord, cannot reproduce.
![image](https://github.com/user-attachments/assets/19f1d0f4-1ae2-4c6d-adf7-2d7d89868b7d)

Please use the issue template and attach required details if you wish to get help with your issue.

**Comment by smartfrigde** [comment]
![obraz](https://github.com/user-attachments/assets/fdba8220-ca79-4a2a-944d-3463e8e2ceff)
https://github.com/Legcord/Legcord/commit/bcca37ccc2f73e1fe3541fcd64e45be44ddc9d09
