### ISSUE TITLE
Equicord not available

### ISSUE THREAD

**Issue by oddbyte** [smartfrigde/armcord#740]
**Describe the bug**
I cannot find any way to enable equicord

**To Reproduce**
1. Go to settings
2. See the lack of the option to enable equicord

**Expected behavior**
A toggle or some other way to switch between vencord and equicord

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Method of installation: Winget, then I tried Microsoft Store
 - Version 3.3.1

**Comment by KrystalSkullOfficial** [comment]
As of now the only way to use Equicord with Armcord is with a dev build

https://github.com/ArmCord/ArmCord/releases/tag/devbuild
