### ISSUE TITLE
ERROR:gbm_pixmap_wayland.cc(82)

### ISSUE THREAD

**Issue by ELECTAPE-CASS** [smartfrigde/armcord#741]
**Describe the bug**
Journal spam due to multiplane rendering attempts in Wayland (Does NOT Support Multiplane Rendering)

**To Reproduce**
1. Open Armcord
2. Enter any text chat with video or images
3. Check journal log (journalctl in systemd)

**Expected behavior**
Quiet log

**Cause**
Electron 31+ enables multiplane rendering by default as a result of an update to Chromium 126

**Similar Issue Reports in Other Projects**
https://github.com/th-ch/youtube-music/issues/2248
https://issues.chromium.org/issues/331796411#comment5

**Screenshots**
![Screenshot_20241008_025715](https://github.com/user-attachments/assets/a5397575-03d0-4b4d-a18f-c8f8377f18b5)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Method of installation: AUR
 - Version: 3.3.1-1

**Current Workaround**
Recompile ArmCord with "UseMultiPlaneFormatForSoftwareVideo" flag disabled in Main.ts
![Screenshot_20241008_035634](https://github.com/user-attachments/assets/fcc5449f-fade-4ff3-9b76-bf6a74714fd9)

**Comment by ELECTAPE-CASS** [comment]
it occurs to me that there are actually two flags: UseMultiPlaneFormatForSoftwareVideo, and UseMultiPlaneFormatForHardwareVideo according to the issue opened in the chromium project

**Comment by ELECTAPE-CASS** [comment]
the same bug presented in vesktop a month ago 
https://github.com/Vencord/Vesktop/issues/852

**Comment by smartfrigde** [comment]
https://github.com/ArmCord/ArmCord/commit/b79dc4dcaf63bc6277fc2a8e366942da64b03d0b
