### ISSUE TITLE
Client showing "failed connect to arRPC" error

### ISSUE THREAD

**Issue by realdcre** [smartfrigde/armcord#748]
**Describe the bug**
ArRPC not starting/working correctly.
**To Reproduce**
1. enable arRPC both in Vencord and the Legcord settings
2. Fully Close legcord
3. reopen legcord

**Expected behavior**

arRPC to work normally

**Screenshots**
![image](https://github.com/user-attachments/assets/86ff4a31-2de8-4350-95a0-2ca60da232b8)

**Desktop (please complete the following information):**
 - OS: Windows 10 IoT-Enterprise LTSC 64bit
 - Method of installation: Setup Exe (64Bit)
 - Version 1.0.1 

**Additional context**
The enabling and disabling of arRPC either through Vencord nor Legcord settings fixes the issue.

**Comment by SomeAspy** [comment]
This is an error from the Vencord arRPC plugin, which overrides the internal server. Turn it off.

**Comment by realdcre** [comment]
Thank you for the help.
