### ISSUE TITLE
[LINUX] Video doesn't fullscreen

### ISSUE THREAD

**Issue by refurbishing** [smartfrigde/armcord#749]
**Describe the bug**
Video doesn't want to Fullscreen when it's supposed to.

**To Reproduce**
1. Go on a Video
2. Click the Fullscreen icon
3. See nothing happen

**Expected behavior**
The video to fullscreen correctly

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Arch Linux 
 - Method of installation: AUR
 - Version: 1.0.1

**Additional context**
This was already reported on the [dev-build-bugs channel](https://discord.com/channels/820732039253852171/1285951774427189341)

**Comment by smartfrigde** [comment]
Fixed https://github.com/Legcord/Legcord/commit/b7f2a3de24469c76eb852c1cf6097059d8faa047
