### ISSUE TITLE
Desktop Notifcations don't work on MacOS (Windows works) 

### ISSUE THREAD

**Issue by TempUser13** [smartfrigde/armcord#751]
After enabling Desktop Notifications in the Discord settings and receiving a DM, there is no notification sent on MacOS nor any notification prompt to allow. Windows worked with no issues issuing a notification. Unrelated to the bug report, the notification issuer is electron.app.legcord on Windows. I haven't tested Linux obviously.

Version 1.0.1 (MacOS and Windows)
Windows 11 22H2 ARM64 (Parallels) and MacOS Sonoma 14.7 Apple Silicon

**Comment by TempUser13** [comment]
Unrelated to Desktop Notifications, the Mac downloads on the website are broke since they link to arch specific builds but only a universal zip/dmg is available. Is there any thoughts on using [Tauri](https://tauri.app) over Electron too? Thanks for all the work that the team does.

**Comment by SomeAspy** [comment]
Regarding tauri, there is would be no gains. See https://github.com/Legcord/Legcord/issues/662

**Comment by TempUser13** [comment]
Fixed in v1.0.2
