### ISSUE TITLE
Vesktop plugins aren't available on Legcord

### ISSUE THREAD

**Issue by theoparis** [smartfrigde/armcord#753]
![image](https://github.com/user-attachments/assets/05e00a30-4579-4d28-b9d1-929da79bbd75)

I am using the rpm package for Legcord and some plugins like Shiki Codeblocks aren't supported for some reason... Can this be fixed as this is a desktop app and not a browser extension? 🤔

**Comment by SomeAspy** [comment]
duplicate of #713
