### ISSUE TITLE
Line breaks in [> quote blocks] aren't always recognized

### ISSUE THREAD

**Issue by Atri7** [smartfrigde/armcord#771]
Hi,
I am a poet and like to write and send prose in order to motivate and bring joy to those close to me, but I have noticed over the past week or two that when I enclose a poem in
> Quotation syntax,
then often the line breaks are stripped from the message when it's sent, so > it reads like this instead of
> reading how I typed it, with the line break

In the message preview at the bottom of my screen, I can see the message as I typed it with correct line breaks, but after I send it, one or more of the line breaks disappear.

**To Reproduce**
1. Go to any chat, private or server
2. Click on the message preview box to begin typing
3. Type '>' to start a quote block
4. Write a few words, then press shift+enter to drop a line.
5. This should open a new line of the quote block as expected.
6. Write five more words, then press shift+enter again, and write five more words on the third line of the quote block.
7. Press enter.

**Expected behavior**
Discord has supported quote block syntax for years, but after I started using Legcord last month, I noticed it breaking. When I press enter to send the message, one or more of the line breaks disappear, creating text similar to 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Setup: .exe
 -  Version: Stable 339221 (3687267) Electron 33.0.1, Chromium 130. Legcord Version 1.0.2

**Additional context**
I love the Legcord client thus far and sincerely appreciate all your hard work creating and maintaining it. Thanks for everything!

**Comment by SomeAspy** [comment]
In standard discord, if you want to linebreak, you press `shift` + `enter` to make a newline without sending the message.
I might be misunderstanding your problem though.
![image](https://github.com/user-attachments/assets/427b34ce-9087-4989-8eb0-95f634fabd2e)
