### ISSUE TITLE
Visual Glitch When Toggling Legcord Settings

### ISSUE THREAD

**Issue by PHenegan** [smartfrigde/armcord#773]
**Describe the bug**

When In the settings menu, I'm getting a visual bug where changing any of the toggles shows the toggle animation for every setting in the menu

**To Reproduce**
1. Go to 'User Settings -> 'Legcord Settings' 
2. Click on any of the menu toggles. I noticed it when toggling the "start minimized" setting but it seems like it's happening with everything else as well

3. The toggle animation plays for every single setting, even though only the one I clicked on actually changes

**Expected behavior**
The toggle animation only happens for the setting I click on, like the rest of the menus

**Screenshots**

Since it's an animation problem I included a video of the bug instead of a screenshot. It shows the animation playing for all of the toggle options. This only happens in the Legcord Settings menu and not any of the other settings menus I tried.
 
https://github.com/user-attachments/assets/c216804c-d204-4b13-abc2-2ff033636981

**Desktop (please complete the following information):**
 - OS: EndeavourOS linux
 - Method of installation [e.g. snap, setup exe, aur]: AUR
 - Version [e.g. 3.0.7]: 1.0.2

**Additional context**
This is obviously a pretty minor bug but I figured I might as well submit a bug report for it. Thanks for making a great app!

**Comment by SomeAspy** [comment]
I caused this bug and intended to fix it later when I fixed settings updated. Originally added to update the vencord/equicord switch so both cannot be on, instead updates all.

**Comment by smartfrigde** [comment]
Can't reproduce on 1.0.3, probably fixed along the way
