### ISSUE TITLE
Legacy build

### ISSUE THREAD

**Issue by RetroSoftwareRepository** [smartfrigde/armcord#774]
Looks like installers aren't built for legacy platforms anymore... any reason why that is?

**Comment by SomeAspy** [comment]
The legacy branch has been moved to https://github.com/Legcord/Legacy - I can initialize a release right now

**Comment by RetroSoftwareRepository** [comment]
> The legacy branch has been moved to https://github.com/Legcord/Legacy - I can initialize a release right now

No need. Thanks for pointing me in the right direction. Please update the download link for the Windows 7/8.1 and Legacy macOS versions to the Legacy repo. 

As a matter of fact that'll come in handy for Macs stuck on Lion/Mountain Lion (the latter is the unofficial maximum fully supported macOS on quite a few polycarbonate MacBooks due to the Intel integrated graphics)

**Comment by smartfrigde** [comment]
@RetroSoftwareRepository Sadly Legcord Legacy can only go down to OS X El Capitan. There were no Electron releases for Lion or Mountain Lion afaik

**Comment by RetroSoftwareRepository** [comment]
> The legacy branch has been moved to https://github.com/Legcord/Legacy - I can initialize a release right now

Mind spinning one up? Thank you. I'd do one myself but I don't have time to fire up my desktop right now. Also I'm running this thing right now on windows 7 Home Premium x64... Sony VAIO VGN-FZ240E (which by the way VkHex is dead.)
