### ISSUE TITLE
Weblate Link Broken 

### ISSUE THREAD

**Issue by ghost** [smartfrigde/armcord#776]
**Describe the bug**
The link to Weblate does not currently work. 

The link leads to https://hosted.weblate.org/projects/Legcord/Legcord/, which returns a "page not found". It seems like the old page (https://hosted.weblate.org/projects/armcord/armcord/) is still around and has not been migrated yet. 

**To Reproduce**
1. Go to https://github.com/Legcord/Legcord
2. 3. Scroll down to "Where can I translate this?"
3. Click on "Translations are done using our Weblate page"
4. See that it leads to a "page not found".

**Expected behavior**
I expected to see a valid weblate page.

**Screenshots**
![LegCord Not Found](https://github.com/user-attachments/assets/7abb9637-fcc7-4a1b-ba38-3519bd7ca64f)
![Old ArmCord Repo](https://github.com/user-attachments/assets/c2bc71b5-a689-492b-9073-d2eb3fb489bd)

**Desktop (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by smartfrigde** [comment]
https://hosted.weblate.org/projects/armcord/client/
