### ISSUE TITLE
Please use the expected tag name (version number)

### ISSUE THREAD

**Issue by theofficialgman** [smartfrigde/armcord#783]
Prior to the latest release (including on ArmCord), all releases were tagged with the version number. The current release uses the non-descriptive tag `stable` which makes CI, scripting, and simply checking out the repository difficult/impossible unless the user uses the github cli or github web interface to find the tag name. Please switch back to using the expected `v1.0.3` tag for this and future stable releases.

https://github.com/Legcord/Legcord/releases/tag/stable

**Comment by SomeAspy** [comment]
oops

**Comment by theofficialgman** [comment]
@SomeAspy Hi the tag version is still different. it is now `1.0.3` when the expected format based on previous tags would be `v1.0.3`

**Comment by SomeAspy** [comment]
Damnit

**Comment by SomeAspy** [comment]
@smartfrigde can you do the release I clearly don't know what I'm doing

**Comment by smartfrigde** [comment]
Yes, just made v1.0.4. Which has a correct tag. Additionally I changed v1.0.3 to be correct
