### ISSUE TITLE
Enable install at a custom location

### ISSUE THREAD

**Issue by realdcre** [smartfrigde/armcord#789]
** I have a very nieche usecase where I am quite often limited in storage on my computer. With ArmCord, I could simply install the app on my D:/ drive without issues, but now with every new update, I have to manually move it away from appdata and hope it continues to work.

**Describe the solution you'd like**
I would love if the installer that you can download from GitHub allowed you to select a install location.

**Describe alternatives you've considered**
Moving the legcird directory to D:/ and hope it still works

**Additional context**

**Comment by smartfrigde** [comment]
https://github.com/Legcord/Legcord/commit/54a482bcf4384ffdeaf57568f52c7f2b5178695d
