### ISSUE TITLE
Common window commands/shortcuts missing from macOS menu bar

### ISSUE THREAD

**Issue by kirb** [smartfrigde/armcord#794]
**Describe the bug**
Various common shortcuts don’t work on macOS, because the items are missing from the menu bar.

**To Reproduce**

1. Press ⌘W, ⌘H, etc.
2. Try finding the matching items in the Legcord, File, etc. menus

**Expected behavior**
The commands should be there since they’re common to all macOS apps, and other Electron apps including Discord also tend to have them.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 15.1
 - Method of installation: dmg
 - Version: 1.0.5

**Additional context**
Comparison of both apps’ menu bars:

<table>
<tr>
<th>Discord</th>
<td valign="top"><img width="234" alt="image" src="https://github.com/user-attachments/assets/40d5ebc3-2a1e-400e-b4d4-d1217b153011"></td>
<td valign="top"><img width="210" alt="image" src="https://github.com/user-attachments/assets/ce5484b5-b007-4f40-9894-f87ef419c6c8"></td>
<td valign="top"><img width="216" alt="image" src="https://github.com/user-attachments/assets/af10cab6-4dac-414e-9396-757c2e389b03"></td>
<td valign="top"><img width="152" alt="image" src="https://github.com/user-attachments/assets/7e77806a-59ee-4ba6-b851-7f21d9775078"></td>
<td valign="top"><img width="130" alt="image" src="https://github.com/user-attachments/assets/96c0124b-8305-494a-857a-d073b1cb129f">
</tr>
<tr>
<th>Legcord</th>
<td valign="top"><img width="198" alt="image" src="https://github.com/user-attachments/assets/bff36d4c-5434-4588-867e-df42994b1eaa"></td>
<td valign="top"><img width="203" alt="image" src="https://github.com/user-attachments/assets/4aa7a709-efa8-4362-a1c3-dcd8e81b9a84"></td>
<td valign="top"><img width="165" alt="image" src="https://github.com/user-attachments/assets/79c8f709-b8f3-4545-b75d-5bb19223266c"></td>
<td valign="top"><img width="161" alt="image" src="https://github.com/user-attachments/assets/a4c6aaed-b3a1-4bbe-a506-df17701e94a1"></td>
<td valign="top"><img width="94" alt="image" src="https://github.com/user-attachments/assets/104a615c-28b8-4b96-9838-119e0f6418c1"></td>
</tr>
</table>

Legcord is doing better by having correct fullscreen shortcut (🌐F), but is missing Close (⌘W), Hide (⌘H), Hide Others (⌥⌘H), and Show All. Missing the Services menu also means global Shortcuts keybinds the user has made won’t work while Legcord is in focus.

(Also, could I beg you to change the devtools shortcut to ⌥⌘I for consistency with Chrome/Discord? 😅)

**Comment by kirb** [comment]
I’m not good with Electron, but according to the docs, looks like many of the items that [currently](https://github.com/Legcord/Legcord/blob/554537cda42c4f172aaf893a26f007f1d5094d9e/src/discord/menu.ts) have custom handlers could be replaced with standard Electron handling by using [`role`](https://www.electronjs.org/docs/latest/api/menu#examples)? Then the items would have consistent label/shortcut/handler, good for localisation and keeping up when Apple decides to add more menu items. Their example seems consistent with the typical Mac app menu bar layout.

**Comment by kirb** [comment]
Just adding on here, I’ve been finding Redo ⇧⌘Z is not working. Undo ⌘Z does. Neither command works when invoked from the Edit menu.

**Comment by IAmVisco** [comment]
Wanted to report the same thing, pressing them out of the habit and nothing happens lol. Additionally, Finder and the original Discord client also support Cmd+[ and Cmd+] to go backward/forward between channels.

**Comment by smartfrigde** [comment]
> I’m not good with Electron, but according to the docs, looks like many of the items that [currently](https://github.com/Legcord/Legcord/blob/554537cda42c4f172aaf893a26f007f1d5094d9e/src/discord/menu.ts) have custom handlers could be replaced with standard Electron handling by using [`role`](https://www.electronjs.org/docs/latest/api/menu#examples)? Then the items would have consistent label/shortcut/handler, good for localisation and keeping up when Apple decides to add more menu items. Their example seems consistent with the typical Mac app menu bar layout.

@kirb 
The `role` property appears to register the menu correctly, allowing access through the menu bar. However, the associated keyboard shortcuts do not function as expected. While the menu items are clickable, their shortcuts fail to trigger the corresponding actions. This is mostly why we had to move to custom handlers :(

I'm gonna fill out the missing keybind shortcuts manually to solve this issue soon

**Comment by smartfrigde** [comment]
https://github.com/Legcord/Legcord/commit/d0b4777aade38d25e30809665dcf343d9bcbbc3e

This should fix it

**Comment by IAmVisco** [comment]
I'm not sure that commit will fix cmd+z issues or missing cmd+[ navigation

**Comment by smartfrigde** [comment]
> I'm not sure that commit will fix cmd+z issues or missing cmd+[ navigation

@IAmVisco sorry I missed those, fixed here https://github.com/Legcord/Legcord/commit/6888db743d73a8cd7fd2b5d035e7025c09148912

As for cmd+[ navigation, I need to look into how Discord does it
