### ISSUE TITLE
Combined macOS title bar style

### ISSUE THREAD

**Issue by kirb** [smartfrigde/armcord#795]
**Is your feature request related to a problem? Please describe.**
The Discord app on macOS hides the native title bar, and sets up the header area to be draggable. It would be nice if Legcord could support this as a title bar style.

**Describe the solution you'd like**
I got it to work by adding `class="platform-osx"` to `body`, but whether that’s a good idea, I don’t know. (`html` class gets overwritten on next render.)

<img width="455" alt="image" src="https://github.com/user-attachments/assets/bbc59044-c2ab-43cc-969b-57d2993bd626">

On macOS, Discord asks Electron to render the native traffic lights on top of the web view, hence the added margin in the sidebar. That makes sure it has the right colors (traffic lights turn grey when the system accent color is grey), and gets all standard behavior such as the menu on the Zoom button.

**Describe alternatives you've considered**
None, this needs to be implemented in Legcord itself, because the Electron window needs to be configured for it.

**Additional context**
`win.titleBarStyle = "hiddenInset"` is the main thing needed for this on the Electron side. May need further tweaking after that to align it correctly.

The styles for making the header draggable look like this:

```css
.platform-osx .container_fc4f04 {
	-webkit-app-region: drag;
}
```

There are also others that toggle it to `no-drag`, e.g. on buttons.

**Comment by smartfrigde** [comment]
All I needed to do is enable the overlay titlebar style for macOS users, done here https://github.com/Legcord/Legcord/commit/129dce78fec68f8cfe970b81c82e9df1cbeb31c3

![obraz](https://github.com/user-attachments/assets/bc2ef059-eb5b-4d22-8906-1352138cc4d4)

**Comment by kirb** [comment]
💯 Great stuff, thanks! Do you think they can be scooted over by a few pixels to be centered in the server list? See [`win.setWindowButtonPosition(position)`](https://www.electronjs.org/docs/latest/api/browser-window#winsetwindowbuttonpositionposition-macos)

**Comment by smartfrigde** [comment]
@kirb https://github.com/Legcord/Legcord/commit/baabee8a823b6dc272e5ee5ba5b40d631326e953
:)

**Comment by alexcraviotto** [comment]
> [@kirb](https://github.com/kirb) [baabee8](https://github.com/Legcord/Legcord/commit/baabee8a823b6dc272e5ee5ba5b40d631326e953) :)

How can i set this?

<img width="1751" height="88" alt="Image" src="https://github.com/user-attachments/assets/d62b01b6-5e4a-4ad4-8e7b-7126f6bce66c" />

I'm getting this annoying separation.
