### ISSUE TITLE
Auto update url

### ISSUE THREAD

**Issue by rllola** [smartfrigde/armcord#9]
Hi :wave:,

I am Lola, one of the engineer working on UpdateRocks!. We recently fixed a bug that showed the auto update url from our staging environment.
See in your code :
https://github.com/smartfrigde/armcord/blob/main/utils/updater.js#L8

Don't worry it won't affect you. It is still working. However we suggest you go back to https://www.update.rocks/ and connect again your repo and update the url with the new one.

Let me know if we can help you with anything else.

Cheers,

**Comment by smartfrigde** [comment]
Fixed by this [commit](https://github.com/smartfrigde/armcord/commit/ae47340ed92cc61362aa64d4437e4a74bb2be77a).
Thanks for reporting, your service is great.
